///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, ARA::COM Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : impl_type_int64_vector.h
/// IMPLEMENTATION DATA TYPE NAME     : int64_Vector
/// GENERATED DATE                    : 2025-12-08 15:30:05
///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// CAUTION!! AUTOMATICALLY GENERATED FILE - DO NOT EDIT                                                   
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_ARA_COM_GEN_OSS_TYPE_CPP_IMPL_TYPE_INT64_VECTOR_H
#define PARA_ARA_COM_GEN_OSS_TYPE_CPP_IMPL_TYPE_INT64_VECTOR_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// @uptrace{SWS_CM_00402}
#include <cstdint>
#include <ara/core/vector.h>
#ifdef PARA_DDS_IMPLEMENTATION
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION FOR DDS
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "impl_type_int64_vector.hpp"
#endif /// PARA_DDS_IMPLEMENTATION
/// @uptrace{SWS_CM_10375}
namespace oss
{
namespace type
{
using int64_Vector = ara::core::Vector<std::int64_t>;
 
#ifdef PARA_DDS_IMPLEMENTATION
inline dds::oss::type::int64_Vector int64_Vector_ConvertToDdsType(const oss::type::int64_Vector& src)
{
    return src;
}
 
inline oss::type::int64_Vector int64_Vector_ConvertFromDdsType(const dds::oss::type::int64_Vector& src)
{
    return src;
}
#endif /// PARA_DDS_IMPLEMENTATION
} /// namespace type
} /// namespace oss
#endif /// PARA_ARA_COM_GEN_OSS_TYPE_CPP_IMPL_TYPE_INT64_VECTOR_H