///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, ARA::COM Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : po_si_servicecreator_skeleton.h
/// SERVICE INTERFACE NAME            : PO_SI_ServiceCreator
/// GENERATED DATE                    : 2025-12-05 12:02:28
///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// CAUTION!! AUTOMATICALLY GENERATED FILE - DO NOT EDIT                                                   
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_COM_GEN_OSS_SRV_SCR2PO_SERVICE_INTERFACE_PO_SI_SERVICECREATOR_SKELETON_H
#define PARA_COM_GEN_OSS_SRV_SCR2PO_SERVICE_INTERFACE_PO_SI_SERVICECREATOR_SKELETON_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// @uptrace{SWS_CM_01004}
#include "po_si_servicecreator_common.h"
#include "para/com/skeleton/skeleton_interface.h"
/// @uptrace{SWS_CM_01005}
namespace oss
{
namespace srv
{
namespace SCr2PO
{
/// @uptrace{SWS_CM_01006}
namespace skeleton
{
class PO_SI_ServiceCreatorSkeleton;
/// @uptrace{SWS_CM_01009}
namespace events
{
/// @uptrace{SWS_CM_00003}
class clock
{
public:
    /// @brief Type alias for type of event data
    /// @uptrace{SWS_CM_00162, SWS_CM_90437}
    using SampleType = oss::type::rosgraph_msgs::msg::Clock;
    /// @brief Constructor
    explicit clock(para::com::SkeletonInterface* interface, para::com::SkeletonDdsInterface* ddsInterface, para::com::ServiceProtocol protocol)
        : mInterface(interface)
        , mDdsInterface(ddsInterface)
        , mProtocol(protocol)
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                break;
            }
            case para::com::ServiceProtocol::kIpc :
            {
                break;
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                mDdsInterface->CreateEvent<dds::oss::srv::SCr2PO::ClockEventType>(kCallSign);
                break;
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : break;
        }
    }
    /// @brief Destructor
    virtual ~clock() = default;
    /// @brief Delete copy constructor
    clock(const clock& other) = delete;
    /// @brief Delete copy assignment
    clock& operator=(const clock& other) = delete;
    /// @brief Move constructor
    clock(clock&& other) noexcept
        : mInterface(other.mInterface)
        , mDdsInterface(other.mDdsInterface)
        , mProtocol(other.mProtocol)
    {
    }
    /// @brief Move assignment
    clock& operator=(clock&& other) noexcept
    {
        mInterface = other.mInterface;
        mDdsInterface = other.mDdsInterface;
        mProtocol = other.mProtocol;
        return *this;
    }
    /// @brief Send event with data to subscribing service consumers
    /// @uptrace{SWS_CM_90437}
    ara::core::Result<void> Send(const SampleType& data)
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                const para::serializer::TransformationProps props{};
                para::serializer::Serializer serializer{};
                serializer.write(props, data);
                auto payload = serializer.ensure();
                return mInterface->SendEvent(kCallSign, payload);
            }
            case para::com::ServiceProtocol::kIpc :
            {
                const para::serializer::TransformationProps props{};
                para::serializer::Serializer serializer{};
                serializer.write(props, data);
                auto payload = serializer.ensure();
                return mInterface->SendEvent(kCallSign, payload);
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                dds::oss::srv::SCr2PO::ClockEventType _event_;
                _event_.instance_id() = mDdsInterface->GetInstanceId();
                _event_.data() = oss::type::rosgraph_msgs::msg::Clock_ConvertToDdsType(data);
                return mDdsInterface->SendEvent<dds::oss::srv::SCr2PO::ClockEventType>(kCallSign, _event_);
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : return ara::core::Result<void>(ara::com::ComErrc::kNetworkBindingFailure);
        }
    }
    /// @brief Returns unique pointer about SampleType
    /// @uptrace{SWS_CM_90438}
    ara::core::Result<ara::com::SampleAllocateePtr<SampleType>> Allocate()
    {
        return std::make_unique<SampleType>();
    }
    
private:
    para::com::SkeletonInterface* mInterface;
    para::com::SkeletonDdsInterface* mDdsInterface;
    para::com::ServiceProtocol mProtocol;
    const std::string kCallSign = {"clock"};
};
/// @uptrace{SWS_CM_00003}
class localization_acceleration
{
public:
    /// @brief Type alias for type of event data
    /// @uptrace{SWS_CM_00162, SWS_CM_90437}
    using SampleType = oss::type::geometry_msgs::msg::AccelWithCovarianceStamped;
    /// @brief Constructor
    explicit localization_acceleration(para::com::SkeletonInterface* interface, para::com::SkeletonDdsInterface* ddsInterface, para::com::ServiceProtocol protocol)
        : mInterface(interface)
        , mDdsInterface(ddsInterface)
        , mProtocol(protocol)
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                break;
            }
            case para::com::ServiceProtocol::kIpc :
            {
                break;
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                mDdsInterface->CreateEvent<dds::oss::srv::SCr2PO::AccelWithCovarianceStampedEventType>(kCallSign);
                break;
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : break;
        }
    }
    /// @brief Destructor
    virtual ~localization_acceleration() = default;
    /// @brief Delete copy constructor
    localization_acceleration(const localization_acceleration& other) = delete;
    /// @brief Delete copy assignment
    localization_acceleration& operator=(const localization_acceleration& other) = delete;
    /// @brief Move constructor
    localization_acceleration(localization_acceleration&& other) noexcept
        : mInterface(other.mInterface)
        , mDdsInterface(other.mDdsInterface)
        , mProtocol(other.mProtocol)
    {
    }
    /// @brief Move assignment
    localization_acceleration& operator=(localization_acceleration&& other) noexcept
    {
        mInterface = other.mInterface;
        mDdsInterface = other.mDdsInterface;
        mProtocol = other.mProtocol;
        return *this;
    }
    /// @brief Send event with data to subscribing service consumers
    /// @uptrace{SWS_CM_90437}
    ara::core::Result<void> Send(const SampleType& data)
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                const para::serializer::TransformationProps props{};
                para::serializer::Serializer serializer{};
                serializer.write(props, data);
                auto payload = serializer.ensure();
                return mInterface->SendEvent(kCallSign, payload);
            }
            case para::com::ServiceProtocol::kIpc :
            {
                const para::serializer::TransformationProps props{};
                para::serializer::Serializer serializer{};
                serializer.write(props, data);
                auto payload = serializer.ensure();
                return mInterface->SendEvent(kCallSign, payload);
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                dds::oss::srv::SCr2PO::AccelWithCovarianceStampedEventType _event_;
                _event_.instance_id() = mDdsInterface->GetInstanceId();
                _event_.data() = oss::type::geometry_msgs::msg::AccelWithCovarianceStamped_ConvertToDdsType(data);
                return mDdsInterface->SendEvent<dds::oss::srv::SCr2PO::AccelWithCovarianceStampedEventType>(kCallSign, _event_);
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : return ara::core::Result<void>(ara::com::ComErrc::kNetworkBindingFailure);
        }
    }
    /// @brief Returns unique pointer about SampleType
    /// @uptrace{SWS_CM_90438}
    ara::core::Result<ara::com::SampleAllocateePtr<SampleType>> Allocate()
    {
        return std::make_unique<SampleType>();
    }
    
private:
    para::com::SkeletonInterface* mInterface;
    para::com::SkeletonDdsInterface* mDdsInterface;
    para::com::ServiceProtocol mProtocol;
    const std::string kCallSign = {"localization_acceleration"};
};
/// @uptrace{SWS_CM_00003}
class localization_kinematicstate
{
public:
    /// @brief Type alias for type of event data
    /// @uptrace{SWS_CM_00162, SWS_CM_90437}
    using SampleType = oss::type::nav_msgs::msg::Odometry;
    /// @brief Constructor
    explicit localization_kinematicstate(para::com::SkeletonInterface* interface, para::com::SkeletonDdsInterface* ddsInterface, para::com::ServiceProtocol protocol)
        : mInterface(interface)
        , mDdsInterface(ddsInterface)
        , mProtocol(protocol)
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                break;
            }
            case para::com::ServiceProtocol::kIpc :
            {
                break;
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                mDdsInterface->CreateEvent<dds::oss::srv::SCr2PO::OdometryEventType>(kCallSign);
                break;
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : break;
        }
    }
    /// @brief Destructor
    virtual ~localization_kinematicstate() = default;
    /// @brief Delete copy constructor
    localization_kinematicstate(const localization_kinematicstate& other) = delete;
    /// @brief Delete copy assignment
    localization_kinematicstate& operator=(const localization_kinematicstate& other) = delete;
    /// @brief Move constructor
    localization_kinematicstate(localization_kinematicstate&& other) noexcept
        : mInterface(other.mInterface)
        , mDdsInterface(other.mDdsInterface)
        , mProtocol(other.mProtocol)
    {
    }
    /// @brief Move assignment
    localization_kinematicstate& operator=(localization_kinematicstate&& other) noexcept
    {
        mInterface = other.mInterface;
        mDdsInterface = other.mDdsInterface;
        mProtocol = other.mProtocol;
        return *this;
    }
    /// @brief Send event with data to subscribing service consumers
    /// @uptrace{SWS_CM_90437}
    ara::core::Result<void> Send(const SampleType& data)
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                const para::serializer::TransformationProps props{};
                para::serializer::Serializer serializer{};
                serializer.write(props, data);
                auto payload = serializer.ensure();
                return mInterface->SendEvent(kCallSign, payload);
            }
            case para::com::ServiceProtocol::kIpc :
            {
                const para::serializer::TransformationProps props{};
                para::serializer::Serializer serializer{};
                serializer.write(props, data);
                auto payload = serializer.ensure();
                return mInterface->SendEvent(kCallSign, payload);
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                dds::oss::srv::SCr2PO::OdometryEventType _event_;
                _event_.instance_id() = mDdsInterface->GetInstanceId();
                _event_.data() = oss::type::nav_msgs::msg::Odometry_ConvertToDdsType(data);
                return mDdsInterface->SendEvent<dds::oss::srv::SCr2PO::OdometryEventType>(kCallSign, _event_);
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : return ara::core::Result<void>(ara::com::ComErrc::kNetworkBindingFailure);
        }
    }
    /// @brief Returns unique pointer about SampleType
    /// @uptrace{SWS_CM_90438}
    ara::core::Result<ara::com::SampleAllocateePtr<SampleType>> Allocate()
    {
        return std::make_unique<SampleType>();
    }
    
private:
    para::com::SkeletonInterface* mInterface;
    para::com::SkeletonDdsInterface* mDdsInterface;
    para::com::ServiceProtocol mProtocol;
    const std::string kCallSign = {"localization_kinematicstate"};
};
/// @uptrace{SWS_CM_00003}
class map_vectormap
{
public:
    /// @brief Type alias for type of event data
    /// @uptrace{SWS_CM_00162, SWS_CM_90437}
    using SampleType = oss::type::autoware_map_msgs::msg::LaneletMapBin;
    /// @brief Constructor
    explicit map_vectormap(para::com::SkeletonInterface* interface, para::com::SkeletonDdsInterface* ddsInterface, para::com::ServiceProtocol protocol)
        : mInterface(interface)
        , mDdsInterface(ddsInterface)
        , mProtocol(protocol)
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                break;
            }
            case para::com::ServiceProtocol::kIpc :
            {
                break;
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                mDdsInterface->CreateEvent<dds::oss::srv::SCr2PO::LaneletMapBinEventType>(kCallSign);
                break;
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : break;
        }
    }
    /// @brief Destructor
    virtual ~map_vectormap() = default;
    /// @brief Delete copy constructor
    map_vectormap(const map_vectormap& other) = delete;
    /// @brief Delete copy assignment
    map_vectormap& operator=(const map_vectormap& other) = delete;
    /// @brief Move constructor
    map_vectormap(map_vectormap&& other) noexcept
        : mInterface(other.mInterface)
        , mDdsInterface(other.mDdsInterface)
        , mProtocol(other.mProtocol)
    {
    }
    /// @brief Move assignment
    map_vectormap& operator=(map_vectormap&& other) noexcept
    {
        mInterface = other.mInterface;
        mDdsInterface = other.mDdsInterface;
        mProtocol = other.mProtocol;
        return *this;
    }
    /// @brief Send event with data to subscribing service consumers
    /// @uptrace{SWS_CM_90437}
    ara::core::Result<void> Send(const SampleType& data)
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                const para::serializer::TransformationProps props{};
                para::serializer::Serializer serializer{};
                serializer.write(props, data);
                auto payload = serializer.ensure();
                return mInterface->SendEvent(kCallSign, payload);
            }
            case para::com::ServiceProtocol::kIpc :
            {
                const para::serializer::TransformationProps props{};
                para::serializer::Serializer serializer{};
                serializer.write(props, data);
                auto payload = serializer.ensure();
                return mInterface->SendEvent(kCallSign, payload);
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                dds::oss::srv::SCr2PO::LaneletMapBinEventType _event_;
                _event_.instance_id() = mDdsInterface->GetInstanceId();
                _event_.data() = oss::type::autoware_map_msgs::msg::LaneletMapBin_ConvertToDdsType(data);
                return mDdsInterface->SendEvent<dds::oss::srv::SCr2PO::LaneletMapBinEventType>(kCallSign, _event_);
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : return ara::core::Result<void>(ara::com::ComErrc::kNetworkBindingFailure);
        }
    }
    /// @brief Returns unique pointer about SampleType
    /// @uptrace{SWS_CM_90438}
    ara::core::Result<ara::com::SampleAllocateePtr<SampleType>> Allocate()
    {
        return std::make_unique<SampleType>();
    }
    
private:
    para::com::SkeletonInterface* mInterface;
    para::com::SkeletonDdsInterface* mDdsInterface;
    para::com::ServiceProtocol mProtocol;
    const std::string kCallSign = {"map_vectormap"};
};
/// @uptrace{SWS_CM_00003}
class perception_objectrecognition_objects
{
public:
    /// @brief Type alias for type of event data
    /// @uptrace{SWS_CM_00162, SWS_CM_90437}
    using SampleType = oss::type::autoware_perception_msgs::msg::PredictedObjects;
    /// @brief Constructor
    explicit perception_objectrecognition_objects(para::com::SkeletonInterface* interface, para::com::SkeletonDdsInterface* ddsInterface, para::com::ServiceProtocol protocol)
        : mInterface(interface)
        , mDdsInterface(ddsInterface)
        , mProtocol(protocol)
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                break;
            }
            case para::com::ServiceProtocol::kIpc :
            {
                break;
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                mDdsInterface->CreateEvent<dds::oss::srv::SCr2PO::PredictedObjectsEventType>(kCallSign);
                break;
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : break;
        }
    }
    /// @brief Destructor
    virtual ~perception_objectrecognition_objects() = default;
    /// @brief Delete copy constructor
    perception_objectrecognition_objects(const perception_objectrecognition_objects& other) = delete;
    /// @brief Delete copy assignment
    perception_objectrecognition_objects& operator=(const perception_objectrecognition_objects& other) = delete;
    /// @brief Move constructor
    perception_objectrecognition_objects(perception_objectrecognition_objects&& other) noexcept
        : mInterface(other.mInterface)
        , mDdsInterface(other.mDdsInterface)
        , mProtocol(other.mProtocol)
    {
    }
    /// @brief Move assignment
    perception_objectrecognition_objects& operator=(perception_objectrecognition_objects&& other) noexcept
    {
        mInterface = other.mInterface;
        mDdsInterface = other.mDdsInterface;
        mProtocol = other.mProtocol;
        return *this;
    }
    /// @brief Send event with data to subscribing service consumers
    /// @uptrace{SWS_CM_90437}
    ara::core::Result<void> Send(const SampleType& data)
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                const para::serializer::TransformationProps props{};
                para::serializer::Serializer serializer{};
                serializer.write(props, data);
                auto payload = serializer.ensure();
                return mInterface->SendEvent(kCallSign, payload);
            }
            case para::com::ServiceProtocol::kIpc :
            {
                const para::serializer::TransformationProps props{};
                para::serializer::Serializer serializer{};
                serializer.write(props, data);
                auto payload = serializer.ensure();
                return mInterface->SendEvent(kCallSign, payload);
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                dds::oss::srv::SCr2PO::PredictedObjectsEventType _event_;
                _event_.instance_id() = mDdsInterface->GetInstanceId();
                _event_.data() = oss::type::autoware_perception_msgs::msg::PredictedObjects_ConvertToDdsType(data);
                return mDdsInterface->SendEvent<dds::oss::srv::SCr2PO::PredictedObjectsEventType>(kCallSign, _event_);
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : return ara::core::Result<void>(ara::com::ComErrc::kNetworkBindingFailure);
        }
    }
    /// @brief Returns unique pointer about SampleType
    /// @uptrace{SWS_CM_90438}
    ara::core::Result<ara::com::SampleAllocateePtr<SampleType>> Allocate()
    {
        return std::make_unique<SampleType>();
    }
    
private:
    para::com::SkeletonInterface* mInterface;
    para::com::SkeletonDdsInterface* mDdsInterface;
    para::com::ServiceProtocol mProtocol;
    const std::string kCallSign = {"perception_objectrecognition_objects"};
};
/// @uptrace{SWS_CM_00003}
class perception_obstaclesegmentation_pointcloud
{
public:
    /// @brief Type alias for type of event data
    /// @uptrace{SWS_CM_00162, SWS_CM_90437}
    using SampleType = oss::type::sensor_msgs::msg::PointCloud2;
    /// @brief Constructor
    explicit perception_obstaclesegmentation_pointcloud(para::com::SkeletonInterface* interface, para::com::SkeletonDdsInterface* ddsInterface, para::com::ServiceProtocol protocol)
        : mInterface(interface)
        , mDdsInterface(ddsInterface)
        , mProtocol(protocol)
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                break;
            }
            case para::com::ServiceProtocol::kIpc :
            {
                break;
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                mDdsInterface->CreateEvent<dds::oss::srv::SCr2PO::PointCloud2EventType>(kCallSign);
                break;
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : break;
        }
    }
    /// @brief Destructor
    virtual ~perception_obstaclesegmentation_pointcloud() = default;
    /// @brief Delete copy constructor
    perception_obstaclesegmentation_pointcloud(const perception_obstaclesegmentation_pointcloud& other) = delete;
    /// @brief Delete copy assignment
    perception_obstaclesegmentation_pointcloud& operator=(const perception_obstaclesegmentation_pointcloud& other) = delete;
    /// @brief Move constructor
    perception_obstaclesegmentation_pointcloud(perception_obstaclesegmentation_pointcloud&& other) noexcept
        : mInterface(other.mInterface)
        , mDdsInterface(other.mDdsInterface)
        , mProtocol(other.mProtocol)
    {
    }
    /// @brief Move assignment
    perception_obstaclesegmentation_pointcloud& operator=(perception_obstaclesegmentation_pointcloud&& other) noexcept
    {
        mInterface = other.mInterface;
        mDdsInterface = other.mDdsInterface;
        mProtocol = other.mProtocol;
        return *this;
    }
    /// @brief Send event with data to subscribing service consumers
    /// @uptrace{SWS_CM_90437}
    ara::core::Result<void> Send(const SampleType& data)
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                const para::serializer::TransformationProps props{};
                para::serializer::Serializer serializer{};
                serializer.write(props, data);
                auto payload = serializer.ensure();
                return mInterface->SendEvent(kCallSign, payload);
            }
            case para::com::ServiceProtocol::kIpc :
            {
                const para::serializer::TransformationProps props{};
                para::serializer::Serializer serializer{};
                serializer.write(props, data);
                auto payload = serializer.ensure();
                return mInterface->SendEvent(kCallSign, payload);
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                dds::oss::srv::SCr2PO::PointCloud2EventType _event_;
                _event_.instance_id() = mDdsInterface->GetInstanceId();
                _event_.data() = oss::type::sensor_msgs::msg::PointCloud2_ConvertToDdsType(data);
                return mDdsInterface->SendEvent<dds::oss::srv::SCr2PO::PointCloud2EventType>(kCallSign, _event_);
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : return ara::core::Result<void>(ara::com::ComErrc::kNetworkBindingFailure);
        }
    }
    /// @brief Returns unique pointer about SampleType
    /// @uptrace{SWS_CM_90438}
    ara::core::Result<ara::com::SampleAllocateePtr<SampleType>> Allocate()
    {
        return std::make_unique<SampleType>();
    }
    
private:
    para::com::SkeletonInterface* mInterface;
    para::com::SkeletonDdsInterface* mDdsInterface;
    para::com::ServiceProtocol mProtocol;
    const std::string kCallSign = {"perception_obstaclesegmentation_pointcloud"};
};
/// @uptrace{SWS_CM_00003}
class perception_occupancygridmap_map
{
public:
    /// @brief Type alias for type of event data
    /// @uptrace{SWS_CM_00162, SWS_CM_90437}
    using SampleType = oss::type::nav_msgs::msg::OccupancyGrid;
    /// @brief Constructor
    explicit perception_occupancygridmap_map(para::com::SkeletonInterface* interface, para::com::SkeletonDdsInterface* ddsInterface, para::com::ServiceProtocol protocol)
        : mInterface(interface)
        , mDdsInterface(ddsInterface)
        , mProtocol(protocol)
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                break;
            }
            case para::com::ServiceProtocol::kIpc :
            {
                break;
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                mDdsInterface->CreateEvent<dds::oss::srv::SCr2PO::OccupancyGridEventType>(kCallSign);
                break;
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : break;
        }
    }
    /// @brief Destructor
    virtual ~perception_occupancygridmap_map() = default;
    /// @brief Delete copy constructor
    perception_occupancygridmap_map(const perception_occupancygridmap_map& other) = delete;
    /// @brief Delete copy assignment
    perception_occupancygridmap_map& operator=(const perception_occupancygridmap_map& other) = delete;
    /// @brief Move constructor
    perception_occupancygridmap_map(perception_occupancygridmap_map&& other) noexcept
        : mInterface(other.mInterface)
        , mDdsInterface(other.mDdsInterface)
        , mProtocol(other.mProtocol)
    {
    }
    /// @brief Move assignment
    perception_occupancygridmap_map& operator=(perception_occupancygridmap_map&& other) noexcept
    {
        mInterface = other.mInterface;
        mDdsInterface = other.mDdsInterface;
        mProtocol = other.mProtocol;
        return *this;
    }
    /// @brief Send event with data to subscribing service consumers
    /// @uptrace{SWS_CM_90437}
    ara::core::Result<void> Send(const SampleType& data)
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                const para::serializer::TransformationProps props{};
                para::serializer::Serializer serializer{};
                serializer.write(props, data);
                auto payload = serializer.ensure();
                return mInterface->SendEvent(kCallSign, payload);
            }
            case para::com::ServiceProtocol::kIpc :
            {
                const para::serializer::TransformationProps props{};
                para::serializer::Serializer serializer{};
                serializer.write(props, data);
                auto payload = serializer.ensure();
                return mInterface->SendEvent(kCallSign, payload);
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                dds::oss::srv::SCr2PO::OccupancyGridEventType _event_;
                _event_.instance_id() = mDdsInterface->GetInstanceId();
                _event_.data() = oss::type::nav_msgs::msg::OccupancyGrid_ConvertToDdsType(data);
                return mDdsInterface->SendEvent<dds::oss::srv::SCr2PO::OccupancyGridEventType>(kCallSign, _event_);
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : return ara::core::Result<void>(ara::com::ComErrc::kNetworkBindingFailure);
        }
    }
    /// @brief Returns unique pointer about SampleType
    /// @uptrace{SWS_CM_90438}
    ara::core::Result<ara::com::SampleAllocateePtr<SampleType>> Allocate()
    {
        return std::make_unique<SampleType>();
    }
    
private:
    para::com::SkeletonInterface* mInterface;
    para::com::SkeletonDdsInterface* mDdsInterface;
    para::com::ServiceProtocol mProtocol;
    const std::string kCallSign = {"perception_occupancygridmap_map"};
};
/// @uptrace{SWS_CM_00003}
class perception_trafficlightrecognition_trafficsignals
{
public:
    /// @brief Type alias for type of event data
    /// @uptrace{SWS_CM_00162, SWS_CM_90437}
    using SampleType = oss::type::autoware_msgs::autoware_perception_msgs::msg::TrafficLightGroupArray;
    /// @brief Constructor
    explicit perception_trafficlightrecognition_trafficsignals(para::com::SkeletonInterface* interface, para::com::SkeletonDdsInterface* ddsInterface, para::com::ServiceProtocol protocol)
        : mInterface(interface)
        , mDdsInterface(ddsInterface)
        , mProtocol(protocol)
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                break;
            }
            case para::com::ServiceProtocol::kIpc :
            {
                break;
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                mDdsInterface->CreateEvent<dds::oss::srv::SCr2PO::TrafficLightGroupArrayEventType>(kCallSign);
                break;
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : break;
        }
    }
    /// @brief Destructor
    virtual ~perception_trafficlightrecognition_trafficsignals() = default;
    /// @brief Delete copy constructor
    perception_trafficlightrecognition_trafficsignals(const perception_trafficlightrecognition_trafficsignals& other) = delete;
    /// @brief Delete copy assignment
    perception_trafficlightrecognition_trafficsignals& operator=(const perception_trafficlightrecognition_trafficsignals& other) = delete;
    /// @brief Move constructor
    perception_trafficlightrecognition_trafficsignals(perception_trafficlightrecognition_trafficsignals&& other) noexcept
        : mInterface(other.mInterface)
        , mDdsInterface(other.mDdsInterface)
        , mProtocol(other.mProtocol)
    {
    }
    /// @brief Move assignment
    perception_trafficlightrecognition_trafficsignals& operator=(perception_trafficlightrecognition_trafficsignals&& other) noexcept
    {
        mInterface = other.mInterface;
        mDdsInterface = other.mDdsInterface;
        mProtocol = other.mProtocol;
        return *this;
    }
    /// @brief Send event with data to subscribing service consumers
    /// @uptrace{SWS_CM_90437}
    ara::core::Result<void> Send(const SampleType& data)
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                const para::serializer::TransformationProps props{};
                para::serializer::Serializer serializer{};
                serializer.write(props, data);
                auto payload = serializer.ensure();
                return mInterface->SendEvent(kCallSign, payload);
            }
            case para::com::ServiceProtocol::kIpc :
            {
                const para::serializer::TransformationProps props{};
                para::serializer::Serializer serializer{};
                serializer.write(props, data);
                auto payload = serializer.ensure();
                return mInterface->SendEvent(kCallSign, payload);
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                dds::oss::srv::SCr2PO::TrafficLightGroupArrayEventType _event_;
                _event_.instance_id() = mDdsInterface->GetInstanceId();
                _event_.data() = oss::type::autoware_msgs::autoware_perception_msgs::msg::TrafficLightGroupArray_ConvertToDdsType(data);
                return mDdsInterface->SendEvent<dds::oss::srv::SCr2PO::TrafficLightGroupArrayEventType>(kCallSign, _event_);
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : return ara::core::Result<void>(ara::com::ComErrc::kNetworkBindingFailure);
        }
    }
    /// @brief Returns unique pointer about SampleType
    /// @uptrace{SWS_CM_90438}
    ara::core::Result<ara::com::SampleAllocateePtr<SampleType>> Allocate()
    {
        return std::make_unique<SampleType>();
    }
    
private:
    para::com::SkeletonInterface* mInterface;
    para::com::SkeletonDdsInterface* mDdsInterface;
    para::com::ServiceProtocol mProtocol;
    const std::string kCallSign = {"perception_trafficlightrecognition_trafficsignals"};
};
/// @uptrace{SWS_CM_00003}
class planning_scenarioplanning_lanedriving_behaviorplanning_behaviorpathplanner_input_lateraloffset
{
public:
    /// @brief Type alias for type of event data
    /// @uptrace{SWS_CM_00162, SWS_CM_90437}
    using SampleType = oss::type::tier4_planning_msgs::msg::LateralOffset;
    /// @brief Constructor
    explicit planning_scenarioplanning_lanedriving_behaviorplanning_behaviorpathplanner_input_lateraloffset(para::com::SkeletonInterface* interface, para::com::SkeletonDdsInterface* ddsInterface, para::com::ServiceProtocol protocol)
        : mInterface(interface)
        , mDdsInterface(ddsInterface)
        , mProtocol(protocol)
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                break;
            }
            case para::com::ServiceProtocol::kIpc :
            {
                break;
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                mDdsInterface->CreateEvent<dds::oss::srv::SCr2PO::LateralOffsetEventType>(kCallSign);
                break;
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : break;
        }
    }
    /// @brief Destructor
    virtual ~planning_scenarioplanning_lanedriving_behaviorplanning_behaviorpathplanner_input_lateraloffset() = default;
    /// @brief Delete copy constructor
    planning_scenarioplanning_lanedriving_behaviorplanning_behaviorpathplanner_input_lateraloffset(const planning_scenarioplanning_lanedriving_behaviorplanning_behaviorpathplanner_input_lateraloffset& other) = delete;
    /// @brief Delete copy assignment
    planning_scenarioplanning_lanedriving_behaviorplanning_behaviorpathplanner_input_lateraloffset& operator=(const planning_scenarioplanning_lanedriving_behaviorplanning_behaviorpathplanner_input_lateraloffset& other) = delete;
    /// @brief Move constructor
    planning_scenarioplanning_lanedriving_behaviorplanning_behaviorpathplanner_input_lateraloffset(planning_scenarioplanning_lanedriving_behaviorplanning_behaviorpathplanner_input_lateraloffset&& other) noexcept
        : mInterface(other.mInterface)
        , mDdsInterface(other.mDdsInterface)
        , mProtocol(other.mProtocol)
    {
    }
    /// @brief Move assignment
    planning_scenarioplanning_lanedriving_behaviorplanning_behaviorpathplanner_input_lateraloffset& operator=(planning_scenarioplanning_lanedriving_behaviorplanning_behaviorpathplanner_input_lateraloffset&& other) noexcept
    {
        mInterface = other.mInterface;
        mDdsInterface = other.mDdsInterface;
        mProtocol = other.mProtocol;
        return *this;
    }
    /// @brief Send event with data to subscribing service consumers
    /// @uptrace{SWS_CM_90437}
    ara::core::Result<void> Send(const SampleType& data)
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                const para::serializer::TransformationProps props{};
                para::serializer::Serializer serializer{};
                serializer.write(props, data);
                auto payload = serializer.ensure();
                return mInterface->SendEvent(kCallSign, payload);
            }
            case para::com::ServiceProtocol::kIpc :
            {
                const para::serializer::TransformationProps props{};
                para::serializer::Serializer serializer{};
                serializer.write(props, data);
                auto payload = serializer.ensure();
                return mInterface->SendEvent(kCallSign, payload);
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                dds::oss::srv::SCr2PO::LateralOffsetEventType _event_;
                _event_.instance_id() = mDdsInterface->GetInstanceId();
                _event_.data() = oss::type::tier4_planning_msgs::msg::LateralOffset_ConvertToDdsType(data);
                return mDdsInterface->SendEvent<dds::oss::srv::SCr2PO::LateralOffsetEventType>(kCallSign, _event_);
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : return ara::core::Result<void>(ara::com::ComErrc::kNetworkBindingFailure);
        }
    }
    /// @brief Returns unique pointer about SampleType
    /// @uptrace{SWS_CM_90438}
    ara::core::Result<ara::com::SampleAllocateePtr<SampleType>> Allocate()
    {
        return std::make_unique<SampleType>();
    }
    
private:
    para::com::SkeletonInterface* mInterface;
    para::com::SkeletonDdsInterface* mDdsInterface;
    para::com::ServiceProtocol mProtocol;
    const std::string kCallSign = {"planning_scenarioplanning_lanedriving_behaviorplanning_behaviorpathplanner_input_lateraloffset"};
};
/// @uptrace{SWS_CM_00003}
class planning_scenarioplanning_maxvelocitydefault
{
public:
    /// @brief Type alias for type of event data
    /// @uptrace{SWS_CM_00162, SWS_CM_90437}
    using SampleType = oss::type::tier4_planning_msgs::msg::VelocityLimit;
    /// @brief Constructor
    explicit planning_scenarioplanning_maxvelocitydefault(para::com::SkeletonInterface* interface, para::com::SkeletonDdsInterface* ddsInterface, para::com::ServiceProtocol protocol)
        : mInterface(interface)
        , mDdsInterface(ddsInterface)
        , mProtocol(protocol)
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                break;
            }
            case para::com::ServiceProtocol::kIpc :
            {
                break;
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                mDdsInterface->CreateEvent<dds::oss::srv::SCr2PO::VelocityLimitEventType>(kCallSign);
                break;
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : break;
        }
    }
    /// @brief Destructor
    virtual ~planning_scenarioplanning_maxvelocitydefault() = default;
    /// @brief Delete copy constructor
    planning_scenarioplanning_maxvelocitydefault(const planning_scenarioplanning_maxvelocitydefault& other) = delete;
    /// @brief Delete copy assignment
    planning_scenarioplanning_maxvelocitydefault& operator=(const planning_scenarioplanning_maxvelocitydefault& other) = delete;
    /// @brief Move constructor
    planning_scenarioplanning_maxvelocitydefault(planning_scenarioplanning_maxvelocitydefault&& other) noexcept
        : mInterface(other.mInterface)
        , mDdsInterface(other.mDdsInterface)
        , mProtocol(other.mProtocol)
    {
    }
    /// @brief Move assignment
    planning_scenarioplanning_maxvelocitydefault& operator=(planning_scenarioplanning_maxvelocitydefault&& other) noexcept
    {
        mInterface = other.mInterface;
        mDdsInterface = other.mDdsInterface;
        mProtocol = other.mProtocol;
        return *this;
    }
    /// @brief Send event with data to subscribing service consumers
    /// @uptrace{SWS_CM_90437}
    ara::core::Result<void> Send(const SampleType& data)
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                const para::serializer::TransformationProps props{};
                para::serializer::Serializer serializer{};
                serializer.write(props, data);
                auto payload = serializer.ensure();
                return mInterface->SendEvent(kCallSign, payload);
            }
            case para::com::ServiceProtocol::kIpc :
            {
                const para::serializer::TransformationProps props{};
                para::serializer::Serializer serializer{};
                serializer.write(props, data);
                auto payload = serializer.ensure();
                return mInterface->SendEvent(kCallSign, payload);
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                dds::oss::srv::SCr2PO::VelocityLimitEventType _event_;
                _event_.instance_id() = mDdsInterface->GetInstanceId();
                _event_.data() = oss::type::tier4_planning_msgs::msg::VelocityLimit_ConvertToDdsType(data);
                return mDdsInterface->SendEvent<dds::oss::srv::SCr2PO::VelocityLimitEventType>(kCallSign, _event_);
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : return ara::core::Result<void>(ara::com::ComErrc::kNetworkBindingFailure);
        }
    }
    /// @brief Returns unique pointer about SampleType
    /// @uptrace{SWS_CM_90438}
    ara::core::Result<ara::com::SampleAllocateePtr<SampleType>> Allocate()
    {
        return std::make_unique<SampleType>();
    }
    
private:
    para::com::SkeletonInterface* mInterface;
    para::com::SkeletonDdsInterface* mDdsInterface;
    para::com::ServiceProtocol mProtocol;
    const std::string kCallSign = {"planning_scenarioplanning_maxvelocitydefault"};
};
/// @uptrace{SWS_CM_00003}
class system_operationmode_state
{
public:
    /// @brief Type alias for type of event data
    /// @uptrace{SWS_CM_00162, SWS_CM_90437}
    using SampleType = oss::type::autoware_adapi_v1_msgs::msg::OperationModeState;
    /// @brief Constructor
    explicit system_operationmode_state(para::com::SkeletonInterface* interface, para::com::SkeletonDdsInterface* ddsInterface, para::com::ServiceProtocol protocol)
        : mInterface(interface)
        , mDdsInterface(ddsInterface)
        , mProtocol(protocol)
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                break;
            }
            case para::com::ServiceProtocol::kIpc :
            {
                break;
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                mDdsInterface->CreateEvent<dds::oss::srv::SCr2PO::OperationModeStateEventType>(kCallSign);
                break;
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : break;
        }
    }
    /// @brief Destructor
    virtual ~system_operationmode_state() = default;
    /// @brief Delete copy constructor
    system_operationmode_state(const system_operationmode_state& other) = delete;
    /// @brief Delete copy assignment
    system_operationmode_state& operator=(const system_operationmode_state& other) = delete;
    /// @brief Move constructor
    system_operationmode_state(system_operationmode_state&& other) noexcept
        : mInterface(other.mInterface)
        , mDdsInterface(other.mDdsInterface)
        , mProtocol(other.mProtocol)
    {
    }
    /// @brief Move assignment
    system_operationmode_state& operator=(system_operationmode_state&& other) noexcept
    {
        mInterface = other.mInterface;
        mDdsInterface = other.mDdsInterface;
        mProtocol = other.mProtocol;
        return *this;
    }
    /// @brief Send event with data to subscribing service consumers
    /// @uptrace{SWS_CM_90437}
    ara::core::Result<void> Send(const SampleType& data)
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                const para::serializer::TransformationProps props{};
                para::serializer::Serializer serializer{};
                serializer.write(props, data);
                auto payload = serializer.ensure();
                return mInterface->SendEvent(kCallSign, payload);
            }
            case para::com::ServiceProtocol::kIpc :
            {
                const para::serializer::TransformationProps props{};
                para::serializer::Serializer serializer{};
                serializer.write(props, data);
                auto payload = serializer.ensure();
                return mInterface->SendEvent(kCallSign, payload);
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                dds::oss::srv::SCr2PO::OperationModeStateEventType _event_;
                _event_.instance_id() = mDdsInterface->GetInstanceId();
                _event_.data() = oss::type::autoware_adapi_v1_msgs::msg::OperationModeState_ConvertToDdsType(data);
                return mDdsInterface->SendEvent<dds::oss::srv::SCr2PO::OperationModeStateEventType>(kCallSign, _event_);
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : return ara::core::Result<void>(ara::com::ComErrc::kNetworkBindingFailure);
        }
    }
    /// @brief Returns unique pointer about SampleType
    /// @uptrace{SWS_CM_90438}
    ara::core::Result<ara::com::SampleAllocateePtr<SampleType>> Allocate()
    {
        return std::make_unique<SampleType>();
    }
    
private:
    para::com::SkeletonInterface* mInterface;
    para::com::SkeletonDdsInterface* mDdsInterface;
    para::com::ServiceProtocol mProtocol;
    const std::string kCallSign = {"system_operationmode_state"};
};
} /// namespace events
/// @uptrace{SWS_CM_01031}
namespace fields
{
} /// namespace fields
/// @uptrace{SWS_CM_00002}
class PO_SI_ServiceCreatorSkeleton
{
public:
    /// @uptrace{SWS_CM_00191}
    /// @brief Constructor
    /// @uptrace{SWS_CM_00002, SWS_CM_00152}
    PO_SI_ServiceCreatorSkeleton(ara::core::InstanceSpecifier instanceSpec, ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent)
        : mInterface(std::make_unique<para::com::SkeletonInterface>(instanceSpec, mode))
        , mDdsInterface(std::make_unique<para::com::SkeletonDdsInterface>(instanceSpec, mode))
        , mProtocol(para::com::GetServiceProtocol(instanceSpec))
        , clock(mInterface.get(), mDdsInterface.get(), mProtocol)
        , localization_acceleration(mInterface.get(), mDdsInterface.get(), mProtocol)
        , localization_kinematicstate(mInterface.get(), mDdsInterface.get(), mProtocol)
        , map_vectormap(mInterface.get(), mDdsInterface.get(), mProtocol)
        , perception_objectrecognition_objects(mInterface.get(), mDdsInterface.get(), mProtocol)
        , perception_obstaclesegmentation_pointcloud(mInterface.get(), mDdsInterface.get(), mProtocol)
        , perception_occupancygridmap_map(mInterface.get(), mDdsInterface.get(), mProtocol)
        , perception_trafficlightrecognition_trafficsignals(mInterface.get(), mDdsInterface.get(), mProtocol)
        , planning_scenarioplanning_lanedriving_behaviorplanning_behaviorpathplanner_input_lateraloffset(mInterface.get(), mDdsInterface.get(), mProtocol)
        , planning_scenarioplanning_maxvelocitydefault(mInterface.get(), mDdsInterface.get(), mProtocol)
        , system_operationmode_state(mInterface.get(), mDdsInterface.get(), mProtocol)
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                mInterface->SetE2EErrorHandler([this](const ara::com::e2e::E2EErrorDomain& errorCode, ara::com::e2e::DataID dataID, ara::com::e2e::MessageCounter messageCounter) {
                    E2EErrorHandler(errorCode, dataID, messageCounter);
                });
                break;
            }
            case para::com::ServiceProtocol::kIpc :
            {
                mInterface->SetE2EErrorHandler([this](const ara::com::e2e::E2EErrorDomain& errorCode, ara::com::e2e::DataID dataID, ara::com::e2e::MessageCounter messageCounter) {
                    E2EErrorHandler(errorCode, dataID, messageCounter);
                });
                break;
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                break;
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : break;
        }
    }
    /// @brief Destructor
    virtual ~PO_SI_ServiceCreatorSkeleton() = default;
    /// @brief Delete copy constructor
    /// @uptrace{SWS_CM_00134}
    PO_SI_ServiceCreatorSkeleton(const PO_SI_ServiceCreatorSkeleton& other) = delete;
    /// @brief Delete copy assignment
    /// @uptrace{SWS_CM_00134}
    PO_SI_ServiceCreatorSkeleton& operator=(const PO_SI_ServiceCreatorSkeleton& other) = delete;
    /// @brief Move constructor
    /// @uptrace{SWS_CM_00135}
    PO_SI_ServiceCreatorSkeleton(PO_SI_ServiceCreatorSkeleton&& other) noexcept
        : mInterface(std::move(other.mInterface))
        , mDdsInterface(std::move(other.mDdsInterface))
        , mProtocol(std::move(other.mProtocol))
        , clock(std::move(other.clock))
        , localization_acceleration(std::move(other.localization_acceleration))
        , localization_kinematicstate(std::move(other.localization_kinematicstate))
        , map_vectormap(std::move(other.map_vectormap))
        , perception_objectrecognition_objects(std::move(other.perception_objectrecognition_objects))
        , perception_obstaclesegmentation_pointcloud(std::move(other.perception_obstaclesegmentation_pointcloud))
        , perception_occupancygridmap_map(std::move(other.perception_occupancygridmap_map))
        , perception_trafficlightrecognition_trafficsignals(std::move(other.perception_trafficlightrecognition_trafficsignals))
        , planning_scenarioplanning_lanedriving_behaviorplanning_behaviorpathplanner_input_lateraloffset(std::move(other.planning_scenarioplanning_lanedriving_behaviorplanning_behaviorpathplanner_input_lateraloffset))
        , planning_scenarioplanning_maxvelocitydefault(std::move(other.planning_scenarioplanning_maxvelocitydefault))
        , system_operationmode_state(std::move(other.system_operationmode_state))
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                mInterface->SetE2EErrorHandler([this](const ara::com::e2e::E2EErrorDomain& errorCode, ara::com::e2e::DataID dataID, ara::com::e2e::MessageCounter messageCounter) {
                    E2EErrorHandler(errorCode, dataID, messageCounter);
                });
            }
            case para::com::ServiceProtocol::kIpc :
            {
                mInterface->SetE2EErrorHandler([this](const ara::com::e2e::E2EErrorDomain& errorCode, ara::com::e2e::DataID dataID, ara::com::e2e::MessageCounter messageCounter) {
                    E2EErrorHandler(errorCode, dataID, messageCounter);
                });
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : break;
        }
        other.mInterface.reset();
        other.mDdsInterface.reset();
    }
    /// @brief Move assignment
    /// @uptrace{SWS_CM_00135}
    PO_SI_ServiceCreatorSkeleton& operator=(PO_SI_ServiceCreatorSkeleton&& other) noexcept
    {
        mInterface = std::move(other.mInterface);
        mDdsInterface = std::move(other.mDdsInterface);
        mProtocol = std::move(other.mProtocol);
        clock = std::move(other.clock);
        localization_acceleration = std::move(other.localization_acceleration);
        localization_kinematicstate = std::move(other.localization_kinematicstate);
        map_vectormap = std::move(other.map_vectormap);
        perception_objectrecognition_objects = std::move(other.perception_objectrecognition_objects);
        perception_obstaclesegmentation_pointcloud = std::move(other.perception_obstaclesegmentation_pointcloud);
        perception_occupancygridmap_map = std::move(other.perception_occupancygridmap_map);
        perception_trafficlightrecognition_trafficsignals = std::move(other.perception_trafficlightrecognition_trafficsignals);
        planning_scenarioplanning_lanedriving_behaviorplanning_behaviorpathplanner_input_lateraloffset = std::move(other.planning_scenarioplanning_lanedriving_behaviorplanning_behaviorpathplanner_input_lateraloffset);
        planning_scenarioplanning_maxvelocitydefault = std::move(other.planning_scenarioplanning_maxvelocitydefault);
        system_operationmode_state = std::move(other.system_operationmode_state);
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                mInterface->SetE2EErrorHandler([this](const ara::com::e2e::E2EErrorDomain& errorCode, ara::com::e2e::DataID dataID, ara::com::e2e::MessageCounter messageCounter) {
                    E2EErrorHandler(errorCode, dataID, messageCounter);
                });
            }
            case para::com::ServiceProtocol::kIpc :
            {
                mInterface->SetE2EErrorHandler([this](const ara::com::e2e::E2EErrorDomain& errorCode, ara::com::e2e::DataID dataID, ara::com::e2e::MessageCounter messageCounter) {
                    E2EErrorHandler(errorCode, dataID, messageCounter);
                });
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : break;
        }
        other.mInterface.reset();
        other.mDdsInterface.reset();
        return *this;
    }
    /// @brief Send "OfferService" message to Communication Management
    /// @uptrace{SWS_CM_00101}
    ara::core::Result<void> OfferService()
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                return mInterface->OfferService();
            }
            case para::com::ServiceProtocol::kIpc :
            {
            	return mInterface->OfferService();
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
            	return mDdsInterface->OfferService();
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : return ara::core::Result<void>(ara::com::ComErrc::kNetworkBindingFailure);
        }
    }
    /// @brief Send "StopOfferService" message to Communication Management
    /// @uptrace{SWS_CM_00111}
    void StopOfferService()
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                mInterface->StopOfferService();
                break;
            }
            case para::com::ServiceProtocol::kIpc :
            {
                mInterface->StopOfferService();
                break;
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                mDdsInterface->StopOfferService();
                break;
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : break;
        }
    }
    /// @brief Allows the implementation providing the service method to trigger the execution of the next service consumer method call at a specific point of time
    ///        if the processing mode is set to kPoll.
    /// @note This function requires that ara::com::MethodCallProcessingMode is configured as kPoll by constructor
    /// @uptrace{SWS_CM_00199}
    ara::core::Future<bool> ProcessNextMethodCall()
    {
        ara::core::Promise<bool> promise{};
        ara::core::Result<bool> ret{false};
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                ret = mInterface->ProcessNextMethodCall();
                break;
            }
            case para::com::ServiceProtocol::kIpc :
            {
                ret = mInterface->ProcessNextMethodCall();
                break;
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                ret = mDdsInterface->ProcessNextMethodCall();
                break;
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : break;
        }
        if (ret.HasValue())
        {
            promise.set_value(ret.Value());
        }
        else
        {
            promise.SetError(ret.Error());
        }
        return promise.get_future();
    }
    /// @brief In case the call to E2E_check indicated a failed E2E check of the request message, the server application can get notified via an E2E error handler.
    /// @uptrace{SWS_CM_10470}
    virtual void E2EErrorHandler(const ara::com::e2e::E2EErrorDomain& errorCode, ara::com::e2e::DataID dataID, ara::com::e2e::MessageCounter messageCounter)
    {
    }
    
private:
    std::unique_ptr<para::com::SkeletonInterface> mInterface;
    std::unique_ptr<para::com::SkeletonDdsInterface> mDdsInterface;
    para::com::ServiceProtocol mProtocol;
    
public:
    /// @brief Event, clock
    events::clock clock;
    /// @brief Event, localization_acceleration
    events::localization_acceleration localization_acceleration;
    /// @brief Event, localization_kinematicstate
    events::localization_kinematicstate localization_kinematicstate;
    /// @brief Event, map_vectormap
    events::map_vectormap map_vectormap;
    /// @brief Event, perception_objectrecognition_objects
    events::perception_objectrecognition_objects perception_objectrecognition_objects;
    /// @brief Event, perception_obstaclesegmentation_pointcloud
    events::perception_obstaclesegmentation_pointcloud perception_obstaclesegmentation_pointcloud;
    /// @brief Event, perception_occupancygridmap_map
    events::perception_occupancygridmap_map perception_occupancygridmap_map;
    /// @brief Event, perception_trafficlightrecognition_trafficsignals
    events::perception_trafficlightrecognition_trafficsignals perception_trafficlightrecognition_trafficsignals;
    /// @brief Event, planning_scenarioplanning_lanedriving_behaviorplanning_behaviorpathplanner_input_lateraloffset
    events::planning_scenarioplanning_lanedriving_behaviorplanning_behaviorpathplanner_input_lateraloffset planning_scenarioplanning_lanedriving_behaviorplanning_behaviorpathplanner_input_lateraloffset;
    /// @brief Event, planning_scenarioplanning_maxvelocitydefault
    events::planning_scenarioplanning_maxvelocitydefault planning_scenarioplanning_maxvelocitydefault;
    /// @brief Event, system_operationmode_state
    events::system_operationmode_state system_operationmode_state;
    
private:
};
} /// namespace skeleton
} /// namespace SCr2PO
} /// namespace srv
} /// namespace oss
#endif /// PARA_COM_GEN_OSS_SRV_SCR2PO_SERVICE_INTERFACE_PO_SI_SERVICECREATOR_SKELETON_H