///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, ARA::COM Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : impl_type_accelwithcovariance.h
/// IMPLEMENTATION DATA TYPE NAME     : AccelWithCovariance
/// GENERATED DATE                    : 2025-12-12 16:16:56
///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// CAUTION!! AUTOMATICALLY GENERATED FILE - DO NOT EDIT                                                   
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_ARA_COM_GEN_OSS_TYPE_GEOMETRY_MSGS_MSG_CPP_IMPL_TYPE_ACCELWITHCOVARIANCE_H
#define PARA_ARA_COM_GEN_OSS_TYPE_GEOMETRY_MSGS_MSG_CPP_IMPL_TYPE_ACCELWITHCOVARIANCE_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// @uptrace{SWS_CM_00402}
#include <ara/core/structure.h>
#include "oss/type/geometry_msgs/msg/impl_type_accel.h"
#include "oss/type/impl_type_double_36.h"
#ifdef PARA_DDS_IMPLEMENTATION
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION FOR DDS
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "impl_type_accelwithcovariance.hpp"
#endif /// PARA_DDS_IMPLEMENTATION
/// @uptrace{SWS_CM_10375}
namespace oss
{
namespace type
{
namespace geometry_msgs
{
namespace msg
{
struct AccelWithCovariance
{
    oss::type::geometry_msgs::msg::Accel accel;
    oss::type::double_36 covariance;

    /// @brief constructor
    AccelWithCovariance() = default;
    AccelWithCovariance(const oss::type::geometry_msgs::msg::Accel& _accel, const oss::type::double_36& _covariance)
        : accel{_accel}
        , covariance{_covariance}
    {
    }

    /// @note marker for serialize, don't touch
    PARA_STRUCTURE(AccelWithCovariance, accel, covariance);
};
 
#ifdef PARA_DDS_IMPLEMENTATION
inline dds::oss::type::geometry_msgs::msg::AccelWithCovariance AccelWithCovariance_ConvertToDdsType(const oss::type::geometry_msgs::msg::AccelWithCovariance& src)
{
    dds::oss::type::geometry_msgs::msg::AccelWithCovariance dst;
    dst.accel() = oss::type::geometry_msgs::msg::Accel_ConvertToDdsType(src.accel);
    dst.covariance() = oss::type::double_36_ConvertToDdsType(src.covariance);
    return dst;
}
 
inline oss::type::geometry_msgs::msg::AccelWithCovariance AccelWithCovariance_ConvertFromDdsType(const dds::oss::type::geometry_msgs::msg::AccelWithCovariance& src)
{
    oss::type::geometry_msgs::msg::AccelWithCovariance dst;
    dst.accel = oss::type::geometry_msgs::msg::Accel_ConvertFromDdsType(src.accel());
    dst.covariance = oss::type::double_36_ConvertFromDdsType(src.covariance());
    return dst;
}
#endif /// PARA_DDS_IMPLEMENTATION
} /// namespace msg
} /// namespace geometry_msgs
} /// namespace type
} /// namespace oss
#endif /// PARA_ARA_COM_GEN_OSS_TYPE_GEOMETRY_MSGS_MSG_CPP_IMPL_TYPE_ACCELWITHCOVARIANCE_H