///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, ARA::COM Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : impl_type_twistwithcovariance.h
/// IMPLEMENTATION DATA TYPE NAME     : TwistWithCovariance
/// GENERATED DATE                    : 2025-12-12 16:16:56
///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// CAUTION!! AUTOMATICALLY GENERATED FILE - DO NOT EDIT                                                   
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_ARA_COM_GEN_OSS_TYPE_GEOMETRY_MSGS_MSG_CPP_IMPL_TYPE_TWISTWITHCOVARIANCE_H
#define PARA_ARA_COM_GEN_OSS_TYPE_GEOMETRY_MSGS_MSG_CPP_IMPL_TYPE_TWISTWITHCOVARIANCE_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// @uptrace{SWS_CM_00402}
#include <ara/core/structure.h>
#include "oss/type/geometry_msgs/msg/impl_type_twist.h"
#include "oss/type/impl_type_double_36.h"
#ifdef PARA_DDS_IMPLEMENTATION
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION FOR DDS
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "impl_type_twistwithcovariance.hpp"
#endif /// PARA_DDS_IMPLEMENTATION
/// @uptrace{SWS_CM_10375}
namespace oss
{
namespace type
{
namespace geometry_msgs
{
namespace msg
{
struct TwistWithCovariance
{
    oss::type::geometry_msgs::msg::Twist twist;
    oss::type::double_36 covariance;

    /// @brief constructor
    TwistWithCovariance() = default;
    TwistWithCovariance(const oss::type::geometry_msgs::msg::Twist& _twist, const oss::type::double_36& _covariance)
        : twist{_twist}
        , covariance{_covariance}
    {
    }

    /// @note marker for serialize, don't touch
    PARA_STRUCTURE(TwistWithCovariance, twist, covariance);
};
 
#ifdef PARA_DDS_IMPLEMENTATION
inline dds::oss::type::geometry_msgs::msg::TwistWithCovariance TwistWithCovariance_ConvertToDdsType(const oss::type::geometry_msgs::msg::TwistWithCovariance& src)
{
    dds::oss::type::geometry_msgs::msg::TwistWithCovariance dst;
    dst.twist() = oss::type::geometry_msgs::msg::Twist_ConvertToDdsType(src.twist);
    dst.covariance() = oss::type::double_36_ConvertToDdsType(src.covariance);
    return dst;
}
 
inline oss::type::geometry_msgs::msg::TwistWithCovariance TwistWithCovariance_ConvertFromDdsType(const dds::oss::type::geometry_msgs::msg::TwistWithCovariance& src)
{
    oss::type::geometry_msgs::msg::TwistWithCovariance dst;
    dst.twist = oss::type::geometry_msgs::msg::Twist_ConvertFromDdsType(src.twist());
    dst.covariance = oss::type::double_36_ConvertFromDdsType(src.covariance());
    return dst;
}
#endif /// PARA_DDS_IMPLEMENTATION
} /// namespace msg
} /// namespace geometry_msgs
} /// namespace type
} /// namespace oss
#endif /// PARA_ARA_COM_GEN_OSS_TYPE_GEOMETRY_MSGS_MSG_CPP_IMPL_TYPE_TWISTWITHCOVARIANCE_H