///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, ARA::COM Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : impl_type_controlpoint.h
/// IMPLEMENTATION DATA TYPE NAME     : ControlPoint
/// GENERATED DATE                    : 2025-12-05 12:02:24
///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// CAUTION!! AUTOMATICALLY GENERATED FILE - DO NOT EDIT                                                   
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_ARA_COM_GEN_OSS_TYPE_TIER4_PLANNING_MSGS_MSG_CPP_IMPL_TYPE_CONTROLPOINT_H
#define PARA_ARA_COM_GEN_OSS_TYPE_TIER4_PLANNING_MSGS_MSG_CPP_IMPL_TYPE_CONTROLPOINT_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// @uptrace{SWS_CM_00402}
#include <ara/core/structure.h>

#include "oss/type/geometry_msgs/msg/impl_type_pose.h"
#ifdef PARA_DDS_IMPLEMENTATION
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION FOR DDS
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "impl_type_controlpoint.hpp"
#endif /// PARA_DDS_IMPLEMENTATION
/// @uptrace{SWS_CM_10375}
namespace oss
{
namespace type
{
namespace tier4_planning_msgs
{
namespace msg
{
struct ControlPoint
{
    oss::type::geometry_msgs::msg::Pose pose;
    float velocity;
    float shift_length;
    float distance;

    /// @brief constructor
    ControlPoint() = default;
    ControlPoint(const oss::type::geometry_msgs::msg::Pose& _pose, const float& _velocity, const float& _shift_length, const float& _distance)
        : pose{_pose}
        , velocity{_velocity}
        , shift_length{_shift_length}
        , distance{_distance}
    {
    }

    /// @note marker for serialize, don't touch
    PARA_STRUCTURE(ControlPoint, pose, velocity, shift_length, distance);
};
 
#ifdef PARA_DDS_IMPLEMENTATION
inline dds::oss::type::tier4_planning_msgs::msg::ControlPoint ControlPoint_ConvertToDdsType(const oss::type::tier4_planning_msgs::msg::ControlPoint& src)
{
    dds::oss::type::tier4_planning_msgs::msg::ControlPoint dst;
    dst.pose() = oss::type::geometry_msgs::msg::Pose_ConvertToDdsType(src.pose);
    dst.velocity() = src.velocity;
    dst.shift_length() = src.shift_length;
    dst.distance() = src.distance;
    return dst;
}
 
inline oss::type::tier4_planning_msgs::msg::ControlPoint ControlPoint_ConvertFromDdsType(const dds::oss::type::tier4_planning_msgs::msg::ControlPoint& src)
{
    oss::type::tier4_planning_msgs::msg::ControlPoint dst;
    dst.pose = oss::type::geometry_msgs::msg::Pose_ConvertFromDdsType(src.pose());
    dst.velocity = src.velocity();
    dst.shift_length = src.shift_length();
    dst.distance = src.distance();
    return dst;
}
#endif /// PARA_DDS_IMPLEMENTATION
} /// namespace msg
} /// namespace tier4_planning_msgs
} /// namespace type
} /// namespace oss
#endif /// PARA_ARA_COM_GEN_OSS_TYPE_TIER4_PLANNING_MSGS_MSG_CPP_IMPL_TYPE_CONTROLPOINT_H