///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, ARA::COM Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : impl_type_pointcloud2.h
/// IMPLEMENTATION DATA TYPE NAME     : PointCloud2
/// GENERATED DATE                    : 2025-12-05 12:02:31
///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// CAUTION!! AUTOMATICALLY GENERATED FILE - DO NOT EDIT                                                   
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_ARA_COM_GEN_OSS_TYPE_SENSOR_MSGS_MSG_CPP_IMPL_TYPE_POINTCLOUD2_H
#define PARA_ARA_COM_GEN_OSS_TYPE_SENSOR_MSGS_MSG_CPP_IMPL_TYPE_POINTCLOUD2_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// @uptrace{SWS_CM_00402}
#include <cstdint>
#include <ara/core/structure.h>

#include "oss/type/impl_type_pointfield_vector.h"
#include "oss/type/impl_type_uint8_vector.h"
#include "oss/type/std_msgs/msg/impl_type_header.h"
#ifdef PARA_DDS_IMPLEMENTATION
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION FOR DDS
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "impl_type_pointcloud2.hpp"
#endif /// PARA_DDS_IMPLEMENTATION
/// @uptrace{SWS_CM_10375}
namespace oss
{
namespace type
{
namespace sensor_msgs
{
namespace msg
{
struct PointCloud2
{
    oss::type::std_msgs::msg::Header header;
    std::uint32_t height;
    std::uint32_t width;
    oss::type::PointField_Vector fields;
    bool is_bigendian;
    std::uint32_t point_step;
    std::uint32_t row_step;
    oss::type::uint8_Vector data;
    bool is_dense;

    /// @brief constructor
    PointCloud2() = default;
    PointCloud2(const oss::type::std_msgs::msg::Header& _header, const std::uint32_t& _height, const std::uint32_t& _width, const oss::type::PointField_Vector& _fields, const bool& _is_bigendian, const std::uint32_t& _point_step, const std::uint32_t& _row_step, const oss::type::uint8_Vector& _data, const bool& _is_dense)
        : header{_header}
        , height{_height}
        , width{_width}
        , fields{_fields}
        , is_bigendian{_is_bigendian}
        , point_step{_point_step}
        , row_step{_row_step}
        , data{_data}
        , is_dense{_is_dense}
    {
    }

    /// @note marker for serialize, don't touch
    PARA_STRUCTURE(PointCloud2, header, height, width, fields, is_bigendian, point_step, row_step, data, is_dense);
};
 
#ifdef PARA_DDS_IMPLEMENTATION
inline dds::oss::type::sensor_msgs::msg::PointCloud2 PointCloud2_ConvertToDdsType(const oss::type::sensor_msgs::msg::PointCloud2& src)
{
    dds::oss::type::sensor_msgs::msg::PointCloud2 dst;
    dst.header() = oss::type::std_msgs::msg::Header_ConvertToDdsType(src.header);
    dst.height() = src.height;
    dst.width() = src.width;
    dst.fields() = oss::type::PointField_Vector_ConvertToDdsType(src.fields);
    dst.is_bigendian() = src.is_bigendian;
    dst.point_step() = src.point_step;
    dst.row_step() = src.row_step;
    dst.data() = oss::type::uint8_Vector_ConvertToDdsType(src.data);
    dst.is_dense() = src.is_dense;
    return dst;
}
 
inline oss::type::sensor_msgs::msg::PointCloud2 PointCloud2_ConvertFromDdsType(const dds::oss::type::sensor_msgs::msg::PointCloud2& src)
{
    oss::type::sensor_msgs::msg::PointCloud2 dst;
    dst.header = oss::type::std_msgs::msg::Header_ConvertFromDdsType(src.header());
    dst.height = src.height();
    dst.width = src.width();
    dst.fields = oss::type::PointField_Vector_ConvertFromDdsType(src.fields());
    dst.is_bigendian = src.is_bigendian();
    dst.point_step = src.point_step();
    dst.row_step = src.row_step();
    dst.data = oss::type::uint8_Vector_ConvertFromDdsType(src.data());
    dst.is_dense = src.is_dense();
    return dst;
}
#endif /// PARA_DDS_IMPLEMENTATION
} /// namespace msg
} /// namespace sensor_msgs
} /// namespace type
} /// namespace oss
#endif /// PARA_ARA_COM_GEN_OSS_TYPE_SENSOR_MSGS_MSG_CPP_IMPL_TYPE_POINTCLOUD2_H