///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, ARA::COM Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : impl_type_stringstamped.h
/// IMPLEMENTATION DATA TYPE NAME     : StringStamped
/// GENERATED DATE                    : 2025-12-08 15:30:05
///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// CAUTION!! AUTOMATICALLY GENERATED FILE - DO NOT EDIT                                                   
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_ARA_COM_GEN_OSS_TYPE_AUTOWARE_INTERNAL_DEBUG_MSGS_MSG_CPP_IMPL_TYPE_STRINGSTAMPED_H
#define PARA_ARA_COM_GEN_OSS_TYPE_AUTOWARE_INTERNAL_DEBUG_MSGS_MSG_CPP_IMPL_TYPE_STRINGSTAMPED_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// @uptrace{SWS_CM_00402}
#include <ara/core/structure.h>
#include "oss/type/builtin_interfaces/msg/impl_type_time.h"
#include "oss/type/impl_type_string.h"
#ifdef PARA_DDS_IMPLEMENTATION
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION FOR DDS
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "impl_type_stringstamped.hpp"
#endif /// PARA_DDS_IMPLEMENTATION
/// @uptrace{SWS_CM_10375}
namespace oss
{
namespace type
{
namespace autoware_internal_debug_msgs
{
namespace msg
{
struct StringStamped
{
    oss::type::builtin_interfaces::msg::Time stamp;
    oss::type::string data;

    /// @brief constructor
    StringStamped() = default;
    StringStamped(const oss::type::builtin_interfaces::msg::Time& _stamp, const oss::type::string& _data)
        : stamp{_stamp}
        , data{_data}
    {
    }

    /// @note marker for serialize, don't touch
    PARA_STRUCTURE(StringStamped, stamp, data);
};
 
#ifdef PARA_DDS_IMPLEMENTATION
inline dds::oss::type::autoware_internal_debug_msgs::msg::StringStamped StringStamped_ConvertToDdsType(const oss::type::autoware_internal_debug_msgs::msg::StringStamped& src)
{
    dds::oss::type::autoware_internal_debug_msgs::msg::StringStamped dst;
    dst.stamp() = oss::type::builtin_interfaces::msg::Time_ConvertToDdsType(src.stamp);
    dst.data() = oss::type::string_ConvertToDdsType(src.data);
    return dst;
}
 
inline oss::type::autoware_internal_debug_msgs::msg::StringStamped StringStamped_ConvertFromDdsType(const dds::oss::type::autoware_internal_debug_msgs::msg::StringStamped& src)
{
    oss::type::autoware_internal_debug_msgs::msg::StringStamped dst;
    dst.stamp = oss::type::builtin_interfaces::msg::Time_ConvertFromDdsType(src.stamp());
    dst.data = oss::type::string_ConvertFromDdsType(src.data());
    return dst;
}
#endif /// PARA_DDS_IMPLEMENTATION
} /// namespace msg
} /// namespace autoware_internal_debug_msgs
} /// namespace type
} /// namespace oss
#endif /// PARA_ARA_COM_GEN_OSS_TYPE_AUTOWARE_INTERNAL_DEBUG_MSGS_MSG_CPP_IMPL_TYPE_STRINGSTAMPED_H