///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, ARA::COM Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : impl_type_odometry.h
/// IMPLEMENTATION DATA TYPE NAME     : Odometry
/// GENERATED DATE                    : 2025-12-02 18:57:09
///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// CAUTION!! AUTOMATICALLY GENERATED FILE - DO NOT EDIT                                                   
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_ARA_COM_GEN_OSS_TYPE_NAV_MSGS_MSG_CPP_IMPL_TYPE_ODOMETRY_H
#define PARA_ARA_COM_GEN_OSS_TYPE_NAV_MSGS_MSG_CPP_IMPL_TYPE_ODOMETRY_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// @uptrace{SWS_CM_00402}
#include <ara/core/structure.h>
#include "oss/type/geometry_msgs/msg/impl_type_posewithcovariance.h"
#include "oss/type/geometry_msgs/msg/impl_type_twistwithcovariance.h"
#include "oss/type/impl_type_string.h"
#include "oss/type/std_msgs/msg/impl_type_header.h"
#ifdef PARA_DDS_IMPLEMENTATION
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION FOR DDS
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "impl_type_odometry.hpp"
#endif /// PARA_DDS_IMPLEMENTATION
/// @uptrace{SWS_CM_10375}
namespace oss
{
namespace type
{
namespace nav_msgs
{
namespace msg
{
struct Odometry
{
    oss::type::std_msgs::msg::Header header;
    oss::type::string child_frame_id;
    oss::type::geometry_msgs::msg::PoseWithCovariance pose;
    oss::type::geometry_msgs::msg::TwistWithCovariance twist;

    /// @brief constructor
    Odometry() = default;
    Odometry(const oss::type::std_msgs::msg::Header& _header, const oss::type::string& _child_frame_id, const oss::type::geometry_msgs::msg::PoseWithCovariance& _pose, const oss::type::geometry_msgs::msg::TwistWithCovariance& _twist)
        : header{_header}
        , child_frame_id{_child_frame_id}
        , pose{_pose}
        , twist{_twist}
    {
    }

    /// @note marker for serialize, don't touch
    PARA_STRUCTURE(Odometry, header, child_frame_id, pose, twist);
};
 
#ifdef PARA_DDS_IMPLEMENTATION
inline dds::oss::type::nav_msgs::msg::Odometry Odometry_ConvertToDdsType(const oss::type::nav_msgs::msg::Odometry& src)
{
    dds::oss::type::nav_msgs::msg::Odometry dst;
    dst.header() = oss::type::std_msgs::msg::Header_ConvertToDdsType(src.header);
    dst.child_frame_id() = oss::type::string_ConvertToDdsType(src.child_frame_id);
    dst.pose() = oss::type::geometry_msgs::msg::PoseWithCovariance_ConvertToDdsType(src.pose);
    dst.twist() = oss::type::geometry_msgs::msg::TwistWithCovariance_ConvertToDdsType(src.twist);
    return dst;
}
 
inline oss::type::nav_msgs::msg::Odometry Odometry_ConvertFromDdsType(const dds::oss::type::nav_msgs::msg::Odometry& src)
{
    oss::type::nav_msgs::msg::Odometry dst;
    dst.header = oss::type::std_msgs::msg::Header_ConvertFromDdsType(src.header());
    dst.child_frame_id = oss::type::string_ConvertFromDdsType(src.child_frame_id());
    dst.pose = oss::type::geometry_msgs::msg::PoseWithCovariance_ConvertFromDdsType(src.pose());
    dst.twist = oss::type::geometry_msgs::msg::TwistWithCovariance_ConvertFromDdsType(src.twist());
    return dst;
}
#endif /// PARA_DDS_IMPLEMENTATION
} /// namespace msg
} /// namespace nav_msgs
} /// namespace type
} /// namespace oss
#endif /// PARA_ARA_COM_GEN_OSS_TYPE_NAV_MSGS_MSG_CPP_IMPL_TYPE_ODOMETRY_H