///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, ARA::COM Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : impl_type_lateraloffset.h
/// IMPLEMENTATION DATA TYPE NAME     : LateralOffset
/// GENERATED DATE                    : 2025-12-02 18:57:08
///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// CAUTION!! AUTOMATICALLY GENERATED FILE - DO NOT EDIT                                                   
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_ARA_COM_GEN_OSS_TYPE_TIER4_PLANNING_MSGS_MSG_CPP_IMPL_TYPE_LATERALOFFSET_H
#define PARA_ARA_COM_GEN_OSS_TYPE_TIER4_PLANNING_MSGS_MSG_CPP_IMPL_TYPE_LATERALOFFSET_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// @uptrace{SWS_CM_00402}
#include <ara/core/structure.h>

#include "oss/type/builtin_interfaces/msg/impl_type_time.h"
#ifdef PARA_DDS_IMPLEMENTATION
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION FOR DDS
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "impl_type_lateraloffset.hpp"
#endif /// PARA_DDS_IMPLEMENTATION
/// @uptrace{SWS_CM_10375}
namespace oss
{
namespace type
{
namespace tier4_planning_msgs
{
namespace msg
{
struct LateralOffset
{
    oss::type::builtin_interfaces::msg::Time stamp;
    float lateral_offset;

    /// @brief constructor
    LateralOffset() = default;
    LateralOffset(const oss::type::builtin_interfaces::msg::Time& _stamp, const float& _lateral_offset)
        : stamp{_stamp}
        , lateral_offset{_lateral_offset}
    {
    }

    /// @note marker for serialize, don't touch
    PARA_STRUCTURE(LateralOffset, stamp, lateral_offset);
};
 
#ifdef PARA_DDS_IMPLEMENTATION
inline dds::oss::type::tier4_planning_msgs::msg::LateralOffset LateralOffset_ConvertToDdsType(const oss::type::tier4_planning_msgs::msg::LateralOffset& src)
{
    dds::oss::type::tier4_planning_msgs::msg::LateralOffset dst;
    dst.stamp() = oss::type::builtin_interfaces::msg::Time_ConvertToDdsType(src.stamp);
    dst.lateral_offset() = src.lateral_offset;
    return dst;
}
 
inline oss::type::tier4_planning_msgs::msg::LateralOffset LateralOffset_ConvertFromDdsType(const dds::oss::type::tier4_planning_msgs::msg::LateralOffset& src)
{
    oss::type::tier4_planning_msgs::msg::LateralOffset dst;
    dst.stamp = oss::type::builtin_interfaces::msg::Time_ConvertFromDdsType(src.stamp());
    dst.lateral_offset = src.lateral_offset();
    return dst;
}
#endif /// PARA_DDS_IMPLEMENTATION
} /// namespace msg
} /// namespace tier4_planning_msgs
} /// namespace type
} /// namespace oss
#endif /// PARA_ARA_COM_GEN_OSS_TYPE_TIER4_PLANNING_MSGS_MSG_CPP_IMPL_TYPE_LATERALOFFSET_H