///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, ARA::COM Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : impl_type_parameterdescriptor.h
/// IMPLEMENTATION DATA TYPE NAME     : ParameterDescriptor
/// GENERATED DATE                    : 2025-12-12 16:17:51
///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// CAUTION!! AUTOMATICALLY GENERATED FILE - DO NOT EDIT                                                   
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_ARA_COM_GEN_OSS_TYPE_RCL_INTERFACES_MSG_CPP_IMPL_TYPE_PARAMETERDESCRIPTOR_H
#define PARA_ARA_COM_GEN_OSS_TYPE_RCL_INTERFACES_MSG_CPP_IMPL_TYPE_PARAMETERDESCRIPTOR_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// @uptrace{SWS_CM_00402}
#include <cstdint>
#include <ara/core/structure.h>

#include "oss/type/impl_type_floatingpointrange_vector.h"
#include "oss/type/impl_type_integerrange_vector.h"
#include "oss/type/impl_type_string.h"
#ifdef PARA_DDS_IMPLEMENTATION
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION FOR DDS
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "impl_type_parameterdescriptor.hpp"
#endif /// PARA_DDS_IMPLEMENTATION
/// @uptrace{SWS_CM_10375}
namespace oss
{
namespace type
{
namespace rcl_interfaces
{
namespace msg
{
struct ParameterDescriptor
{
    oss::type::string name;
    std::uint8_t type;
    oss::type::string description;
    oss::type::string additional_constraints;
    bool read_only;
    bool dynamic_typing;
    oss::type::FloatingPointRange_Vector floating_point_range;
    oss::type::IntegerRange_Vector integer_range;

    /// @brief constructor
    ParameterDescriptor() = default;
    ParameterDescriptor(const oss::type::string& _name, const std::uint8_t& _type, const oss::type::string& _description, const oss::type::string& _additional_constraints, const bool& _read_only, const bool& _dynamic_typing, const oss::type::FloatingPointRange_Vector& _floating_point_range, const oss::type::IntegerRange_Vector& _integer_range)
        : name{_name}
        , type{_type}
        , description{_description}
        , additional_constraints{_additional_constraints}
        , read_only{_read_only}
        , dynamic_typing{_dynamic_typing}
        , floating_point_range{_floating_point_range}
        , integer_range{_integer_range}
    {
    }

    /// @note marker for serialize, don't touch
    PARA_STRUCTURE(ParameterDescriptor, name, type, description, additional_constraints, read_only, dynamic_typing, floating_point_range, integer_range);
};
 
#ifdef PARA_DDS_IMPLEMENTATION
inline dds::oss::type::rcl_interfaces::msg::ParameterDescriptor ParameterDescriptor_ConvertToDdsType(const oss::type::rcl_interfaces::msg::ParameterDescriptor& src)
{
    dds::oss::type::rcl_interfaces::msg::ParameterDescriptor dst;
    dst.name() = oss::type::string_ConvertToDdsType(src.name);
    dst.type() = src.type;
    dst.description() = oss::type::string_ConvertToDdsType(src.description);
    dst.additional_constraints() = oss::type::string_ConvertToDdsType(src.additional_constraints);
    dst.read_only() = src.read_only;
    dst.dynamic_typing() = src.dynamic_typing;
    dst.floating_point_range() = oss::type::FloatingPointRange_Vector_ConvertToDdsType(src.floating_point_range);
    dst.integer_range() = oss::type::IntegerRange_Vector_ConvertToDdsType(src.integer_range);
    return dst;
}
 
inline oss::type::rcl_interfaces::msg::ParameterDescriptor ParameterDescriptor_ConvertFromDdsType(const dds::oss::type::rcl_interfaces::msg::ParameterDescriptor& src)
{
    oss::type::rcl_interfaces::msg::ParameterDescriptor dst;
    dst.name = oss::type::string_ConvertFromDdsType(src.name());
    dst.type = src.type();
    dst.description = oss::type::string_ConvertFromDdsType(src.description());
    dst.additional_constraints = oss::type::string_ConvertFromDdsType(src.additional_constraints());
    dst.read_only = src.read_only();
    dst.dynamic_typing = src.dynamic_typing();
    dst.floating_point_range = oss::type::FloatingPointRange_Vector_ConvertFromDdsType(src.floating_point_range());
    dst.integer_range = oss::type::IntegerRange_Vector_ConvertFromDdsType(src.integer_range());
    return dst;
}
#endif /// PARA_DDS_IMPLEMENTATION
} /// namespace msg
} /// namespace rcl_interfaces
} /// namespace type
} /// namespace oss
#endif /// PARA_ARA_COM_GEN_OSS_TYPE_RCL_INTERFACES_MSG_CPP_IMPL_TYPE_PARAMETERDESCRIPTOR_H