///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, ARA::COM Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : impl_type_pointfield_vector.h
/// IMPLEMENTATION DATA TYPE NAME     : PointField_Vector
/// GENERATED DATE                    : 2025-12-12 16:17:52
///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// CAUTION!! AUTOMATICALLY GENERATED FILE - DO NOT EDIT                                                   
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_ARA_COM_GEN_OSS_TYPE_CPP_IMPL_TYPE_POINTFIELD_VECTOR_H
#define PARA_ARA_COM_GEN_OSS_TYPE_CPP_IMPL_TYPE_POINTFIELD_VECTOR_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// @uptrace{SWS_CM_00402}
#include <ara/core/vector.h>
#include "oss/type/sensor_msgs/msg/impl_type_pointfield.h"
#ifdef PARA_DDS_IMPLEMENTATION
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION FOR DDS
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "impl_type_pointfield_vector.hpp"
#endif /// PARA_DDS_IMPLEMENTATION
/// @uptrace{SWS_CM_10375}
namespace oss
{
namespace type
{
using PointField_Vector = ara::core::Vector<oss::type::sensor_msgs::msg::PointField>;
 
#ifdef PARA_DDS_IMPLEMENTATION
inline dds::oss::type::PointField_Vector PointField_Vector_ConvertToDdsType(const oss::type::PointField_Vector& src)
{
    dds::oss::type::PointField_Vector dst{};
    std::transform(src.begin(), src.end(), std::back_inserter(dst), [](const auto& element) {
        return oss::type::sensor_msgs::msg::PointField_ConvertToDdsType(element);
    });
    return dst;
}
 
inline oss::type::PointField_Vector PointField_Vector_ConvertFromDdsType(const dds::oss::type::PointField_Vector& src)
{
    oss::type::PointField_Vector dst{};
    std::transform(src.begin(), src.end(), std::back_inserter(dst), [](const auto& element) {
        return oss::type::sensor_msgs::msg::PointField_ConvertFromDdsType(element);
    });
    return dst;
}
#endif /// PARA_DDS_IMPLEMENTATION
} /// namespace type
} /// namespace oss
#endif /// PARA_ARA_COM_GEN_OSS_TYPE_CPP_IMPL_TYPE_POINTFIELD_VECTOR_H