///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, ARA::COM Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : impl_type_listparameters_request.h
/// IMPLEMENTATION DATA TYPE NAME     : ListParameters_Request
/// GENERATED DATE                    : 2025-12-05 12:02:24
///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// CAUTION!! AUTOMATICALLY GENERATED FILE - DO NOT EDIT                                                   
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_ARA_COM_GEN_OSS_TYPE_RCL_INTERFACES_SRV_CPP_IMPL_TYPE_LISTPARAMETERS_REQUEST_H
#define PARA_ARA_COM_GEN_OSS_TYPE_RCL_INTERFACES_SRV_CPP_IMPL_TYPE_LISTPARAMETERS_REQUEST_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// @uptrace{SWS_CM_00402}
#include <cstdint>
#include <ara/core/structure.h>
#include "oss/type/impl_type_string_vector.h"
#ifdef PARA_DDS_IMPLEMENTATION
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION FOR DDS
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "impl_type_listparameters_request.hpp"
#endif /// PARA_DDS_IMPLEMENTATION
/// @uptrace{SWS_CM_10375}
namespace oss
{
namespace type
{
namespace rcl_interfaces
{
namespace srv
{
struct ListParameters_Request
{
    std::uint64_t DEPTH_RECURSIVE;
    oss::type::string_Vector prefixes;
    std::uint64_t depth;

    /// @brief constructor
    ListParameters_Request() = default;
    ListParameters_Request(const std::uint64_t& _DEPTH_RECURSIVE, const oss::type::string_Vector& _prefixes, const std::uint64_t& _depth)
        : DEPTH_RECURSIVE{_DEPTH_RECURSIVE}
        , prefixes{_prefixes}
        , depth{_depth}
    {
    }

    /// @note marker for serialize, don't touch
    PARA_STRUCTURE(ListParameters_Request, DEPTH_RECURSIVE, prefixes, depth);
};
 
#ifdef PARA_DDS_IMPLEMENTATION
inline dds::oss::type::rcl_interfaces::srv::ListParameters_Request ListParameters_Request_ConvertToDdsType(const oss::type::rcl_interfaces::srv::ListParameters_Request& src)
{
    dds::oss::type::rcl_interfaces::srv::ListParameters_Request dst;
    dst.DEPTH_RECURSIVE() = src.DEPTH_RECURSIVE;
    dst.prefixes() = oss::type::string_Vector_ConvertToDdsType(src.prefixes);
    dst.depth() = src.depth;
    return dst;
}
 
inline oss::type::rcl_interfaces::srv::ListParameters_Request ListParameters_Request_ConvertFromDdsType(const dds::oss::type::rcl_interfaces::srv::ListParameters_Request& src)
{
    oss::type::rcl_interfaces::srv::ListParameters_Request dst;
    dst.DEPTH_RECURSIVE = src.DEPTH_RECURSIVE();
    dst.prefixes = oss::type::string_Vector_ConvertFromDdsType(src.prefixes());
    dst.depth = src.depth();
    return dst;
}
#endif /// PARA_DDS_IMPLEMENTATION
} /// namespace srv
} /// namespace rcl_interfaces
} /// namespace type
} /// namespace oss
#endif /// PARA_ARA_COM_GEN_OSS_TYPE_RCL_INTERFACES_SRV_CPP_IMPL_TYPE_LISTPARAMETERS_REQUEST_H