///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, ARA::COM Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : impl_type_gridmapinfo.h
/// IMPLEMENTATION DATA TYPE NAME     : GridMapInfo
/// GENERATED DATE                    : 2025-12-08 15:30:06
///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// CAUTION!! AUTOMATICALLY GENERATED FILE - DO NOT EDIT                                                   
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_ARA_COM_GEN_OSS_TYPE_GRID_MAP_MSGS_MSG_CPP_IMPL_TYPE_GRIDMAPINFO_H
#define PARA_ARA_COM_GEN_OSS_TYPE_GRID_MAP_MSGS_MSG_CPP_IMPL_TYPE_GRIDMAPINFO_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// @uptrace{SWS_CM_00402}
#include <ara/core/structure.h>

#include "oss/type/geometry_msgs/msg/impl_type_pose.h"
#ifdef PARA_DDS_IMPLEMENTATION
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION FOR DDS
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "impl_type_gridmapinfo.hpp"
#endif /// PARA_DDS_IMPLEMENTATION
/// @uptrace{SWS_CM_10375}
namespace oss
{
namespace type
{
namespace grid_map_msgs
{
namespace msg
{
struct GridMapInfo
{
    double resolution;
    double length_x;
    double length_y;
    oss::type::geometry_msgs::msg::Pose pose;

    /// @brief constructor
    GridMapInfo() = default;
    GridMapInfo(const double& _resolution, const double& _length_x, const double& _length_y, const oss::type::geometry_msgs::msg::Pose& _pose)
        : resolution{_resolution}
        , length_x{_length_x}
        , length_y{_length_y}
        , pose{_pose}
    {
    }

    /// @note marker for serialize, don't touch
    PARA_STRUCTURE(GridMapInfo, resolution, length_x, length_y, pose);
};
 
#ifdef PARA_DDS_IMPLEMENTATION
inline dds::oss::type::grid_map_msgs::msg::GridMapInfo GridMapInfo_ConvertToDdsType(const oss::type::grid_map_msgs::msg::GridMapInfo& src)
{
    dds::oss::type::grid_map_msgs::msg::GridMapInfo dst;
    dst.resolution() = src.resolution;
    dst.length_x() = src.length_x;
    dst.length_y() = src.length_y;
    dst.pose() = oss::type::geometry_msgs::msg::Pose_ConvertToDdsType(src.pose);
    return dst;
}
 
inline oss::type::grid_map_msgs::msg::GridMapInfo GridMapInfo_ConvertFromDdsType(const dds::oss::type::grid_map_msgs::msg::GridMapInfo& src)
{
    oss::type::grid_map_msgs::msg::GridMapInfo dst;
    dst.resolution = src.resolution();
    dst.length_x = src.length_x();
    dst.length_y = src.length_y();
    dst.pose = oss::type::geometry_msgs::msg::Pose_ConvertFromDdsType(src.pose());
    return dst;
}
#endif /// PARA_DDS_IMPLEMENTATION
} /// namespace msg
} /// namespace grid_map_msgs
} /// namespace type
} /// namespace oss
#endif /// PARA_ARA_COM_GEN_OSS_TYPE_GRID_MAP_MSGS_MSG_CPP_IMPL_TYPE_GRIDMAPINFO_H