///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, ARA::COM Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : impl_type_pose.h
/// IMPLEMENTATION DATA TYPE NAME     : Pose
/// GENERATED DATE                    : 2025-12-05 12:02:31
///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// CAUTION!! AUTOMATICALLY GENERATED FILE - DO NOT EDIT                                                   
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_ARA_COM_GEN_OSS_TYPE_GEOMETRY_MSGS_MSG_CPP_IMPL_TYPE_POSE_H
#define PARA_ARA_COM_GEN_OSS_TYPE_GEOMETRY_MSGS_MSG_CPP_IMPL_TYPE_POSE_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// @uptrace{SWS_CM_00402}
#include <ara/core/structure.h>
#include "oss/type/geometry_msgs/msg/impl_type_point.h"
#include "oss/type/geometry_msgs/msg/impl_type_quaternion.h"
#ifdef PARA_DDS_IMPLEMENTATION
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION FOR DDS
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "impl_type_pose.hpp"
#endif /// PARA_DDS_IMPLEMENTATION
/// @uptrace{SWS_CM_10375}
namespace oss
{
namespace type
{
namespace geometry_msgs
{
namespace msg
{
struct Pose
{
    oss::type::geometry_msgs::msg::Point position;
    oss::type::geometry_msgs::msg::Quaternion orientation;

    /// @brief constructor
    Pose() = default;
    Pose(const oss::type::geometry_msgs::msg::Point& _position, const oss::type::geometry_msgs::msg::Quaternion& _orientation)
        : position{_position}
        , orientation{_orientation}
    {
    }

    /// @note marker for serialize, don't touch
    PARA_STRUCTURE(Pose, position, orientation);
};
 
#ifdef PARA_DDS_IMPLEMENTATION
inline dds::oss::type::geometry_msgs::msg::Pose Pose_ConvertToDdsType(const oss::type::geometry_msgs::msg::Pose& src)
{
    dds::oss::type::geometry_msgs::msg::Pose dst;
    dst.position() = oss::type::geometry_msgs::msg::Point_ConvertToDdsType(src.position);
    dst.orientation() = oss::type::geometry_msgs::msg::Quaternion_ConvertToDdsType(src.orientation);
    return dst;
}
 
inline oss::type::geometry_msgs::msg::Pose Pose_ConvertFromDdsType(const dds::oss::type::geometry_msgs::msg::Pose& src)
{
    oss::type::geometry_msgs::msg::Pose dst;
    dst.position = oss::type::geometry_msgs::msg::Point_ConvertFromDdsType(src.position());
    dst.orientation = oss::type::geometry_msgs::msg::Quaternion_ConvertFromDdsType(src.orientation());
    return dst;
}
#endif /// PARA_DDS_IMPLEMENTATION
} /// namespace msg
} /// namespace geometry_msgs
} /// namespace type
} /// namespace oss
#endif /// PARA_ARA_COM_GEN_OSS_TYPE_GEOMETRY_MSGS_MSG_CPP_IMPL_TYPE_POSE_H