///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, ARA::COM Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : impl_type_laneletprimitive.h
/// IMPLEMENTATION DATA TYPE NAME     : LaneletPrimitive
/// GENERATED DATE                    : 2025-12-02 18:57:09
///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// CAUTION!! AUTOMATICALLY GENERATED FILE - DO NOT EDIT                                                   
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_ARA_COM_GEN_OSS_TYPE_AUTOWARE_PLANNING_MSGS_MSG_CPP_IMPL_TYPE_LANELETPRIMITIVE_H
#define PARA_ARA_COM_GEN_OSS_TYPE_AUTOWARE_PLANNING_MSGS_MSG_CPP_IMPL_TYPE_LANELETPRIMITIVE_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// @uptrace{SWS_CM_00402}
#include <cstdint>
#include <ara/core/structure.h>
#include "oss/type/impl_type_string.h"
#ifdef PARA_DDS_IMPLEMENTATION
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION FOR DDS
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "impl_type_laneletprimitive.hpp"
#endif /// PARA_DDS_IMPLEMENTATION
/// @uptrace{SWS_CM_10375}
namespace oss
{
namespace type
{
namespace autoware_planning_msgs
{
namespace msg
{
struct LaneletPrimitive
{
    std::int64_t id;
    oss::type::string primitive_type;

    /// @brief constructor
    LaneletPrimitive() = default;
    LaneletPrimitive(const std::int64_t& _id, const oss::type::string& _primitive_type)
        : id{_id}
        , primitive_type{_primitive_type}
    {
    }

    /// @note marker for serialize, don't touch
    PARA_STRUCTURE(LaneletPrimitive, id, primitive_type);
};
 
#ifdef PARA_DDS_IMPLEMENTATION
inline dds::oss::type::autoware_planning_msgs::msg::LaneletPrimitive LaneletPrimitive_ConvertToDdsType(const oss::type::autoware_planning_msgs::msg::LaneletPrimitive& src)
{
    dds::oss::type::autoware_planning_msgs::msg::LaneletPrimitive dst;
    dst.id() = src.id;
    dst.primitive_type() = oss::type::string_ConvertToDdsType(src.primitive_type);
    return dst;
}
 
inline oss::type::autoware_planning_msgs::msg::LaneletPrimitive LaneletPrimitive_ConvertFromDdsType(const dds::oss::type::autoware_planning_msgs::msg::LaneletPrimitive& src)
{
    oss::type::autoware_planning_msgs::msg::LaneletPrimitive dst;
    dst.id = src.id();
    dst.primitive_type = oss::type::string_ConvertFromDdsType(src.primitive_type());
    return dst;
}
#endif /// PARA_DDS_IMPLEMENTATION
} /// namespace msg
} /// namespace autoware_planning_msgs
} /// namespace type
} /// namespace oss
#endif /// PARA_ARA_COM_GEN_OSS_TYPE_AUTOWARE_PLANNING_MSGS_MSG_CPP_IMPL_TYPE_LANELETPRIMITIVE_H