///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : pport_ebs2po.cpp
/// SOFTWARE COMPONENT NAME           : PPort_EBS2PO
/// GENERATED DATE                    : 2025-12-05 12:02:34
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "exe_elasticbandsmoother/aa/port/pport_ebs2po.h"
 
namespace oss
{
namespace srv
{
namespace EBS2PO
{
namespace skeleton
{
 
PO_SI_elasticbandsmootherSkeletonImpl::PO_SI_elasticbandsmootherSkeletonImpl(ara::core::InstanceSpecifier instanceSpec, ara::com::MethodCallProcessingMode mode)
    : PO_SI_elasticbandsmootherSkeleton(instanceSpec, mode)
    , m_logger(ara::log::CreateLogger("EBST", "PORT", ara::log::LogLevel::kVerbose))
{
}
 
ara::core::Future<PO_SI_elasticbandsmootherSkeleton::planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_configloggerOutput> PO_SI_elasticbandsmootherSkeletonImpl::planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_configlogger(const oss::type::logging_demo::srv::ConfigLogger_Request& req)
{
    m_logger.LogVerbose() << "PPort_EBS2PO::planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_configlogger::Requested";
    
    planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_configloggerOutput response;
    ara::core::Promise<planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_configloggerOutput> promise;
    
    // put your logic
    
    promise.set_value(response);
    return promise.get_future();
}
 
ara::core::Future<PO_SI_elasticbandsmootherSkeleton::planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_describeparametersOutput> PO_SI_elasticbandsmootherSkeletonImpl::planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_describeparameters(const oss::type::rcl_interfaces::srv::DescribeParameters_Request& req)
{
    m_logger.LogVerbose() << "PPort_EBS2PO::planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_describeparameters::Requested";
    
    planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_describeparametersOutput response;
    ara::core::Promise<planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_describeparametersOutput> promise;
    
    // put your logic
    
    promise.set_value(response);
    return promise.get_future();
}
 
ara::core::Future<PO_SI_elasticbandsmootherSkeleton::planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_getparametersOutput> PO_SI_elasticbandsmootherSkeletonImpl::planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_getparameters(const oss::type::rcl_interfaces::srv::GetParameters_Request& req)
{
    m_logger.LogVerbose() << "PPort_EBS2PO::planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_getparameters::Requested";
    
    planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_getparametersOutput response;
    ara::core::Promise<planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_getparametersOutput> promise;
    
    // put your logic
    
    promise.set_value(response);
    return promise.get_future();
}
 
ara::core::Future<PO_SI_elasticbandsmootherSkeleton::planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_getparametertypesOutput> PO_SI_elasticbandsmootherSkeletonImpl::planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_getparametertypes(const oss::type::rcl_interfaces::srv::GetParameterTypes_Request& req)
{
    m_logger.LogVerbose() << "PPort_EBS2PO::planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_getparametertypes::Requested";
    
    planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_getparametertypesOutput response;
    ara::core::Promise<planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_getparametertypesOutput> promise;
    
    // put your logic
    
    promise.set_value(response);
    return promise.get_future();
}
 
ara::core::Future<PO_SI_elasticbandsmootherSkeleton::planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_listparametersOutput> PO_SI_elasticbandsmootherSkeletonImpl::planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_listparameters(const oss::type::rcl_interfaces::srv::ListParameters_Request& req)
{
    m_logger.LogVerbose() << "PPort_EBS2PO::planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_listparameters::Requested";
    
    planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_listparametersOutput response;
    ara::core::Promise<planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_listparametersOutput> promise;
    
    // put your logic
    
    promise.set_value(response);
    return promise.get_future();
}
 
ara::core::Future<PO_SI_elasticbandsmootherSkeleton::planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_setparametersOutput> PO_SI_elasticbandsmootherSkeletonImpl::planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_setparameters(const oss::type::rcl_interfaces::srv::SetParameters_Request& req)
{
    m_logger.LogVerbose() << "PPort_EBS2PO::planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_setparameters::Requested";
    
    planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_setparametersOutput response;
    ara::core::Promise<planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_setparametersOutput> promise;
    
    // put your logic
    
    promise.set_value(response);
    return promise.get_future();
}
 
ara::core::Future<PO_SI_elasticbandsmootherSkeleton::planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_setparametersatomicallyOutput> PO_SI_elasticbandsmootherSkeletonImpl::planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_setparametersatomically(const oss::type::rcl_interfaces::srv::SetParametersAtomically_Request& req)
{
    m_logger.LogVerbose() << "PPort_EBS2PO::planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_setparametersatomically::Requested";
    
    planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_setparametersatomicallyOutput response;
    ara::core::Promise<planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_setparametersatomicallyOutput> promise;
    
    // put your logic
    
    promise.set_value(response);
    return promise.get_future();
}
 
} /// namespace skeleton
} /// namespace EBS2PO
} /// namespace srv
} /// namespace oss

namespace exe_elasticbandsmoother
{
namespace aa
{
namespace port
{
 
PPort_EBS2PO::PPort_EBS2PO()
    : m_logger(ara::log::CreateLogger("EBST", "PORT", ara::log::LogLevel::kVerbose))
    , m_running{false}
    , m_planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_calculationtimeData{{0, 0U}, "str_string"}
    , m_planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_ebfixedtrajData{{{0, 0U}, "str_string"}, {{{0, 0U}, {{0.0, 0.0, 0.0}, {0.0, 0.0, 0.0, 0.0}}, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f}, {{0, 0U}, {{0.0, 0.0, 0.0}, {0.0, 0.0, 0.0, 0.0}}, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f}, {{0, 0U}, {{0.0, 0.0, 0.0}, {0.0, 0.0, 0.0, 0.0}}, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f}}}
    , m_planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_ebtrajData{{{0, 0U}, "str_string"}, {{{0, 0U}, {{0.0, 0.0, 0.0}, {0.0, 0.0, 0.0, 0.0}}, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f}, {{0, 0U}, {{0.0, 0.0, 0.0}, {0.0, 0.0, 0.0, 0.0}}, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f}, {{0, 0U}, {{0.0, 0.0, 0.0}, {0.0, 0.0, 0.0, 0.0}}, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f}}}
    , m_planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_extendedtrajData{{{0, 0U}, "str_string"}, {{{0, 0U}, {{0.0, 0.0, 0.0}, {0.0, 0.0, 0.0, 0.0}}, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f}, {{0, 0U}, {{0.0, 0.0, 0.0}, {0.0, 0.0, 0.0, 0.0}}, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f}, {{0, 0U}, {{0.0, 0.0, 0.0}, {0.0, 0.0, 0.0, 0.0}}, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f}}}
    , m_planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_processingtimemsData{{0, 0U}, 0.0}
    , m_planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_output_trajData{{{0, 0U}, "str_string"}, {{{0, 0U}, {{0.0, 0.0, 0.0}, {0.0, 0.0, 0.0, 0.0}}, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f}, {{0, 0U}, {{0.0, 0.0, 0.0}, {0.0, 0.0, 0.0, 0.0}}, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f}, {{0, 0U}, {{0.0, 0.0, 0.0}, {0.0, 0.0, 0.0, 0.0}}, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f}}}
    , m_planning_scenarioplanning_lanedriving_motionplanning_pathsmoother_pathData{{{0, 0U}, "str_string"}, {{{{0.0, 0.0, 0.0}, {0.0, 0.0, 0.0, 0.0}}, 0.0f, 0.0f, 0.0f, false}, {{{0.0, 0.0, 0.0}, {0.0, 0.0, 0.0, 0.0}}, 0.0f, 0.0f, 0.0f, false}, {{{0.0, 0.0, 0.0}, {0.0, 0.0, 0.0, 0.0}}, 0.0f, 0.0f, 0.0f, false}}, {{0.0, 0.0, 0.0}, {0.0, 0.0, 0.0}, {0.0, 0.0, 0.0}}, {{0.0, 0.0, 0.0}, {0.0, 0.0, 0.0}, {0.0, 0.0, 0.0}}}
{
}
 
PPort_EBS2PO::~PPort_EBS2PO()
{
}
 
void PPort_EBS2PO::Start()
{
    m_logger.LogVerbose() << "PPort_EBS2PO::Start";
    
    // construct skeleton
    ara::core::InstanceSpecifier specifier{"Exe_elasticbandsmoother/AA/PPort_EBS2PO"};
    m_interface = std::make_unique<oss::srv::EBS2PO::skeleton::PO_SI_elasticbandsmootherSkeletonImpl>(specifier);
    
    // offer service
    auto offer = m_interface->OfferService();
    if (offer.HasValue())
    {
        m_running = true;
        m_logger.LogVerbose() << "PPort_EBS2PO::Start::OfferService";
    }
    else
    {
        m_running = false;
        m_logger.LogError() << "PPort_EBS2PO::Start::OfferService::" << offer.Error().Message();
    }
}
 
void PPort_EBS2PO::Terminate()
{
    m_logger.LogVerbose() << "PPort_EBS2PO::Terminate";
    
    // stop port
    m_running = false;
    
    // stop offer service
    m_interface->StopOfferService();
    m_logger.LogVerbose() << "PPort_EBS2PO::Terminate::StopOfferService";
}
 
void PPort_EBS2PO::WriteDataplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_calculationtime(const oss::srv::EBS2PO::skeleton::events::planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_calculationtime::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    m_planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_calculationtimeData = data;
}
 
void PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_calculationtimeCyclic()
{
    while (m_running)
    {
        {
            std::lock_guard<std::mutex> lock(m_mutex);
            
            auto send = m_interface->planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_calculationtime.Send(m_planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_calculationtimeData);
            if (send.HasValue())
            {
                m_logger.LogVerbose() << "PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_calculationtimeCyclic::Send";
            }
            else
            {
                m_logger.LogError() << "PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_calculationtimeCyclic::Send::" << send.Error().Message();
            }
        }
        std::this_thread::sleep_for(std::chrono::seconds(1));
    }
}
 
void PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_calculationtimeTriggered()
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    auto send = m_interface->planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_calculationtime.Send(m_planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_calculationtimeData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_calculationtimeTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_calculationtimeTriggered::Send::" << send.Error().Message();
    }
}
 
void PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_calculationtimeTriggered(const oss::srv::EBS2PO::skeleton::events::planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_calculationtime::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    m_planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_calculationtimeData = data;
    auto send = m_interface->planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_calculationtime.Send(m_planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_calculationtimeData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_calculationtimeTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_calculationtimeTriggered::Send::" << send.Error().Message();
    }
}
 
void PPort_EBS2PO::WriteDataplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_ebfixedtraj(const oss::srv::EBS2PO::skeleton::events::planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_ebfixedtraj::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    m_planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_ebfixedtrajData = data;
}
 
void PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_ebfixedtrajCyclic()
{
    while (m_running)
    {
        {
            std::lock_guard<std::mutex> lock(m_mutex);
            
            auto send = m_interface->planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_ebfixedtraj.Send(m_planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_ebfixedtrajData);
            if (send.HasValue())
            {
                m_logger.LogVerbose() << "PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_ebfixedtrajCyclic::Send";
            }
            else
            {
                m_logger.LogError() << "PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_ebfixedtrajCyclic::Send::" << send.Error().Message();
            }
        }
        std::this_thread::sleep_for(std::chrono::seconds(1));
    }
}
 
void PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_ebfixedtrajTriggered()
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    auto send = m_interface->planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_ebfixedtraj.Send(m_planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_ebfixedtrajData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_ebfixedtrajTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_ebfixedtrajTriggered::Send::" << send.Error().Message();
    }
}
 
void PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_ebfixedtrajTriggered(const oss::srv::EBS2PO::skeleton::events::planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_ebfixedtraj::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    m_planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_ebfixedtrajData = data;
    auto send = m_interface->planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_ebfixedtraj.Send(m_planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_ebfixedtrajData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_ebfixedtrajTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_ebfixedtrajTriggered::Send::" << send.Error().Message();
    }
}
 
void PPort_EBS2PO::WriteDataplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_ebtraj(const oss::srv::EBS2PO::skeleton::events::planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_ebtraj::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    m_planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_ebtrajData = data;
}
 
void PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_ebtrajCyclic()
{
    while (m_running)
    {
        {
            std::lock_guard<std::mutex> lock(m_mutex);
            
            auto send = m_interface->planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_ebtraj.Send(m_planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_ebtrajData);
            if (send.HasValue())
            {
                m_logger.LogVerbose() << "PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_ebtrajCyclic::Send";
            }
            else
            {
                m_logger.LogError() << "PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_ebtrajCyclic::Send::" << send.Error().Message();
            }
        }
        std::this_thread::sleep_for(std::chrono::seconds(1));
    }
}
 
void PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_ebtrajTriggered()
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    auto send = m_interface->planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_ebtraj.Send(m_planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_ebtrajData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_ebtrajTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_ebtrajTriggered::Send::" << send.Error().Message();
    }
}
 
void PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_ebtrajTriggered(const oss::srv::EBS2PO::skeleton::events::planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_ebtraj::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    m_planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_ebtrajData = data;
    auto send = m_interface->planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_ebtraj.Send(m_planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_ebtrajData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_ebtrajTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_ebtrajTriggered::Send::" << send.Error().Message();
    }
}
 
void PPort_EBS2PO::WriteDataplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_extendedtraj(const oss::srv::EBS2PO::skeleton::events::planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_extendedtraj::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    m_planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_extendedtrajData = data;
}
 
void PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_extendedtrajCyclic()
{
    while (m_running)
    {
        {
            std::lock_guard<std::mutex> lock(m_mutex);
            
            auto send = m_interface->planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_extendedtraj.Send(m_planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_extendedtrajData);
            if (send.HasValue())
            {
                m_logger.LogVerbose() << "PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_extendedtrajCyclic::Send";
            }
            else
            {
                m_logger.LogError() << "PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_extendedtrajCyclic::Send::" << send.Error().Message();
            }
        }
        std::this_thread::sleep_for(std::chrono::seconds(1));
    }
}
 
void PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_extendedtrajTriggered()
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    auto send = m_interface->planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_extendedtraj.Send(m_planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_extendedtrajData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_extendedtrajTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_extendedtrajTriggered::Send::" << send.Error().Message();
    }
}
 
void PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_extendedtrajTriggered(const oss::srv::EBS2PO::skeleton::events::planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_extendedtraj::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    m_planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_extendedtrajData = data;
    auto send = m_interface->planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_extendedtraj.Send(m_planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_extendedtrajData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_extendedtrajTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_extendedtrajTriggered::Send::" << send.Error().Message();
    }
}
 
void PPort_EBS2PO::WriteDataplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_processingtimems(const oss::srv::EBS2PO::skeleton::events::planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_processingtimems::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    m_planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_processingtimemsData = data;
}
 
void PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_processingtimemsCyclic()
{
    while (m_running)
    {
        {
            std::lock_guard<std::mutex> lock(m_mutex);
            
            auto send = m_interface->planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_processingtimems.Send(m_planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_processingtimemsData);
            if (send.HasValue())
            {
                m_logger.LogVerbose() << "PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_processingtimemsCyclic::Send";
            }
            else
            {
                m_logger.LogError() << "PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_processingtimemsCyclic::Send::" << send.Error().Message();
            }
        }
        std::this_thread::sleep_for(std::chrono::seconds(1));
    }
}
 
void PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_processingtimemsTriggered()
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    auto send = m_interface->planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_processingtimems.Send(m_planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_processingtimemsData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_processingtimemsTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_processingtimemsTriggered::Send::" << send.Error().Message();
    }
}
 
void PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_processingtimemsTriggered(const oss::srv::EBS2PO::skeleton::events::planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_processingtimems::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    m_planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_processingtimemsData = data;
    auto send = m_interface->planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_processingtimems.Send(m_planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_processingtimemsData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_processingtimemsTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_debug_processingtimemsTriggered::Send::" << send.Error().Message();
    }
}
 
void PPort_EBS2PO::WriteDataplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_output_traj(const oss::srv::EBS2PO::skeleton::events::planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_output_traj::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    m_planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_output_trajData = data;
}
 
void PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_output_trajCyclic()
{
    while (m_running)
    {
        {
            std::lock_guard<std::mutex> lock(m_mutex);
            
            auto send = m_interface->planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_output_traj.Send(m_planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_output_trajData);
            if (send.HasValue())
            {
                m_logger.LogVerbose() << "PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_output_trajCyclic::Send";
            }
            else
            {
                m_logger.LogError() << "PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_output_trajCyclic::Send::" << send.Error().Message();
            }
        }
        std::this_thread::sleep_for(std::chrono::seconds(1));
    }
}
 
void PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_output_trajTriggered()
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    auto send = m_interface->planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_output_traj.Send(m_planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_output_trajData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_output_trajTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_output_trajTriggered::Send::" << send.Error().Message();
    }
}
 
void PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_output_trajTriggered(const oss::srv::EBS2PO::skeleton::events::planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_output_traj::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    m_planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_output_trajData = data;
    auto send = m_interface->planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_output_traj.Send(m_planning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_output_trajData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_output_trajTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_elasticbandsmoother_output_trajTriggered::Send::" << send.Error().Message();
    }
}
 
void PPort_EBS2PO::WriteDataplanning_scenarioplanning_lanedriving_motionplanning_pathsmoother_path(const oss::srv::EBS2PO::skeleton::events::planning_scenarioplanning_lanedriving_motionplanning_pathsmoother_path::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    m_planning_scenarioplanning_lanedriving_motionplanning_pathsmoother_pathData = data;
}
 
void PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathsmoother_pathCyclic()
{
    while (m_running)
    {
        {
            std::lock_guard<std::mutex> lock(m_mutex);
            
            auto send = m_interface->planning_scenarioplanning_lanedriving_motionplanning_pathsmoother_path.Send(m_planning_scenarioplanning_lanedriving_motionplanning_pathsmoother_pathData);
            if (send.HasValue())
            {
                m_logger.LogVerbose() << "PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathsmoother_pathCyclic::Send";
            }
            else
            {
                // m_logger.LogError() << "PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathsmoother_pathCyclic::Send::" << send.Error().Message();
            }
        }
        std::this_thread::sleep_for(std::chrono::seconds(5));
    }
}
 
void PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathsmoother_pathTriggered()
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    auto send = m_interface->planning_scenarioplanning_lanedriving_motionplanning_pathsmoother_path.Send(m_planning_scenarioplanning_lanedriving_motionplanning_pathsmoother_pathData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathsmoother_pathTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathsmoother_pathTriggered::Send::" << send.Error().Message();
    }
}
 
void PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathsmoother_pathTriggered(const oss::srv::EBS2PO::skeleton::events::planning_scenarioplanning_lanedriving_motionplanning_pathsmoother_path::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    m_planning_scenarioplanning_lanedriving_motionplanning_pathsmoother_pathData = data;
    auto send = m_interface->planning_scenarioplanning_lanedriving_motionplanning_pathsmoother_path.Send(m_planning_scenarioplanning_lanedriving_motionplanning_pathsmoother_pathData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathsmoother_pathTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "PPort_EBS2PO::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathsmoother_pathTriggered::Send::" << send.Error().Message();
    }
}
 
} /// namespace port
} /// namespace aa
} /// namespace exe_elasticbandsmoother
 
/// EOF