///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : pport_po2mvp.cpp
/// SOFTWARE COMPONENT NAME           : PPort_PO2MVP
/// GENERATED DATE                    : 2025-12-05 12:02:34
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "exe_pathoptimizer/aa/port/pport_po2mvp.h"
 
namespace oss
{
namespace srv
{
namespace PO2MVP
{
namespace skeleton
{
 
MVP_SI_pathoptimizerSkeletonImpl::MVP_SI_pathoptimizerSkeletonImpl(ara::core::InstanceSpecifier instanceSpec, ara::com::MethodCallProcessingMode mode)
    : MVP_SI_pathoptimizerSkeleton(instanceSpec, mode)
    , m_logger(ara::log::CreateLogger("PTOP", "PORT", ara::log::LogLevel::kVerbose))
{
}
 
ara::core::Future<MVP_SI_pathoptimizerSkeleton::planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_configloggerOutput> MVP_SI_pathoptimizerSkeletonImpl::planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_configlogger(const oss::type::logging_demo::srv::ConfigLogger_Request& req)
{
    m_logger.LogVerbose() << "PPort_PO2MVP::planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_configlogger::Requested";
    
    planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_configloggerOutput response;
    ara::core::Promise<planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_configloggerOutput> promise;
    
    // put your logic
    
    promise.set_value(response);
    return promise.get_future();
}
 
ara::core::Future<MVP_SI_pathoptimizerSkeleton::planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_describeparametersOutput> MVP_SI_pathoptimizerSkeletonImpl::planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_describeparameters(const oss::type::rcl_interfaces::srv::DescribeParameters_Request& req)
{
    m_logger.LogVerbose() << "PPort_PO2MVP::planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_describeparameters::Requested";
    
    planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_describeparametersOutput response;
    ara::core::Promise<planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_describeparametersOutput> promise;
    
    // put your logic
    
    promise.set_value(response);
    return promise.get_future();
}
 
ara::core::Future<MVP_SI_pathoptimizerSkeleton::planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_getparametersOutput> MVP_SI_pathoptimizerSkeletonImpl::planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_getparameters(const oss::type::rcl_interfaces::srv::GetParameters_Request& req)
{
    m_logger.LogVerbose() << "PPort_PO2MVP::planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_getparameters::Requested";
    
    planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_getparametersOutput response;
    ara::core::Promise<planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_getparametersOutput> promise;
    
    // put your logic
    
    promise.set_value(response);
    return promise.get_future();
}
 
ara::core::Future<MVP_SI_pathoptimizerSkeleton::planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_getparametertypesOutput> MVP_SI_pathoptimizerSkeletonImpl::planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_getparametertypes(const oss::type::rcl_interfaces::srv::GetParameterTypes_Request& req)
{
    m_logger.LogVerbose() << "PPort_PO2MVP::planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_getparametertypes::Requested";
    
    planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_getparametertypesOutput response;
    ara::core::Promise<planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_getparametertypesOutput> promise;
    
    // put your logic
    
    promise.set_value(response);
    return promise.get_future();
}
 
ara::core::Future<MVP_SI_pathoptimizerSkeleton::planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_listparametersOutput> MVP_SI_pathoptimizerSkeletonImpl::planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_listparameters(const oss::type::rcl_interfaces::srv::ListParameters_Request& req)
{
    m_logger.LogVerbose() << "PPort_PO2MVP::planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_listparameters::Requested";
    
    planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_listparametersOutput response;
    ara::core::Promise<planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_listparametersOutput> promise;
    
    // put your logic
    
    promise.set_value(response);
    return promise.get_future();
}
 
ara::core::Future<MVP_SI_pathoptimizerSkeleton::planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_setparametersOutput> MVP_SI_pathoptimizerSkeletonImpl::planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_setparameters(const oss::type::rcl_interfaces::srv::SetParameters_Request& req)
{
    m_logger.LogVerbose() << "PPort_PO2MVP::planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_setparameters::Requested";
    
    planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_setparametersOutput response;
    ara::core::Promise<planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_setparametersOutput> promise;
    
    // put your logic
    
    promise.set_value(response);
    return promise.get_future();
}
 
ara::core::Future<MVP_SI_pathoptimizerSkeleton::planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_setparametersatomicallyOutput> MVP_SI_pathoptimizerSkeletonImpl::planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_setparametersatomically(const oss::type::rcl_interfaces::srv::SetParametersAtomically_Request& req)
{
    m_logger.LogVerbose() << "PPort_PO2MVP::planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_setparametersatomically::Requested";
    
    planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_setparametersatomicallyOutput response;
    ara::core::Promise<planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_setparametersatomicallyOutput> promise;
    
    // put your logic
    
    promise.set_value(response);
    return promise.get_future();
}
 
} /// namespace skeleton
} /// namespace PO2MVP
} /// namespace srv
} /// namespace oss

namespace exe_pathoptimizer
{
namespace aa
{
namespace port
{
 
PPort_PO2MVP::PPort_PO2MVP()
    : m_logger(ara::log::CreateLogger("PTOP", "PORT", ara::log::LogLevel::kVerbose))
    , m_running{false}
    , m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_calculationtimeData{{0, 0U}, "str_string"}
    , m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_extendedtrajData{{{0, 0U}, "str_string"}, {{{0, 0U}, {{0.0, 0.0, 0.0}, {0.0, 0.0, 0.0, 0.0}}, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f}, {{0, 0U}, {{0.0, 0.0, 0.0}, {0.0, 0.0, 0.0, 0.0}}, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f}, {{0, 0U}, {{0.0, 0.0, 0.0}, {0.0, 0.0, 0.0, 0.0}}, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f}}}
    , m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_markerData{{{{{0, 0U}, "str_string"}, "str_string", 0, oss::type::Marker_type::ARROW, oss::type::Marker_action::ADD, {{0.0, 0.0, 0.0}, {0.0, 0.0, 0.0, 0.0}}, {0.0, 0.0, 0.0}, {0.0f, 0.0f, 0.0f, 0.0f}, {0, 0U}, false, {{0.0, 0.0, 0.0}, {0.0, 0.0, 0.0}, {0.0, 0.0, 0.0}}, {{0.0f, 0.0f, 0.0f, 0.0f}, {0.0f, 0.0f, 0.0f, 0.0f}, {0.0f, 0.0f, 0.0f, 0.0f}}, "str_string", {{{0, 0U}, "str_string"}, "str_string", {0U, 0U, 0U}}, {{0.0f, 0.0f}, {0.0f, 0.0f}, {0.0f, 0.0f}}, "str_string", "str_string", {"str_string", {0U, 0U, 0U}}, false}, {{{0, 0U}, "str_string"}, "str_string", 0, oss::type::Marker_type::ARROW, oss::type::Marker_action::ADD, {{0.0, 0.0, 0.0}, {0.0, 0.0, 0.0, 0.0}}, {0.0, 0.0, 0.0}, {0.0f, 0.0f, 0.0f, 0.0f}, {0, 0U}, false, {{0.0, 0.0, 0.0}, {0.0, 0.0, 0.0}, {0.0, 0.0, 0.0}}, {{0.0f, 0.0f, 0.0f, 0.0f}, {0.0f, 0.0f, 0.0f, 0.0f}, {0.0f, 0.0f, 0.0f, 0.0f}}, "str_string", {{{0, 0U}, "str_string"}, "str_string", {0U, 0U, 0U}}, {{0.0f, 0.0f}, {0.0f, 0.0f}, {0.0f, 0.0f}}, "str_string", "str_string", {"str_string", {0U, 0U, 0U}}, false}, {{{0, 0U}, "str_string"}, "str_string", 0, oss::type::Marker_type::ARROW, oss::type::Marker_action::ADD, {{0.0, 0.0, 0.0}, {0.0, 0.0, 0.0, 0.0}}, {0.0, 0.0, 0.0}, {0.0f, 0.0f, 0.0f, 0.0f}, {0, 0U}, false, {{0.0, 0.0, 0.0}, {0.0, 0.0, 0.0}, {0.0, 0.0, 0.0}}, {{0.0f, 0.0f, 0.0f, 0.0f}, {0.0f, 0.0f, 0.0f, 0.0f}, {0.0f, 0.0f, 0.0f, 0.0f}}, "str_string", {{{0, 0U}, "str_string"}, "str_string", {0U, 0U, 0U}}, {{0.0f, 0.0f}, {0.0f, 0.0f}, {0.0f, 0.0f}}, "str_string", "str_string", {"str_string", {0U, 0U, 0U}}, false}}}
    , m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mptfixedtrajData{{{0, 0U}, "str_string"}, {{{0, 0U}, {{0.0, 0.0, 0.0}, {0.0, 0.0, 0.0, 0.0}}, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f}, {{0, 0U}, {{0.0, 0.0, 0.0}, {0.0, 0.0, 0.0, 0.0}}, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f}, {{0, 0U}, {{0.0, 0.0, 0.0}, {0.0, 0.0, 0.0, 0.0}}, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f}}}
    , m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mptreftrajData{{{0, 0U}, "str_string"}, {{{0, 0U}, {{0.0, 0.0, 0.0}, {0.0, 0.0, 0.0, 0.0}}, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f}, {{0, 0U}, {{0.0, 0.0, 0.0}, {0.0, 0.0, 0.0, 0.0}}, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f}, {{0, 0U}, {{0.0, 0.0, 0.0}, {0.0, 0.0, 0.0, 0.0}}, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f}}}
    , m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mpttrajData{{{0, 0U}, "str_string"}, {{{0, 0U}, {{0.0, 0.0, 0.0}, {0.0, 0.0, 0.0, 0.0}}, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f}, {{0, 0U}, {{0.0, 0.0, 0.0}, {0.0, 0.0, 0.0, 0.0}}, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f}, {{0, 0U}, {{0.0, 0.0, 0.0}, {0.0, 0.0, 0.0, 0.0}}, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f}}}
    , m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_processingtimedetailmsData{{{0, "str_string", 0.0, 0, "str_string"}, {0, "str_string", 0.0, 0, "str_string"}, {0, "str_string", 0.0, 0, "str_string"}}}
    , m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_processingtimemsData{{0, 0U}, 0.0}
    , m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_trajectoryData{{{0, 0U}, "str_string"}, {{{0, 0U}, {{0.0, 0.0, 0.0}, {0.0, 0.0, 0.0, 0.0}}, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f}, {{0, 0U}, {{0.0, 0.0, 0.0}, {0.0, 0.0, 0.0, 0.0}}, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f}, {{0, 0U}, {{0.0, 0.0, 0.0}, {0.0, 0.0, 0.0, 0.0}}, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f}}}
    , m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_virtualwallData{{{{{0, 0U}, "str_string"}, "str_string", 0, oss::type::Marker_type::ARROW, oss::type::Marker_action::ADD, {{0.0, 0.0, 0.0}, {0.0, 0.0, 0.0, 0.0}}, {0.0, 0.0, 0.0}, {0.0f, 0.0f, 0.0f, 0.0f}, {0, 0U}, false, {{0.0, 0.0, 0.0}, {0.0, 0.0, 0.0}, {0.0, 0.0, 0.0}}, {{0.0f, 0.0f, 0.0f, 0.0f}, {0.0f, 0.0f, 0.0f, 0.0f}, {0.0f, 0.0f, 0.0f, 0.0f}}, "str_string", {{{0, 0U}, "str_string"}, "str_string", {0U, 0U, 0U}}, {{0.0f, 0.0f}, {0.0f, 0.0f}, {0.0f, 0.0f}}, "str_string", "str_string", {"str_string", {0U, 0U, 0U}}, false}, {{{0, 0U}, "str_string"}, "str_string", 0, oss::type::Marker_type::ARROW, oss::type::Marker_action::ADD, {{0.0, 0.0, 0.0}, {0.0, 0.0, 0.0, 0.0}}, {0.0, 0.0, 0.0}, {0.0f, 0.0f, 0.0f, 0.0f}, {0, 0U}, false, {{0.0, 0.0, 0.0}, {0.0, 0.0, 0.0}, {0.0, 0.0, 0.0}}, {{0.0f, 0.0f, 0.0f, 0.0f}, {0.0f, 0.0f, 0.0f, 0.0f}, {0.0f, 0.0f, 0.0f, 0.0f}}, "str_string", {{{0, 0U}, "str_string"}, "str_string", {0U, 0U, 0U}}, {{0.0f, 0.0f}, {0.0f, 0.0f}, {0.0f, 0.0f}}, "str_string", "str_string", {"str_string", {0U, 0U, 0U}}, false}, {{{0, 0U}, "str_string"}, "str_string", 0, oss::type::Marker_type::ARROW, oss::type::Marker_action::ADD, {{0.0, 0.0, 0.0}, {0.0, 0.0, 0.0, 0.0}}, {0.0, 0.0, 0.0}, {0.0f, 0.0f, 0.0f, 0.0f}, {0, 0U}, false, {{0.0, 0.0, 0.0}, {0.0, 0.0, 0.0}, {0.0, 0.0, 0.0}}, {{0.0f, 0.0f, 0.0f, 0.0f}, {0.0f, 0.0f, 0.0f, 0.0f}, {0.0f, 0.0f, 0.0f, 0.0f}}, "str_string", {{{0, 0U}, "str_string"}, "str_string", {0U, 0U, 0U}}, {{0.0f, 0.0f}, {0.0f, 0.0f}, {0.0f, 0.0f}}, "str_string", "str_string", {"str_string", {0U, 0U, 0U}}, false}}}
{
}
 
PPort_PO2MVP::~PPort_PO2MVP()
{
}
 
void PPort_PO2MVP::Start()
{
    m_logger.LogVerbose() << "PPort_PO2MVP::Start";
    
    // construct skeleton
    ara::core::InstanceSpecifier specifier{"Exe_pathoptimizer/AA/PPort_PO2MVP"};
    m_interface = std::make_unique<oss::srv::PO2MVP::skeleton::MVP_SI_pathoptimizerSkeletonImpl>(specifier);
    
    // offer service
    auto offer = m_interface->OfferService();
    if (offer.HasValue())
    {
        m_running = true;
        m_logger.LogVerbose() << "PPort_PO2MVP::Start::OfferService";
    }
    else
    {
        m_running = false;
        m_logger.LogError() << "PPort_PO2MVP::Start::OfferService::" << offer.Error().Message();
    }
}
 
void PPort_PO2MVP::Terminate()
{
    m_logger.LogVerbose() << "PPort_PO2MVP::Terminate";
    
    // stop port
    m_running = false;
    
    // stop offer service
    m_interface->StopOfferService();
    m_logger.LogVerbose() << "PPort_PO2MVP::Terminate::StopOfferService";
}
 
void PPort_PO2MVP::WriteDataplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_calculationtime(const oss::srv::PO2MVP::skeleton::events::planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_calculationtime::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_calculationtimeData = data;
}
 
void PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_calculationtimeCyclic()
{
    while (m_running)
    {
        {
            std::lock_guard<std::mutex> lock(m_mutex);
            
            auto send = m_interface->planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_calculationtime.Send(m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_calculationtimeData);
            if (send.HasValue())
            {
                m_logger.LogVerbose() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_calculationtimeCyclic::Send";
            }
            else
            {
                m_logger.LogError() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_calculationtimeCyclic::Send::" << send.Error().Message();
            }
        }
        std::this_thread::sleep_for(std::chrono::seconds(1));
    }
}
 
void PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_calculationtimeTriggered()
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    auto send = m_interface->planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_calculationtime.Send(m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_calculationtimeData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_calculationtimeTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_calculationtimeTriggered::Send::" << send.Error().Message();
    }
}
 
void PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_calculationtimeTriggered(const oss::srv::PO2MVP::skeleton::events::planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_calculationtime::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_calculationtimeData = data;
    auto send = m_interface->planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_calculationtime.Send(m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_calculationtimeData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_calculationtimeTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_calculationtimeTriggered::Send::" << send.Error().Message();
    }
}
 
void PPort_PO2MVP::WriteDataplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_extendedtraj(const oss::srv::PO2MVP::skeleton::events::planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_extendedtraj::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_extendedtrajData = data;
}
 
void PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_extendedtrajCyclic()
{
    while (m_running)
    {
        {
            std::lock_guard<std::mutex> lock(m_mutex);
            
            auto send = m_interface->planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_extendedtraj.Send(m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_extendedtrajData);
            if (send.HasValue())
            {
                m_logger.LogVerbose() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_extendedtrajCyclic::Send";
            }
            else
            {
                m_logger.LogError() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_extendedtrajCyclic::Send::" << send.Error().Message();
            }
        }
        std::this_thread::sleep_for(std::chrono::seconds(1));
    }
}
 
void PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_extendedtrajTriggered()
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    auto send = m_interface->planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_extendedtraj.Send(m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_extendedtrajData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_extendedtrajTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_extendedtrajTriggered::Send::" << send.Error().Message();
    }
}
 
void PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_extendedtrajTriggered(const oss::srv::PO2MVP::skeleton::events::planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_extendedtraj::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_extendedtrajData = data;
    auto send = m_interface->planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_extendedtraj.Send(m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_extendedtrajData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_extendedtrajTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_extendedtrajTriggered::Send::" << send.Error().Message();
    }
}
 
void PPort_PO2MVP::WriteDataplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_marker(const oss::srv::PO2MVP::skeleton::events::planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_marker::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_markerData = data;
}
 
void PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_markerCyclic()
{
    while (m_running)
    {
        {
            std::lock_guard<std::mutex> lock(m_mutex);
            
            auto send = m_interface->planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_marker.Send(m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_markerData);
            if (send.HasValue())
            {
                m_logger.LogVerbose() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_markerCyclic::Send";
            }
            else
            {
                m_logger.LogError() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_markerCyclic::Send::" << send.Error().Message();
            }
        }
        std::this_thread::sleep_for(std::chrono::seconds(1));
    }
}
 
void PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_markerTriggered()
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    auto send = m_interface->planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_marker.Send(m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_markerData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_markerTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_markerTriggered::Send::" << send.Error().Message();
    }
}
 
void PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_markerTriggered(const oss::srv::PO2MVP::skeleton::events::planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_marker::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_markerData = data;
    auto send = m_interface->planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_marker.Send(m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_markerData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_markerTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_markerTriggered::Send::" << send.Error().Message();
    }
}
 
void PPort_PO2MVP::WriteDataplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mptfixedtraj(const oss::srv::PO2MVP::skeleton::events::planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mptfixedtraj::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mptfixedtrajData = data;
}
 
void PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mptfixedtrajCyclic()
{
    while (m_running)
    {
        {
            std::lock_guard<std::mutex> lock(m_mutex);
            
            auto send = m_interface->planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mptfixedtraj.Send(m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mptfixedtrajData);
            if (send.HasValue())
            {
                m_logger.LogVerbose() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mptfixedtrajCyclic::Send";
            }
            else
            {
                m_logger.LogError() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mptfixedtrajCyclic::Send::" << send.Error().Message();
            }
        }
        std::this_thread::sleep_for(std::chrono::seconds(1));
    }
}
 
void PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mptfixedtrajTriggered()
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    auto send = m_interface->planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mptfixedtraj.Send(m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mptfixedtrajData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mptfixedtrajTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mptfixedtrajTriggered::Send::" << send.Error().Message();
    }
}
 
void PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mptfixedtrajTriggered(const oss::srv::PO2MVP::skeleton::events::planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mptfixedtraj::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mptfixedtrajData = data;
    auto send = m_interface->planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mptfixedtraj.Send(m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mptfixedtrajData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mptfixedtrajTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mptfixedtrajTriggered::Send::" << send.Error().Message();
    }
}
 
void PPort_PO2MVP::WriteDataplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mptreftraj(const oss::srv::PO2MVP::skeleton::events::planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mptreftraj::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mptreftrajData = data;
}
 
void PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mptreftrajCyclic()
{
    while (m_running)
    {
        {
            std::lock_guard<std::mutex> lock(m_mutex);
            
            auto send = m_interface->planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mptreftraj.Send(m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mptreftrajData);
            if (send.HasValue())
            {
                m_logger.LogVerbose() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mptreftrajCyclic::Send";
            }
            else
            {
                m_logger.LogError() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mptreftrajCyclic::Send::" << send.Error().Message();
            }
        }
        std::this_thread::sleep_for(std::chrono::seconds(1));
    }
}
 
void PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mptreftrajTriggered()
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    auto send = m_interface->planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mptreftraj.Send(m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mptreftrajData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mptreftrajTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mptreftrajTriggered::Send::" << send.Error().Message();
    }
}
 
void PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mptreftrajTriggered(const oss::srv::PO2MVP::skeleton::events::planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mptreftraj::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mptreftrajData = data;
    auto send = m_interface->planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mptreftraj.Send(m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mptreftrajData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mptreftrajTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mptreftrajTriggered::Send::" << send.Error().Message();
    }
}
 
void PPort_PO2MVP::WriteDataplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mpttraj(const oss::srv::PO2MVP::skeleton::events::planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mpttraj::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mpttrajData = data;
}
 
void PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mpttrajCyclic()
{
    while (m_running)
    {
        {
            std::lock_guard<std::mutex> lock(m_mutex);
            
            auto send = m_interface->planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mpttraj.Send(m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mpttrajData);
            if (send.HasValue())
            {
                m_logger.LogVerbose() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mpttrajCyclic::Send";
            }
            else
            {
                m_logger.LogError() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mpttrajCyclic::Send::" << send.Error().Message();
            }
        }
        std::this_thread::sleep_for(std::chrono::seconds(1));
    }
}
 
void PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mpttrajTriggered()
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    auto send = m_interface->planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mpttraj.Send(m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mpttrajData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mpttrajTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mpttrajTriggered::Send::" << send.Error().Message();
    }
}
 
void PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mpttrajTriggered(const oss::srv::PO2MVP::skeleton::events::planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mpttraj::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mpttrajData = data;
    auto send = m_interface->planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mpttraj.Send(m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mpttrajData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mpttrajTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_mpttrajTriggered::Send::" << send.Error().Message();
    }
}
 
void PPort_PO2MVP::WriteDataplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_processingtimedetailms(const oss::srv::PO2MVP::skeleton::events::planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_processingtimedetailms::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_processingtimedetailmsData = data;
}
 
void PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_processingtimedetailmsCyclic()
{
    while (m_running)
    {
        {
            std::lock_guard<std::mutex> lock(m_mutex);
            
            auto send = m_interface->planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_processingtimedetailms.Send(m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_processingtimedetailmsData);
            if (send.HasValue())
            {
                m_logger.LogVerbose() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_processingtimedetailmsCyclic::Send";
            }
            else
            {
                m_logger.LogError() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_processingtimedetailmsCyclic::Send::" << send.Error().Message();
            }
        }
        std::this_thread::sleep_for(std::chrono::seconds(1));
    }
}
 
void PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_processingtimedetailmsTriggered()
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    auto send = m_interface->planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_processingtimedetailms.Send(m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_processingtimedetailmsData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_processingtimedetailmsTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_processingtimedetailmsTriggered::Send::" << send.Error().Message();
    }
}
 
void PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_processingtimedetailmsTriggered(const oss::srv::PO2MVP::skeleton::events::planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_processingtimedetailms::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_processingtimedetailmsData = data;
    auto send = m_interface->planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_processingtimedetailms.Send(m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_processingtimedetailmsData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_processingtimedetailmsTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_processingtimedetailmsTriggered::Send::" << send.Error().Message();
    }
}
 
void PPort_PO2MVP::WriteDataplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_processingtimems(const oss::srv::PO2MVP::skeleton::events::planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_processingtimems::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_processingtimemsData = data;
}
 
void PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_processingtimemsCyclic()
{
    while (m_running)
    {
        {
            std::lock_guard<std::mutex> lock(m_mutex);
            
            auto send = m_interface->planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_processingtimems.Send(m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_processingtimemsData);
            if (send.HasValue())
            {
                m_logger.LogVerbose() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_processingtimemsCyclic::Send";
            }
            else
            {
                m_logger.LogError() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_processingtimemsCyclic::Send::" << send.Error().Message();
            }
        }
        std::this_thread::sleep_for(std::chrono::seconds(1));
    }
}
 
void PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_processingtimemsTriggered()
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    auto send = m_interface->planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_processingtimems.Send(m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_processingtimemsData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_processingtimemsTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_processingtimemsTriggered::Send::" << send.Error().Message();
    }
}
 
void PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_processingtimemsTriggered(const oss::srv::PO2MVP::skeleton::events::planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_processingtimems::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_processingtimemsData = data;
    auto send = m_interface->planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_processingtimems.Send(m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_processingtimemsData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_processingtimemsTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_debug_processingtimemsTriggered::Send::" << send.Error().Message();
    }
}
 
void PPort_PO2MVP::WriteDataplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_trajectory(const oss::srv::PO2MVP::skeleton::events::planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_trajectory::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_trajectoryData = data;
}
 
void PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_trajectoryCyclic()
{
    while (m_running)
    {
        {
            std::lock_guard<std::mutex> lock(m_mutex);
            
            auto send = m_interface->planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_trajectory.Send(m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_trajectoryData);
            if (send.HasValue())
            {
                m_logger.LogVerbose() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_trajectoryCyclic::Send";
            }
            else
            {
                m_logger.LogError() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_trajectoryCyclic::Send::" << send.Error().Message();
            }
        }
        std::this_thread::sleep_for(std::chrono::seconds(1));
    }
}
 
void PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_trajectoryTriggered()
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    auto send = m_interface->planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_trajectory.Send(m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_trajectoryData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_trajectoryTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_trajectoryTriggered::Send::" << send.Error().Message();
    }
}
 
void PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_trajectoryTriggered(const oss::srv::PO2MVP::skeleton::events::planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_trajectory::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_trajectoryData = data;
    auto send = m_interface->planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_trajectory.Send(m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_trajectoryData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_trajectoryTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_trajectoryTriggered::Send::" << send.Error().Message();
    }
}
 
void PPort_PO2MVP::WriteDataplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_virtualwall(const oss::srv::PO2MVP::skeleton::events::planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_virtualwall::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_virtualwallData = data;
}
 
void PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_virtualwallCyclic()
{
    while (m_running)
    {
        {
            std::lock_guard<std::mutex> lock(m_mutex);
            
            auto send = m_interface->planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_virtualwall.Send(m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_virtualwallData);
            if (send.HasValue())
            {
                m_logger.LogVerbose() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_virtualwallCyclic::Send";
            }
            else
            {
                m_logger.LogError() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_virtualwallCyclic::Send::" << send.Error().Message();
            }
        }
        std::this_thread::sleep_for(std::chrono::seconds(1));
    }
}
 
void PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_virtualwallTriggered()
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    auto send = m_interface->planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_virtualwall.Send(m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_virtualwallData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_virtualwallTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_virtualwallTriggered::Send::" << send.Error().Message();
    }
}
 
void PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_virtualwallTriggered(const oss::srv::PO2MVP::skeleton::events::planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_virtualwall::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_virtualwallData = data;
    auto send = m_interface->planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_virtualwall.Send(m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_virtualwallData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_virtualwallTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "PPort_PO2MVP::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_virtualwallTriggered::Send::" << send.Error().Message();
    }
}
 
} /// namespace port
} /// namespace aa
} /// namespace exe_pathoptimizer
 
/// EOF