///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : pport_po2pe.cpp
/// SOFTWARE COMPONENT NAME           : PPort_PO2PE
/// GENERATED DATE                    : 2025-12-05 12:02:34
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "exe_pathoptimizer/aa/port/pport_po2pe.h"
 
namespace oss
{
namespace srv
{
namespace PO2PE
{
namespace skeleton
{
 
PE_SI_pathoptimizerSkeletonImpl::PE_SI_pathoptimizerSkeletonImpl(ara::core::InstanceSpecifier instanceSpec, ara::com::MethodCallProcessingMode mode)
    : PE_SI_pathoptimizerSkeleton(instanceSpec, mode)
    , m_logger(ara::log::CreateLogger("PTOP", "PORT", ara::log::LogLevel::kVerbose))
{
}
 
} /// namespace skeleton
} /// namespace PO2PE
} /// namespace srv
} /// namespace oss

namespace exe_pathoptimizer
{
namespace aa
{
namespace port
{
 
PPort_PO2PE::PPort_PO2PE()
    : m_logger(ara::log::CreateLogger("PTOP", "PORT", ara::log::LogLevel::kVerbose))
    , m_running{false}
    , m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_trajectoryData{{{0, 0U}, "str_string"}, {{{0, 0U}, {{0.0, 0.0, 0.0}, {0.0, 0.0, 0.0, 0.0}}, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f}, {{0, 0U}, {{0.0, 0.0, 0.0}, {0.0, 0.0, 0.0, 0.0}}, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f}, {{0, 0U}, {{0.0, 0.0, 0.0}, {0.0, 0.0, 0.0, 0.0}}, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f}}}
{
}
 
PPort_PO2PE::~PPort_PO2PE()
{
}
 
void PPort_PO2PE::Start()
{
    m_logger.LogVerbose() << "PPort_PO2PE::Start";
    
    // construct skeleton
    ara::core::InstanceSpecifier specifier{"Exe_pathoptimizer/AA/PPort_PO2PE"};
    m_interface = std::make_unique<oss::srv::PO2PE::skeleton::PE_SI_pathoptimizerSkeletonImpl>(specifier);
    
    // offer service
    auto offer = m_interface->OfferService();
    if (offer.HasValue())
    {
        m_running = true;
        m_logger.LogVerbose() << "PPort_PO2PE::Start::OfferService";
    }
    else
    {
        m_running = false;
        m_logger.LogError() << "PPort_PO2PE::Start::OfferService::" << offer.Error().Message();
    }
}
 
void PPort_PO2PE::Terminate()
{
    m_logger.LogVerbose() << "PPort_PO2PE::Terminate";
    
    // stop port
    m_running = false;
    
    // stop offer service
    m_interface->StopOfferService();
    m_logger.LogVerbose() << "PPort_PO2PE::Terminate::StopOfferService";
}
 
void PPort_PO2PE::WriteDataplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_trajectory(const oss::srv::PO2PE::skeleton::events::planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_trajectory::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_trajectoryData = data;
}
 
void PPort_PO2PE::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_trajectoryCyclic()
{
    while (m_running)
    {
        {
            std::lock_guard<std::mutex> lock(m_mutex);
            
            auto send = m_interface->planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_trajectory.Send(m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_trajectoryData);
            if (send.HasValue())
            {
                m_logger.LogVerbose() << "PPort_PO2PE::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_trajectoryCyclic::Send";
            }
            else
            {
                m_logger.LogError() << "PPort_PO2PE::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_trajectoryCyclic::Send::" << send.Error().Message();
            }
        }
        std::this_thread::sleep_for(std::chrono::seconds(1));
    }
}
 
void PPort_PO2PE::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_trajectoryTriggered()
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    auto send = m_interface->planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_trajectory.Send(m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_trajectoryData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "PPort_PO2PE::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_trajectoryTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "PPort_PO2PE::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_trajectoryTriggered::Send::" << send.Error().Message();
    }
}
 
void PPort_PO2PE::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_trajectoryTriggered(const oss::srv::PO2PE::skeleton::events::planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_trajectory::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_trajectoryData = data;
    auto send = m_interface->planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_trajectory.Send(m_planning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_trajectoryData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "PPort_PO2PE::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_trajectoryTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "PPort_PO2PE::SendEventplanning_scenarioplanning_lanedriving_motionplanning_pathoptimizer_trajectoryTriggered::Send::" << send.Error().Message();
    }
}
 
} /// namespace port
} /// namespace aa
} /// namespace exe_pathoptimizer
 
/// EOF