///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, ARA::COM Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : impl_type_mapmetadata.h
/// IMPLEMENTATION DATA TYPE NAME     : MapMetaData
/// GENERATED DATE                    : 2025-12-08 15:30:03
///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// CAUTION!! AUTOMATICALLY GENERATED FILE - DO NOT EDIT                                                   
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_ARA_COM_GEN_OSS_TYPE_NAV_MSGS_MSG_CPP_IMPL_TYPE_MAPMETADATA_H
#define PARA_ARA_COM_GEN_OSS_TYPE_NAV_MSGS_MSG_CPP_IMPL_TYPE_MAPMETADATA_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// @uptrace{SWS_CM_00402}
#include <cstdint>
#include <ara/core/structure.h>

#include "oss/type/builtin_interfaces/msg/impl_type_time.h"
#include "oss/type/geometry_msgs/msg/impl_type_pose.h"
#ifdef PARA_DDS_IMPLEMENTATION
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION FOR DDS
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "impl_type_mapmetadata.hpp"
#endif /// PARA_DDS_IMPLEMENTATION
/// @uptrace{SWS_CM_10375}
namespace oss
{
namespace type
{
namespace nav_msgs
{
namespace msg
{
struct MapMetaData
{
    oss::type::builtin_interfaces::msg::Time map_load_time;
    float resolution;
    std::uint32_t width;
    std::uint32_t height;
    oss::type::geometry_msgs::msg::Pose origin;

    /// @brief constructor
    MapMetaData() = default;
    MapMetaData(const oss::type::builtin_interfaces::msg::Time& _map_load_time, const float& _resolution, const std::uint32_t& _width, const std::uint32_t& _height, const oss::type::geometry_msgs::msg::Pose& _origin)
        : map_load_time{_map_load_time}
        , resolution{_resolution}
        , width{_width}
        , height{_height}
        , origin{_origin}
    {
    }

    /// @note marker for serialize, don't touch
    PARA_STRUCTURE(MapMetaData, map_load_time, resolution, width, height, origin);
};
 
#ifdef PARA_DDS_IMPLEMENTATION
inline dds::oss::type::nav_msgs::msg::MapMetaData MapMetaData_ConvertToDdsType(const oss::type::nav_msgs::msg::MapMetaData& src)
{
    dds::oss::type::nav_msgs::msg::MapMetaData dst;
    dst.map_load_time() = oss::type::builtin_interfaces::msg::Time_ConvertToDdsType(src.map_load_time);
    dst.resolution() = src.resolution;
    dst.width() = src.width;
    dst.height() = src.height;
    dst.origin() = oss::type::geometry_msgs::msg::Pose_ConvertToDdsType(src.origin);
    return dst;
}
 
inline oss::type::nav_msgs::msg::MapMetaData MapMetaData_ConvertFromDdsType(const dds::oss::type::nav_msgs::msg::MapMetaData& src)
{
    oss::type::nav_msgs::msg::MapMetaData dst;
    dst.map_load_time = oss::type::builtin_interfaces::msg::Time_ConvertFromDdsType(src.map_load_time());
    dst.resolution = src.resolution();
    dst.width = src.width();
    dst.height = src.height();
    dst.origin = oss::type::geometry_msgs::msg::Pose_ConvertFromDdsType(src.origin());
    return dst;
}
#endif /// PARA_DDS_IMPLEMENTATION
} /// namespace msg
} /// namespace nav_msgs
} /// namespace type
} /// namespace oss
#endif /// PARA_ARA_COM_GEN_OSS_TYPE_NAV_MSGS_MSG_CPP_IMPL_TYPE_MAPMETADATA_H