///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : pport_ocp2ss.cpp
/// SOFTWARE COMPONENT NAME           : PPort_OCP2SS
/// GENERATED DATE                    : 2025-12-12 16:18:12
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "exe_obstaclecruiseplanner/aa/port/pport_ocp2ss.h"
 
namespace oss
{
namespace srv
{
namespace OCP2SS
{
namespace skeleton
{
 
SS_SI_obstaclecruiseplannerSkeletonImpl::SS_SI_obstaclecruiseplannerSkeletonImpl(ara::core::InstanceSpecifier instanceSpec, ara::com::MethodCallProcessingMode mode)
    : SS_SI_obstaclecruiseplannerSkeleton(instanceSpec, mode)
    , m_logger(ara::log::CreateLogger("OCPL", "PORT", ara::log::LogLevel::kVerbose))
{
}
 
} /// namespace skeleton
} /// namespace OCP2SS
} /// namespace srv
} /// namespace oss

namespace exe_obstaclecruiseplanner
{
namespace aa
{
namespace port
{
 
PPort_OCP2SS::PPort_OCP2SS()
    : m_logger(ara::log::CreateLogger("OCPL", "PORT", ara::log::LogLevel::kVerbose))
    , m_running{false}
    , m_planning_scenarioplanning_lanedriving_trajectoryData{{{0, 0U}, "str_string"}, {{{0, 0U}, {{0.0, 0.0, 0.0}, {0.0, 0.0, 0.0, 0.0}}, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f}, {{0, 0U}, {{0.0, 0.0, 0.0}, {0.0, 0.0, 0.0, 0.0}}, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f}, {{0, 0U}, {{0.0, 0.0, 0.0}, {0.0, 0.0, 0.0, 0.0}}, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f}}}
{
}
 
PPort_OCP2SS::~PPort_OCP2SS()
{
}
 
void PPort_OCP2SS::Start()
{
    m_logger.LogVerbose() << "PPort_OCP2SS::Start";
    
    // construct skeleton
    ara::core::InstanceSpecifier specifier{"Exe_obstaclecruiseplanner/AA/PPort_OCP2SS"};
    m_interface = std::make_unique<oss::srv::OCP2SS::skeleton::SS_SI_obstaclecruiseplannerSkeletonImpl>(specifier);
    
    // offer service
    auto offer = m_interface->OfferService();
    if (offer.HasValue())
    {
        m_running = true;
        m_logger.LogVerbose() << "PPort_OCP2SS::Start::OfferService";
    }
    else
    {
        m_running = false;
        m_logger.LogError() << "PPort_OCP2SS::Start::OfferService::" << offer.Error().Message();
    }
}
 
void PPort_OCP2SS::Terminate()
{
    m_logger.LogVerbose() << "PPort_OCP2SS::Terminate";
    
    // stop port
    m_running = false;
    
    // stop offer service
    m_interface->StopOfferService();
    m_logger.LogVerbose() << "PPort_OCP2SS::Terminate::StopOfferService";
}
 
void PPort_OCP2SS::WriteDataplanning_scenarioplanning_lanedriving_trajectory(const oss::srv::OCP2SS::skeleton::events::planning_scenarioplanning_lanedriving_trajectory::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    m_planning_scenarioplanning_lanedriving_trajectoryData = data;
}
 
void PPort_OCP2SS::SendEventplanning_scenarioplanning_lanedriving_trajectoryCyclic()
{
    while (m_running)
    {
        {
            std::lock_guard<std::mutex> lock(m_mutex);
            
            auto send = m_interface->planning_scenarioplanning_lanedriving_trajectory.Send(m_planning_scenarioplanning_lanedriving_trajectoryData);
            if (send.HasValue())
            {
                m_logger.LogVerbose() << "PPort_OCP2SS::SendEventplanning_scenarioplanning_lanedriving_trajectoryCyclic::Send";
            }
            else
            {
                m_logger.LogError() << "PPort_OCP2SS::SendEventplanning_scenarioplanning_lanedriving_trajectoryCyclic::Send::" << send.Error().Message();
            }
        }
        std::this_thread::sleep_for(std::chrono::seconds(1));
    }
}
 
void PPort_OCP2SS::SendEventplanning_scenarioplanning_lanedriving_trajectoryTriggered()
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    auto send = m_interface->planning_scenarioplanning_lanedriving_trajectory.Send(m_planning_scenarioplanning_lanedriving_trajectoryData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "PPort_OCP2SS::SendEventplanning_scenarioplanning_lanedriving_trajectoryTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "PPort_OCP2SS::SendEventplanning_scenarioplanning_lanedriving_trajectoryTriggered::Send::" << send.Error().Message();
    }
}
 
void PPort_OCP2SS::SendEventplanning_scenarioplanning_lanedriving_trajectoryTriggered(const oss::srv::OCP2SS::skeleton::events::planning_scenarioplanning_lanedriving_trajectory::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    
    m_planning_scenarioplanning_lanedriving_trajectoryData = data;
    auto send = m_interface->planning_scenarioplanning_lanedriving_trajectory.Send(m_planning_scenarioplanning_lanedriving_trajectoryData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "PPort_OCP2SS::SendEventplanning_scenarioplanning_lanedriving_trajectoryTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "PPort_OCP2SS::SendEventplanning_scenarioplanning_lanedriving_trajectoryTriggered::Send::" << send.Error().Message();
    }
}
 
} /// namespace port
} /// namespace aa
} /// namespace exe_obstaclecruiseplanner
 
/// EOF