///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, ARA::COM Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : impl_type_accelwithcovariancestamped.h
/// IMPLEMENTATION DATA TYPE NAME     : AccelWithCovarianceStamped
/// GENERATED DATE                    : 2025-12-02 18:57:09
///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// CAUTION!! AUTOMATICALLY GENERATED FILE - DO NOT EDIT                                                   
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_ARA_COM_GEN_OSS_TYPE_GEOMETRY_MSGS_MSG_CPP_IMPL_TYPE_ACCELWITHCOVARIANCESTAMPED_H
#define PARA_ARA_COM_GEN_OSS_TYPE_GEOMETRY_MSGS_MSG_CPP_IMPL_TYPE_ACCELWITHCOVARIANCESTAMPED_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// @uptrace{SWS_CM_00402}
#include <ara/core/structure.h>
#include "oss/type/geometry_msgs/msg/impl_type_accelwithcovariance.h"
#include "oss/type/std_msgs/msg/impl_type_header.h"
#ifdef PARA_DDS_IMPLEMENTATION
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION FOR DDS
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "impl_type_accelwithcovariancestamped.hpp"
#endif /// PARA_DDS_IMPLEMENTATION
/// @uptrace{SWS_CM_10375}
namespace oss
{
namespace type
{
namespace geometry_msgs
{
namespace msg
{
struct AccelWithCovarianceStamped
{
    oss::type::std_msgs::msg::Header header;
    oss::type::geometry_msgs::msg::AccelWithCovariance accel;

    /// @brief constructor
    AccelWithCovarianceStamped() = default;
    AccelWithCovarianceStamped(const oss::type::std_msgs::msg::Header& _header, const oss::type::geometry_msgs::msg::AccelWithCovariance& _accel)
        : header{_header}
        , accel{_accel}
    {
    }

    /// @note marker for serialize, don't touch
    PARA_STRUCTURE(AccelWithCovarianceStamped, header, accel);
};
 
#ifdef PARA_DDS_IMPLEMENTATION
inline dds::oss::type::geometry_msgs::msg::AccelWithCovarianceStamped AccelWithCovarianceStamped_ConvertToDdsType(const oss::type::geometry_msgs::msg::AccelWithCovarianceStamped& src)
{
    dds::oss::type::geometry_msgs::msg::AccelWithCovarianceStamped dst;
    dst.header() = oss::type::std_msgs::msg::Header_ConvertToDdsType(src.header);
    dst.accel() = oss::type::geometry_msgs::msg::AccelWithCovariance_ConvertToDdsType(src.accel);
    return dst;
}
 
inline oss::type::geometry_msgs::msg::AccelWithCovarianceStamped AccelWithCovarianceStamped_ConvertFromDdsType(const dds::oss::type::geometry_msgs::msg::AccelWithCovarianceStamped& src)
{
    oss::type::geometry_msgs::msg::AccelWithCovarianceStamped dst;
    dst.header = oss::type::std_msgs::msg::Header_ConvertFromDdsType(src.header());
    dst.accel = oss::type::geometry_msgs::msg::AccelWithCovariance_ConvertFromDdsType(src.accel());
    return dst;
}
#endif /// PARA_DDS_IMPLEMENTATION
} /// namespace msg
} /// namespace geometry_msgs
} /// namespace type
} /// namespace oss
#endif /// PARA_ARA_COM_GEN_OSS_TYPE_GEOMETRY_MSGS_MSG_CPP_IMPL_TYPE_ACCELWITHCOVARIANCESTAMPED_H