///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, ARA::COM Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : impl_type_predictedpath.h
/// IMPLEMENTATION DATA TYPE NAME     : PredictedPath
/// GENERATED DATE                    : 2025-12-08 15:30:04
///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// CAUTION!! AUTOMATICALLY GENERATED FILE - DO NOT EDIT                                                   
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_ARA_COM_GEN_OSS_TYPE_AUTOWARE_PERCEPTION_MSGS_MSG_CPP_IMPL_TYPE_PREDICTEDPATH_H
#define PARA_ARA_COM_GEN_OSS_TYPE_AUTOWARE_PERCEPTION_MSGS_MSG_CPP_IMPL_TYPE_PREDICTEDPATH_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// @uptrace{SWS_CM_00402}
#include <ara/core/structure.h>

#include "oss/type/builtin_interfaces/msg/impl_type_duration.h"
#include "oss/type/impl_type_pose_vector.h"
#ifdef PARA_DDS_IMPLEMENTATION
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION FOR DDS
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "impl_type_predictedpath.hpp"
#endif /// PARA_DDS_IMPLEMENTATION
/// @uptrace{SWS_CM_10375}
namespace oss
{
namespace type
{
namespace autoware_perception_msgs
{
namespace msg
{
struct PredictedPath
{
    oss::type::Pose_Vector path;
    oss::type::builtin_interfaces::msg::Duration time_step;
    float confidence;

    /// @brief constructor
    PredictedPath() = default;
    PredictedPath(const oss::type::Pose_Vector& _path, const oss::type::builtin_interfaces::msg::Duration& _time_step, const float& _confidence)
        : path{_path}
        , time_step{_time_step}
        , confidence{_confidence}
    {
    }

    /// @note marker for serialize, don't touch
    PARA_STRUCTURE(PredictedPath, path, time_step, confidence);
};
 
#ifdef PARA_DDS_IMPLEMENTATION
inline dds::oss::type::autoware_perception_msgs::msg::PredictedPath PredictedPath_ConvertToDdsType(const oss::type::autoware_perception_msgs::msg::PredictedPath& src)
{
    dds::oss::type::autoware_perception_msgs::msg::PredictedPath dst;
    dst.path() = oss::type::Pose_Vector_ConvertToDdsType(src.path);
    dst.time_step() = oss::type::builtin_interfaces::msg::Duration_ConvertToDdsType(src.time_step);
    dst.confidence() = src.confidence;
    return dst;
}
 
inline oss::type::autoware_perception_msgs::msg::PredictedPath PredictedPath_ConvertFromDdsType(const dds::oss::type::autoware_perception_msgs::msg::PredictedPath& src)
{
    oss::type::autoware_perception_msgs::msg::PredictedPath dst;
    dst.path = oss::type::Pose_Vector_ConvertFromDdsType(src.path());
    dst.time_step = oss::type::builtin_interfaces::msg::Duration_ConvertFromDdsType(src.time_step());
    dst.confidence = src.confidence();
    return dst;
}
#endif /// PARA_DDS_IMPLEMENTATION
} /// namespace msg
} /// namespace autoware_perception_msgs
} /// namespace type
} /// namespace oss
#endif /// PARA_ARA_COM_GEN_OSS_TYPE_AUTOWARE_PERCEPTION_MSGS_MSG_CPP_IMPL_TYPE_PREDICTEDPATH_H