///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : rport_mp2scr.h
/// SOFTWARE COMPONENT NAME           : RPort_MP2SCr
/// GENERATED DATE                    : 2025-12-12 16:18:09
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_AA_GEN_SOFTWARE_COMPONENT_RPORT_EXE_SERVICECREATOR_AA_RPORT_MP2SCR_H
#define PARA_AA_GEN_SOFTWARE_COMPONENT_RPORT_EXE_SERVICECREATOR_AA_RPORT_MP2SCR_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "oss/srv/MP2SCr/scr_si_missionplanner_proxy.h"
 
#include "ara/log/logger.h"
 
#include <mutex>
#include <thread>
 
namespace exe_servicecreator
{
namespace aa
{
namespace port
{
 
class RPort_MP2SCr
{
public:
    /// @brief Constructor
    RPort_MP2SCr();
    
    /// @brief Destructor
    ~RPort_MP2SCr();
    
    /// @brief Start port
    void Start();
    
    /// @brief Terminate port
    void Terminate();

    /// @brief Request with Response method using by software component, planning_missionplanning_missionplanner_clearroute
    void Requestplanning_missionplanning_missionplanner_clearroute();
     
    /// @brief Regist callback from software component
    void RegistResponseHandlerplanning_missionplanning_missionplanner_clearroute(std::function<void(const oss::srv::MP2SCr::proxy::methods::planning_missionplanning_missionplanner_clearroute::Output&)> handler);
    
    /// @brief Request with Response method using by software component, planning_missionplanning_missionplanner_setlaneletroute
    void Requestplanning_missionplanning_missionplanner_setlaneletroute(const oss::type::tier4_planning_msgs::srv::SetLaneletRoute_Request& req);
     
    /// @brief Regist callback from software component
    void RegistResponseHandlerplanning_missionplanning_missionplanner_setlaneletroute(std::function<void(const oss::srv::MP2SCr::proxy::methods::planning_missionplanning_missionplanner_setlaneletroute::Output&)> handler);
    
    /// @brief Request with Response method using by software component, planning_missionplanning_missionplanner_setwaypointroute
    void Requestplanning_missionplanning_missionplanner_setwaypointroute(const oss::type::tier4_planning_msgs::srv::SetWaypointRoute_Request& req);
     
    /// @brief Regist callback from software component
    void RegistResponseHandlerplanning_missionplanning_missionplanner_setwaypointroute(std::function<void(const oss::srv::MP2SCr::proxy::methods::planning_missionplanning_missionplanner_setwaypointroute::Output&)> handler);
    
private:
    /// @brief Callback for find service
    void Find(ara::com::ServiceHandleContainer<oss::srv::MP2SCr::proxy::SCr_SI_missionplannerProxy::HandleType> handles,
              ara::com::FindServiceHandle findHandle);

private:
    /// @brief Logger for this port
    ara::log::Logger& m_logger;
    
    /// @brief Flag of port status
    bool m_running;
    
    /// @brief Flag of find service status
    bool m_found;
    
    /// @brief Mutex for this port
    std::mutex m_mutex; 
    
    /// @brief AUTOSAR Port Interface
    std::unique_ptr<oss::srv::MP2SCr::proxy::SCr_SI_missionplannerProxy> m_interface;
    
    /// @brief Find service handle
    std::unique_ptr<ara::com::FindServiceHandle> m_findHandle;

    /// @brief Callback from software component, planning_missionplanning_missionplanner_clearroute
    std::function<void(const oss::srv::MP2SCr::proxy::methods::planning_missionplanning_missionplanner_clearroute::Output&)> m_responderplanning_missionplanning_missionplanner_clearroute;
    
    /// @brief Callback from software component, planning_missionplanning_missionplanner_setlaneletroute
    std::function<void(const oss::srv::MP2SCr::proxy::methods::planning_missionplanning_missionplanner_setlaneletroute::Output&)> m_responderplanning_missionplanning_missionplanner_setlaneletroute;
    
    /// @brief Callback from software component, planning_missionplanning_missionplanner_setwaypointroute
    std::function<void(const oss::srv::MP2SCr::proxy::methods::planning_missionplanning_missionplanner_setwaypointroute::Output&)> m_responderplanning_missionplanning_missionplanner_setwaypointroute;
};
 
} /// namespace port
} /// namespace aa
} /// namespace exe_servicecreator
 
#endif /// PARA_AA_GEN_SOFTWARE_COMPONENT_RPORT_EXE_SERVICECREATOR_AA_RPORT_MP2SCR_H