///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : rport_ocp2scr.h
/// SOFTWARE COMPONENT NAME           : RPort_OCP2SCr
/// GENERATED DATE                    : 2025-12-12 16:18:09
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_AA_GEN_SOFTWARE_COMPONENT_RPORT_EXE_SERVICECREATOR_AA_RPORT_OCP2SCR_H
#define PARA_AA_GEN_SOFTWARE_COMPONENT_RPORT_EXE_SERVICECREATOR_AA_RPORT_OCP2SCR_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "oss/srv/OCP2SCr/scr_si_obstaclecruiseplanner_proxy.h"
 
#include "ara/log/logger.h"
 
#include <mutex>
#include <thread>
 
namespace exe_servicecreator
{
namespace aa
{
namespace port
{
 
class RPort_OCP2SCr
{
public:
    /// @brief Constructor
    RPort_OCP2SCr();
    
    /// @brief Destructor
    ~RPort_OCP2SCr();
    
    /// @brief Start port
    void Start();
    
    /// @brief Terminate port
    void Terminate();
    
    /// @brief Subscribe event, trajectory
    void Subscribetrajectory();
     
    /// @brief Stop event subscription, trajectory
    void StopSubscribetrajectory();
     
    /// @brief Event receive handler, trajectory
    void ReceiveEventtrajectoryTriggered();
     
    /// @brief Event receive handler, trajectory
    void ReceiveEventtrajectoryCyclic();
     
    /// @brief Read event data, trajectory
    void ReadDatatrajectory(ara::com::SamplePtr<oss::srv::OCP2SCr::proxy::events::trajectory::SampleType const> samplePtr);
     
    /// @brief Regist callback from software component
    void RegistEventHandlertrajectory(std::function<void(const oss::srv::OCP2SCr::proxy::events::trajectory::SampleType&)> handler);
    
    /// @brief Subscribe event, scenario
    void Subscribescenario();
     
    /// @brief Stop event subscription, scenario
    void StopSubscribescenario();
     
    /// @brief Event receive handler, scenario
    void ReceiveEventscenarioTriggered();
     
    /// @brief Event receive handler, scenario
    void ReceiveEventscenarioCyclic();
     
    /// @brief Read event data, scenario
    void ReadDatascenario(ara::com::SamplePtr<oss::srv::OCP2SCr::proxy::events::scenario::SampleType const> samplePtr);
     
    /// @brief Regist callback from software component
    void RegistEventHandlerscenario(std::function<void(const oss::srv::OCP2SCr::proxy::events::scenario::SampleType&)> handler);

private:
    /// @brief Callback for find service
    void Find(ara::com::ServiceHandleContainer<oss::srv::OCP2SCr::proxy::SCr_SI_obstaclecruiseplannerProxy::HandleType> handles,
              ara::com::FindServiceHandle findHandle);
    
    /// @brief Callback for event receiver, trajectory
    void RegistReceivertrajectory();
    
    /// @brief Callback for event receiver, scenario
    void RegistReceiverscenario();

private:
    /// @brief Logger for this port
    ara::log::Logger& m_logger;
    
    /// @brief Flag of port status
    bool m_running;
    
    /// @brief Flag of find service status
    bool m_found;
    
    /// @brief Mutex for this port
    std::mutex m_mutex; 
    
    /// @brief AUTOSAR Port Interface
    std::unique_ptr<oss::srv::OCP2SCr::proxy::SCr_SI_obstaclecruiseplannerProxy> m_interface;
    
    /// @brief Find service handle
    std::unique_ptr<ara::com::FindServiceHandle> m_findHandle;
    
    /// @brief Callback from software component, trajectory
    std::function<void(const oss::srv::OCP2SCr::proxy::events::trajectory::SampleType&)> m_receivertrajectory;
    
    /// @brief Callback from software component, scenario
    std::function<void(const oss::srv::OCP2SCr::proxy::events::scenario::SampleType&)> m_receiverscenario;

};
 
} /// namespace port
} /// namespace aa
} /// namespace exe_servicecreator
 
#endif /// PARA_AA_GEN_SOFTWARE_COMPONENT_RPORT_EXE_SERVICECREATOR_AA_RPORT_OCP2SCR_H