///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : swc_elasticbandsmoother.h
/// SOFTWARE COMPONENT NAME           : Swc_elasticbandsmoother
/// GENERATED DATE                    : 2025-12-05 12:02:34
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_AA_GEN_SOFTWARE_COMPONENT_EXE_ELASTICBANDSMOOTHER_AA_H
#define PARA_AA_GEN_SOFTWARE_COMPONENT_EXE_ELASTICBANDSMOOTHER_AA_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "exe_elasticbandsmoother/aa/port/pport_ebs2po.h"
#include "exe_elasticbandsmoother/aa/port/rport_bvp2ebs.h"
#include "exe_elasticbandsmoother/aa/port/rport_scr2ebs.h"
 
#include "ara/log/logger.h"
#include "para/swc/port_pool.h"
 
namespace exe_elasticbandsmoother
{
namespace aa
{
 
class Swc_elasticbandsmoother
{
public:
    /// @brief Constructor
    Swc_elasticbandsmoother();
    
    /// @brief Destructor
    ~Swc_elasticbandsmoother();
    
    /// @brief Initialize software component
    bool Initialize();
    
    /// @brief Start software component
    void Start();
    
    /// @brief Terminate software component
    void Terminate();
    
    /// @brief Run software component
    void Run();
    
private:
    /// @brief Running status of software component
    bool m_running;
    
    /// @brief Pool of port
    ::para::swc::PortPool m_workers;
    
    /// @brief Logger for software component
    ara::log::Logger& m_logger;
    
    /// @brief Instance of Port {Swc_elasticbandsmoother.PPort_EBS2PO}
    std::unique_ptr<exe_elasticbandsmoother::aa::port::PPort_EBS2PO> m_PPort_EBS2PO;
    
    /// @brief Instance of Port {Swc_elasticbandsmoother.RPort_BVP2EBS}
    std::unique_ptr<exe_elasticbandsmoother::aa::port::RPort_BVP2EBS> m_RPort_BVP2EBS;
    
    /// @brief Instance of Port {Swc_elasticbandsmoother.RPort_SCr2EBS}
    std::unique_ptr<exe_elasticbandsmoother::aa::port::RPort_SCr2EBS> m_RPort_SCr2EBS;
};
 
} /// namespace aa
} /// namespace exe_elasticbandsmoother
 
#endif /// PARA_AA_GEN_SOFTWARE_COMPONENT_EXE_ELASTICBANDSMOOTHER_AA_H