///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, ARA::COM Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : scr_si_missionplanner_skeleton.h
/// SERVICE INTERFACE NAME            : SCr_SI_missionplanner
/// GENERATED DATE                    : 2025-12-12 16:16:54
///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// CAUTION!! AUTOMATICALLY GENERATED FILE - DO NOT EDIT                                                   
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_COM_GEN_OSS_SRV_MP2SCR_SERVICE_INTERFACE_SCR_SI_MISSIONPLANNER_SKELETON_H
#define PARA_COM_GEN_OSS_SRV_MP2SCR_SERVICE_INTERFACE_SCR_SI_MISSIONPLANNER_SKELETON_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// @uptrace{SWS_CM_01004}
#include "scr_si_missionplanner_common.h"
#include "para/com/skeleton/skeleton_interface.h"
/// @uptrace{SWS_CM_01005}
namespace oss
{
namespace srv
{
namespace MP2SCr
{
/// @uptrace{SWS_CM_01006}
namespace skeleton
{
class SCr_SI_missionplannerSkeleton;
/// @uptrace{SWS_CM_01009}
namespace events
{
} /// namespace events
/// @uptrace{SWS_CM_01031}
namespace fields
{
} /// namespace fields
/// @uptrace{SWS_CM_00002}
class SCr_SI_missionplannerSkeleton
{
public:
    /// @uptrace{SWS_CM_00191}
    struct planning_missionplanning_missionplanner_clearrouteOutput
    {
        oss::type::autoware_adapi_v1_msgs::srv::ClearRoute_Response res;
    };
    struct planning_missionplanning_missionplanner_setlaneletrouteOutput
    {
        oss::type::tier4_planning_msgs::srv::SetLaneletRoute_Response res;
    };
    struct planning_missionplanning_missionplanner_setwaypointrouteOutput
    {
        oss::type::tier4_planning_msgs::srv::SetWaypointRoute_Response res;
    };
    /// @brief Constructor
    /// @uptrace{SWS_CM_00002, SWS_CM_00152}
    SCr_SI_missionplannerSkeleton(ara::core::InstanceSpecifier instanceSpec, ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent)
        : mInterface(std::make_unique<para::com::SkeletonInterface>(instanceSpec, mode))
        , mDdsInterface(std::make_unique<para::com::SkeletonDdsInterface>(instanceSpec, mode))
        , mProtocol(para::com::GetServiceProtocol(instanceSpec))
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_clearrouteCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_clearroute(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_setlaneletrouteCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_setlaneletroute(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_setwaypointrouteCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_setwaypointroute(data, token);
                });
                mInterface->SetE2EErrorHandler([this](const ara::com::e2e::E2EErrorDomain& errorCode, ara::com::e2e::DataID dataID, ara::com::e2e::MessageCounter messageCounter) {
                    E2EErrorHandler(errorCode, dataID, messageCounter);
                });
                break;
            }
            case para::com::ServiceProtocol::kIpc :
            {
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_clearrouteCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_clearroute(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_setlaneletrouteCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_setlaneletroute(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_setwaypointrouteCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_setwaypointroute(data, token);
                });
                mInterface->SetE2EErrorHandler([this](const ara::com::e2e::E2EErrorDomain& errorCode, ara::com::e2e::DataID dataID, ara::com::e2e::MessageCounter messageCounter) {
                    E2EErrorHandler(errorCode, dataID, messageCounter);
                });
                break;
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                mDdsInterface->CreateMethods<dds::oss::srv::MP2SCr::SCr_SI_missionplannerMethod_Request, dds::oss::srv::MP2SCr::SCr_SI_missionplannerMethod_Reply>();
                mDdsInterface->SetMethodCallHandler([this](dds::sub::AnyDataReader& reader) {
                    HandleDdsMethod(reader);
                });
                break;
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : break;
        }
    }
    /// @brief Destructor
    virtual ~SCr_SI_missionplannerSkeleton() = default;
    /// @brief Delete copy constructor
    /// @uptrace{SWS_CM_00134}
    SCr_SI_missionplannerSkeleton(const SCr_SI_missionplannerSkeleton& other) = delete;
    /// @brief Delete copy assignment
    /// @uptrace{SWS_CM_00134}
    SCr_SI_missionplannerSkeleton& operator=(const SCr_SI_missionplannerSkeleton& other) = delete;
    /// @brief Move constructor
    /// @uptrace{SWS_CM_00135}
    SCr_SI_missionplannerSkeleton(SCr_SI_missionplannerSkeleton&& other) noexcept
        : mInterface(std::move(other.mInterface))
        , mDdsInterface(std::move(other.mDdsInterface))
        , mProtocol(std::move(other.mProtocol))
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_clearrouteCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_clearroute(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_setlaneletrouteCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_setlaneletroute(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_setwaypointrouteCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_setwaypointroute(data, token);
                });
                mInterface->SetE2EErrorHandler([this](const ara::com::e2e::E2EErrorDomain& errorCode, ara::com::e2e::DataID dataID, ara::com::e2e::MessageCounter messageCounter) {
                    E2EErrorHandler(errorCode, dataID, messageCounter);
                });
            }
            case para::com::ServiceProtocol::kIpc :
            {
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_clearrouteCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_clearroute(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_setlaneletrouteCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_setlaneletroute(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_setwaypointrouteCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_setwaypointroute(data, token);
                });
                mInterface->SetE2EErrorHandler([this](const ara::com::e2e::E2EErrorDomain& errorCode, ara::com::e2e::DataID dataID, ara::com::e2e::MessageCounter messageCounter) {
                    E2EErrorHandler(errorCode, dataID, messageCounter);
                });
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                mDdsInterface->CreateMethods<dds::oss::srv::MP2SCr::SCr_SI_missionplannerMethod_Request, dds::oss::srv::MP2SCr::SCr_SI_missionplannerMethod_Reply>();
                mDdsInterface->SetMethodCallHandler([this](dds::sub::AnyDataReader& reader) {
                    HandleDdsMethod(reader);
                });
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : break;
        }
        other.mInterface.reset();
        other.mDdsInterface.reset();
    }
    /// @brief Move assignment
    /// @uptrace{SWS_CM_00135}
    SCr_SI_missionplannerSkeleton& operator=(SCr_SI_missionplannerSkeleton&& other) noexcept
    {
        mInterface = std::move(other.mInterface);
        mDdsInterface = std::move(other.mDdsInterface);
        mProtocol = std::move(other.mProtocol);
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_clearrouteCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_clearroute(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_setlaneletrouteCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_setlaneletroute(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_setwaypointrouteCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_setwaypointroute(data, token);
                });
                mInterface->SetE2EErrorHandler([this](const ara::com::e2e::E2EErrorDomain& errorCode, ara::com::e2e::DataID dataID, ara::com::e2e::MessageCounter messageCounter) {
                    E2EErrorHandler(errorCode, dataID, messageCounter);
                });
            }
            case para::com::ServiceProtocol::kIpc :
            {
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_clearrouteCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_clearroute(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_setlaneletrouteCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_setlaneletroute(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_setwaypointrouteCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_setwaypointroute(data, token);
                });
                mInterface->SetE2EErrorHandler([this](const ara::com::e2e::E2EErrorDomain& errorCode, ara::com::e2e::DataID dataID, ara::com::e2e::MessageCounter messageCounter) {
                    E2EErrorHandler(errorCode, dataID, messageCounter);
                });
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                mDdsInterface->CreateMethods<dds::oss::srv::MP2SCr::SCr_SI_missionplannerMethod_Request, dds::oss::srv::MP2SCr::SCr_SI_missionplannerMethod_Reply>();
                mDdsInterface->SetMethodCallHandler([this](dds::sub::AnyDataReader& reader) {
                    HandleDdsMethod(reader);
                });
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : break;
        }
        other.mInterface.reset();
        other.mDdsInterface.reset();
        return *this;
    }
    /// @brief Send "OfferService" message to Communication Management
    /// @uptrace{SWS_CM_00101}
    ara::core::Result<void> OfferService()
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                return mInterface->OfferService();
            }
            case para::com::ServiceProtocol::kIpc :
            {
            	return mInterface->OfferService();
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
            	return mDdsInterface->OfferService();
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : return ara::core::Result<void>(ara::com::ComErrc::kNetworkBindingFailure);
        }
    }
    /// @brief Send "StopOfferService" message to Communication Management
    /// @uptrace{SWS_CM_00111}
    void StopOfferService()
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                mInterface->StopOfferService();
                break;
            }
            case para::com::ServiceProtocol::kIpc :
            {
                mInterface->StopOfferService();
                break;
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                mDdsInterface->StopOfferService();
                break;
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : break;
        }
    }
    /// @brief Allows the implementation providing the service method to trigger the execution of the next service consumer method call at a specific point of time
    ///        if the processing mode is set to kPoll.
    /// @note This function requires that ara::com::MethodCallProcessingMode is configured as kPoll by constructor
    /// @uptrace{SWS_CM_00199}
    ara::core::Future<bool> ProcessNextMethodCall()
    {
        ara::core::Promise<bool> promise{};
        ara::core::Result<bool> ret{false};
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                ret = mInterface->ProcessNextMethodCall();
                break;
            }
            case para::com::ServiceProtocol::kIpc :
            {
                ret = mInterface->ProcessNextMethodCall();
                break;
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                ret = mDdsInterface->ProcessNextMethodCall();
                break;
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : break;
        }
        if (ret.HasValue())
        {
            promise.set_value(ret.Value());
        }
        else
        {
            promise.SetError(ret.Error());
        }
        return promise.get_future();
    }
    /// @brief In case the call to E2E_check indicated a failed E2E check of the request message, the server application can get notified via an E2E error handler.
    /// @uptrace{SWS_CM_10470}
    virtual void E2EErrorHandler(const ara::com::e2e::E2EErrorDomain& errorCode, ara::com::e2e::DataID dataID, ara::com::e2e::MessageCounter messageCounter)
    {
    }
    
private:
    std::unique_ptr<para::com::SkeletonInterface> mInterface;
    std::unique_ptr<para::com::SkeletonDdsInterface> mDdsInterface;
    para::com::ServiceProtocol mProtocol;
    
public:
    /// @brief Method, planning_missionplanning_missionplanner_clearroute
    /// @uptrace{SWS_CM_00191}
    virtual ara::core::Future<planning_missionplanning_missionplanner_clearrouteOutput> planning_missionplanning_missionplanner_clearroute() = 0;
    /// @brief Method, planning_missionplanning_missionplanner_setlaneletroute
    /// @uptrace{SWS_CM_00191}
    virtual ara::core::Future<planning_missionplanning_missionplanner_setlaneletrouteOutput> planning_missionplanning_missionplanner_setlaneletroute(const oss::type::tier4_planning_msgs::srv::SetLaneletRoute_Request& req) = 0;
    /// @brief Method, planning_missionplanning_missionplanner_setwaypointroute
    /// @uptrace{SWS_CM_00191}
    virtual ara::core::Future<planning_missionplanning_missionplanner_setwaypointrouteOutput> planning_missionplanning_missionplanner_setwaypointroute(const oss::type::tier4_planning_msgs::srv::SetWaypointRoute_Request& req) = 0;
    
private:
    void Handleplanning_missionplanning_missionplanner_clearroute(const std::vector<std::uint8_t>& data, const para::com::MethodToken token)
    {
        const para::serializer::TransformationProps props{};
        std::uint8_t retResult{1};
        std::vector<std::uint8_t> retData{};
        auto future = planning_missionplanning_missionplanner_clearroute();
        auto result = future.GetResult();
        if (result.HasValue())
        {
            planning_missionplanning_missionplanner_clearrouteOutput output = result.Value();
            para::serializer::Serializer serializer{};
            serializer.write(props, output.res);
            retData = serializer.ensure();
            retResult = 0;
        }
        else
        {
            para::serializer::ApplicationMethodErrorData errorData{result.Error().Domain().Id(), result.Error().Value()};
            para::serializer::ApplicationMethodError error;
            error = errorData;
            para::serializer::Serializer serializer{};
            serializer.write(para::serializer::Serializer::getApplicationMethodErrorProps(), error);
            retData = serializer.ensure();
            retResult = 1;
        }
        mInterface->ReturnMethod(kplanning_missionplanning_missionplanner_clearrouteCallSign, retResult, retData, token);
    }
    void Handleplanning_missionplanning_missionplanner_setlaneletroute(const std::vector<std::uint8_t>& data, const para::com::MethodToken token)
    {
        const para::serializer::TransformationProps props{};
        std::uint8_t retResult{1};
        std::vector<std::uint8_t> retData{};
        para::serializer::Deserializer deserializer{data};
        oss::type::tier4_planning_msgs::srv::SetLaneletRoute_Request _req_;
        deserializer.read(props, _req_);
        auto future = planning_missionplanning_missionplanner_setlaneletroute(_req_);
        auto result = future.GetResult();
        if (result.HasValue())
        {
            planning_missionplanning_missionplanner_setlaneletrouteOutput output = result.Value();
            para::serializer::Serializer serializer{};
            serializer.write(props, output.res);
            retData = serializer.ensure();
            retResult = 0;
        }
        else
        {
            para::serializer::ApplicationMethodErrorData errorData{result.Error().Domain().Id(), result.Error().Value()};
            para::serializer::ApplicationMethodError error;
            error = errorData;
            para::serializer::Serializer serializer{};
            serializer.write(para::serializer::Serializer::getApplicationMethodErrorProps(), error);
            retData = serializer.ensure();
            retResult = 1;
        }
        mInterface->ReturnMethod(kplanning_missionplanning_missionplanner_setlaneletrouteCallSign, retResult, retData, token);
    }
    void Handleplanning_missionplanning_missionplanner_setwaypointroute(const std::vector<std::uint8_t>& data, const para::com::MethodToken token)
    {
        const para::serializer::TransformationProps props{};
        std::uint8_t retResult{1};
        std::vector<std::uint8_t> retData{};
        para::serializer::Deserializer deserializer{data};
        oss::type::tier4_planning_msgs::srv::SetWaypointRoute_Request _req_;
        deserializer.read(props, _req_);
        auto future = planning_missionplanning_missionplanner_setwaypointroute(_req_);
        auto result = future.GetResult();
        if (result.HasValue())
        {
            planning_missionplanning_missionplanner_setwaypointrouteOutput output = result.Value();
            para::serializer::Serializer serializer{};
            serializer.write(props, output.res);
            retData = serializer.ensure();
            retResult = 0;
        }
        else
        {
            para::serializer::ApplicationMethodErrorData errorData{result.Error().Domain().Id(), result.Error().Value()};
            para::serializer::ApplicationMethodError error;
            error = errorData;
            para::serializer::Serializer serializer{};
            serializer.write(para::serializer::Serializer::getApplicationMethodErrorProps(), error);
            retData = serializer.ensure();
            retResult = 1;
        }
        mInterface->ReturnMethod(kplanning_missionplanning_missionplanner_setwaypointrouteCallSign, retResult, retData, token);
    }
    #ifdef PARA_DDS_IMPLEMENTATION
    void HandleDdsMethod(const dds::sub::AnyDataReader& reader)
    {
        dds::sub::DataReader<dds::oss::srv::MP2SCr::SCr_SI_missionplannerMethod_Request> _reader_ = reader;
        dds::sub::LoanedSamples<dds::oss::srv::MP2SCr::SCr_SI_missionplannerMethod_Request> _requests_;
        _requests_ = _reader_.take();
        for (auto& _request_ : _requests_)
        {
            if (_request_->info().valid())
            {
                auto _data_ = _request_.data().data();
                switch (_data_._d())
                {
                    case dds::oss::srv::MP2SCr::SCr_SI_missionplannerMethod_planning_missionplanning_missionplanner_clearroute_Hash :
                    {
                        Handleplanning_missionplanning_missionplanner_clearroute(_data_.planning_missionplanning_missionplanner_clearroute(), _request_.data().header());
                        break;
                    }
                    case dds::oss::srv::MP2SCr::SCr_SI_missionplannerMethod_planning_missionplanning_missionplanner_setlaneletroute_Hash :
                    {
                        Handleplanning_missionplanning_missionplanner_setlaneletroute(_data_.planning_missionplanning_missionplanner_setlaneletroute(), _request_.data().header());
                        break;
                    }
                    case dds::oss::srv::MP2SCr::SCr_SI_missionplannerMethod_planning_missionplanning_missionplanner_setwaypointroute_Hash :
                    {
                        Handleplanning_missionplanning_missionplanner_setwaypointroute(_data_.planning_missionplanning_missionplanner_setwaypointroute(), _request_.data().header());
                        break;
                    }
                    default : break;
                }
            }
        }
    }
    #endif /// PARA_DDS_IMPLEMENTATION
    #ifdef PARA_DDS_IMPLEMENTATION
    void Handleplanning_missionplanning_missionplanner_clearroute(const dds::oss::srv::MP2SCr::SCr_SI_missionplannerMethod_planning_missionplanning_missionplanner_clearroute_In& data, const dds::rpc::RequestHeader token)
    {
        dds::oss::srv::MP2SCr::SCr_SI_missionplannerMethod_planning_missionplanning_missionplanner_clearroute_Result _result_{};
        auto future = this->planning_missionplanning_missionplanner_clearroute();
        auto result = future.GetResult();
        if (result.HasValue())
        {
            dds::oss::srv::MP2SCr::SCr_SI_missionplannerMethod_planning_missionplanning_missionplanner_clearroute_Out _out_args_;
            _out_args_.res() = oss::type::autoware_adapi_v1_msgs::srv::ClearRoute_Response_ConvertToDdsType(result.Value().res);
            _result_.result(_out_args_, dds::RETCODE_OK);
        }
        else
        {
            dds::ara::core::ErrorCode _error_;
            _error_.error_code() = result.Error().Value();
            _error_.error_domain_value() = result.Error().Domain().Id();
            _result_.error(_error_, dds::RETCODE_ERROR);
        }
        dds::oss::srv::MP2SCr::SCr_SI_missionplannerMethod_Return _return_;
        _return_.planning_missionplanning_missionplanner_clearroute(_result_, dds::oss::srv::MP2SCr::SCr_SI_missionplannerMethod_planning_missionplanning_missionplanner_clearroute_Hash);
        dds::oss::srv::MP2SCr::SCr_SI_missionplannerMethod_Reply _reply_;
        _reply_.data() = _return_;
        _reply_.header() = mDdsInterface->GetReplyHeader(token);
        mDdsInterface->ReturnMethod<dds::oss::srv::MP2SCr::SCr_SI_missionplannerMethod_Reply>(_reply_);
    }
    #endif /// PARA_DDS_IMPLEMENTATION
    #ifdef PARA_DDS_IMPLEMENTATION
    void Handleplanning_missionplanning_missionplanner_setlaneletroute(const dds::oss::srv::MP2SCr::SCr_SI_missionplannerMethod_planning_missionplanning_missionplanner_setlaneletroute_In& data, const dds::rpc::RequestHeader token)
    {
        dds::oss::srv::MP2SCr::SCr_SI_missionplannerMethod_planning_missionplanning_missionplanner_setlaneletroute_Result _result_{};
        oss::type::tier4_planning_msgs::srv::SetLaneletRoute_Request _req = oss::type::tier4_planning_msgs::srv::SetLaneletRoute_Request_ConvertFromDdsType(data.req());
        auto future = this->planning_missionplanning_missionplanner_setlaneletroute(_req);
        auto result = future.GetResult();
        if (result.HasValue())
        {
            dds::oss::srv::MP2SCr::SCr_SI_missionplannerMethod_planning_missionplanning_missionplanner_setlaneletroute_Out _out_args_;
            _out_args_.res() = oss::type::tier4_planning_msgs::srv::SetLaneletRoute_Response_ConvertToDdsType(result.Value().res);
            _result_.result(_out_args_, dds::RETCODE_OK);
        }
        else
        {
            dds::ara::core::ErrorCode _error_;
            _error_.error_code() = result.Error().Value();
            _error_.error_domain_value() = result.Error().Domain().Id();
            _result_.error(_error_, dds::RETCODE_ERROR);
        }
        dds::oss::srv::MP2SCr::SCr_SI_missionplannerMethod_Return _return_;
        _return_.planning_missionplanning_missionplanner_setlaneletroute(_result_, dds::oss::srv::MP2SCr::SCr_SI_missionplannerMethod_planning_missionplanning_missionplanner_setlaneletroute_Hash);
        dds::oss::srv::MP2SCr::SCr_SI_missionplannerMethod_Reply _reply_;
        _reply_.data() = _return_;
        _reply_.header() = mDdsInterface->GetReplyHeader(token);
        mDdsInterface->ReturnMethod<dds::oss::srv::MP2SCr::SCr_SI_missionplannerMethod_Reply>(_reply_);
    }
    #endif /// PARA_DDS_IMPLEMENTATION
    #ifdef PARA_DDS_IMPLEMENTATION
    void Handleplanning_missionplanning_missionplanner_setwaypointroute(const dds::oss::srv::MP2SCr::SCr_SI_missionplannerMethod_planning_missionplanning_missionplanner_setwaypointroute_In& data, const dds::rpc::RequestHeader token)
    {
        dds::oss::srv::MP2SCr::SCr_SI_missionplannerMethod_planning_missionplanning_missionplanner_setwaypointroute_Result _result_{};
        oss::type::tier4_planning_msgs::srv::SetWaypointRoute_Request _req = oss::type::tier4_planning_msgs::srv::SetWaypointRoute_Request_ConvertFromDdsType(data.req());
        auto future = this->planning_missionplanning_missionplanner_setwaypointroute(_req);
        auto result = future.GetResult();
        if (result.HasValue())
        {
            dds::oss::srv::MP2SCr::SCr_SI_missionplannerMethod_planning_missionplanning_missionplanner_setwaypointroute_Out _out_args_;
            _out_args_.res() = oss::type::tier4_planning_msgs::srv::SetWaypointRoute_Response_ConvertToDdsType(result.Value().res);
            _result_.result(_out_args_, dds::RETCODE_OK);
        }
        else
        {
            dds::ara::core::ErrorCode _error_;
            _error_.error_code() = result.Error().Value();
            _error_.error_domain_value() = result.Error().Domain().Id();
            _result_.error(_error_, dds::RETCODE_ERROR);
        }
        dds::oss::srv::MP2SCr::SCr_SI_missionplannerMethod_Return _return_;
        _return_.planning_missionplanning_missionplanner_setwaypointroute(_result_, dds::oss::srv::MP2SCr::SCr_SI_missionplannerMethod_planning_missionplanning_missionplanner_setwaypointroute_Hash);
        dds::oss::srv::MP2SCr::SCr_SI_missionplannerMethod_Reply _reply_;
        _reply_.data() = _return_;
        _reply_.header() = mDdsInterface->GetReplyHeader(token);
        mDdsInterface->ReturnMethod<dds::oss::srv::MP2SCr::SCr_SI_missionplannerMethod_Reply>(_reply_);
    }
    #endif /// PARA_DDS_IMPLEMENTATION
    const std::string kplanning_missionplanning_missionplanner_clearrouteCallSign{"planning_missionplanning_missionplanner_clearroute"};
    const std::string kplanning_missionplanning_missionplanner_setlaneletrouteCallSign{"planning_missionplanning_missionplanner_setlaneletroute"};
    const std::string kplanning_missionplanning_missionplanner_setwaypointrouteCallSign{"planning_missionplanning_missionplanner_setwaypointroute"};
};
} /// namespace skeleton
} /// namespace MP2SCr
} /// namespace srv
} /// namespace oss
#endif /// PARA_COM_GEN_OSS_SRV_MP2SCR_SERVICE_INTERFACE_SCR_SI_MISSIONPLANNER_SKELETON_H