///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, ARA::COM Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : bpp_si_missionplanner_skeleton.h
/// SERVICE INTERFACE NAME            : BPP_SI_missionplanner
/// GENERATED DATE                    : 2025-12-02 18:57:07
///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// CAUTION!! AUTOMATICALLY GENERATED FILE - DO NOT EDIT                                                   
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_COM_GEN_OSS_SRV_MP2BPP_SERVICE_INTERFACE_BPP_SI_MISSIONPLANNER_SKELETON_H
#define PARA_COM_GEN_OSS_SRV_MP2BPP_SERVICE_INTERFACE_BPP_SI_MISSIONPLANNER_SKELETON_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// @uptrace{SWS_CM_01004}
#include "bpp_si_missionplanner_common.h"
#include "para/com/skeleton/skeleton_interface.h"
/// @uptrace{SWS_CM_01005}
namespace oss
{
namespace srv
{
namespace MP2BPP
{
/// @uptrace{SWS_CM_01006}
namespace skeleton
{
class BPP_SI_missionplannerSkeleton;
/// @uptrace{SWS_CM_01009}
namespace events
{
/// @uptrace{SWS_CM_00003}
class planning_missionplanning_missionplanner_debug_goalfootprint
{
public:
    /// @brief Type alias for type of event data
    /// @uptrace{SWS_CM_00162, SWS_CM_90437}
    using SampleType = oss::type::visualization_msgs::msg::MarkerArray;
    /// @brief Constructor
    explicit planning_missionplanning_missionplanner_debug_goalfootprint(para::com::SkeletonInterface* interface, para::com::SkeletonDdsInterface* ddsInterface, para::com::ServiceProtocol protocol)
        : mInterface(interface)
        , mDdsInterface(ddsInterface)
        , mProtocol(protocol)
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                break;
            }
            case para::com::ServiceProtocol::kIpc :
            {
                break;
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                mDdsInterface->CreateEvent<dds::oss::srv::MP2BPP::MarkerArrayEventType>(kCallSign);
                break;
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : break;
        }
    }
    /// @brief Destructor
    virtual ~planning_missionplanning_missionplanner_debug_goalfootprint() = default;
    /// @brief Delete copy constructor
    planning_missionplanning_missionplanner_debug_goalfootprint(const planning_missionplanning_missionplanner_debug_goalfootprint& other) = delete;
    /// @brief Delete copy assignment
    planning_missionplanning_missionplanner_debug_goalfootprint& operator=(const planning_missionplanning_missionplanner_debug_goalfootprint& other) = delete;
    /// @brief Move constructor
    planning_missionplanning_missionplanner_debug_goalfootprint(planning_missionplanning_missionplanner_debug_goalfootprint&& other) noexcept
        : mInterface(other.mInterface)
        , mDdsInterface(other.mDdsInterface)
        , mProtocol(other.mProtocol)
    {
    }
    /// @brief Move assignment
    planning_missionplanning_missionplanner_debug_goalfootprint& operator=(planning_missionplanning_missionplanner_debug_goalfootprint&& other) noexcept
    {
        mInterface = other.mInterface;
        mDdsInterface = other.mDdsInterface;
        mProtocol = other.mProtocol;
        return *this;
    }
    /// @brief Send event with data to subscribing service consumers
    /// @uptrace{SWS_CM_90437}
    ara::core::Result<void> Send(const SampleType& data)
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                const para::serializer::TransformationProps props{};
                para::serializer::Serializer serializer{};
                serializer.write(props, data);
                auto payload = serializer.ensure();
                return mInterface->SendEvent(kCallSign, payload);
            }
            case para::com::ServiceProtocol::kIpc :
            {
                const para::serializer::TransformationProps props{};
                para::serializer::Serializer serializer{};
                serializer.write(props, data);
                auto payload = serializer.ensure();
                return mInterface->SendEvent(kCallSign, payload);
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                dds::oss::srv::MP2BPP::MarkerArrayEventType _event_;
                _event_.instance_id() = mDdsInterface->GetInstanceId();
                _event_.data() = oss::type::visualization_msgs::msg::MarkerArray_ConvertToDdsType(data);
                return mDdsInterface->SendEvent<dds::oss::srv::MP2BPP::MarkerArrayEventType>(kCallSign, _event_);
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : return ara::core::Result<void>(ara::com::ComErrc::kNetworkBindingFailure);
        }
    }
    /// @brief Returns unique pointer about SampleType
    /// @uptrace{SWS_CM_90438}
    ara::core::Result<ara::com::SampleAllocateePtr<SampleType>> Allocate()
    {
        return std::make_unique<SampleType>();
    }
    
private:
    para::com::SkeletonInterface* mInterface;
    para::com::SkeletonDdsInterface* mDdsInterface;
    para::com::ServiceProtocol mProtocol;
    const std::string kCallSign = {"planning_missionplanning_missionplanner_debug_goalfootprint"};
};
/// @uptrace{SWS_CM_00003}
class planning_missionplanning_missionplanner_debug_processingtimems
{
public:
    /// @brief Type alias for type of event data
    /// @uptrace{SWS_CM_00162, SWS_CM_90437}
    using SampleType = oss::type::autoware_internal_debug_msgs::msg::Float64Stamped;
    /// @brief Constructor
    explicit planning_missionplanning_missionplanner_debug_processingtimems(para::com::SkeletonInterface* interface, para::com::SkeletonDdsInterface* ddsInterface, para::com::ServiceProtocol protocol)
        : mInterface(interface)
        , mDdsInterface(ddsInterface)
        , mProtocol(protocol)
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                break;
            }
            case para::com::ServiceProtocol::kIpc :
            {
                break;
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                mDdsInterface->CreateEvent<dds::oss::srv::MP2BPP::Float64StampedEventType>(kCallSign);
                break;
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : break;
        }
    }
    /// @brief Destructor
    virtual ~planning_missionplanning_missionplanner_debug_processingtimems() = default;
    /// @brief Delete copy constructor
    planning_missionplanning_missionplanner_debug_processingtimems(const planning_missionplanning_missionplanner_debug_processingtimems& other) = delete;
    /// @brief Delete copy assignment
    planning_missionplanning_missionplanner_debug_processingtimems& operator=(const planning_missionplanning_missionplanner_debug_processingtimems& other) = delete;
    /// @brief Move constructor
    planning_missionplanning_missionplanner_debug_processingtimems(planning_missionplanning_missionplanner_debug_processingtimems&& other) noexcept
        : mInterface(other.mInterface)
        , mDdsInterface(other.mDdsInterface)
        , mProtocol(other.mProtocol)
    {
    }
    /// @brief Move assignment
    planning_missionplanning_missionplanner_debug_processingtimems& operator=(planning_missionplanning_missionplanner_debug_processingtimems&& other) noexcept
    {
        mInterface = other.mInterface;
        mDdsInterface = other.mDdsInterface;
        mProtocol = other.mProtocol;
        return *this;
    }
    /// @brief Send event with data to subscribing service consumers
    /// @uptrace{SWS_CM_90437}
    ara::core::Result<void> Send(const SampleType& data)
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                const para::serializer::TransformationProps props{};
                para::serializer::Serializer serializer{};
                serializer.write(props, data);
                auto payload = serializer.ensure();
                return mInterface->SendEvent(kCallSign, payload);
            }
            case para::com::ServiceProtocol::kIpc :
            {
                const para::serializer::TransformationProps props{};
                para::serializer::Serializer serializer{};
                serializer.write(props, data);
                auto payload = serializer.ensure();
                return mInterface->SendEvent(kCallSign, payload);
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                dds::oss::srv::MP2BPP::Float64StampedEventType _event_;
                _event_.instance_id() = mDdsInterface->GetInstanceId();
                _event_.data() = oss::type::autoware_internal_debug_msgs::msg::Float64Stamped_ConvertToDdsType(data);
                return mDdsInterface->SendEvent<dds::oss::srv::MP2BPP::Float64StampedEventType>(kCallSign, _event_);
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : return ara::core::Result<void>(ara::com::ComErrc::kNetworkBindingFailure);
        }
    }
    /// @brief Returns unique pointer about SampleType
    /// @uptrace{SWS_CM_90438}
    ara::core::Result<ara::com::SampleAllocateePtr<SampleType>> Allocate()
    {
        return std::make_unique<SampleType>();
    }
    
private:
    para::com::SkeletonInterface* mInterface;
    para::com::SkeletonDdsInterface* mDdsInterface;
    para::com::ServiceProtocol mProtocol;
    const std::string kCallSign = {"planning_missionplanning_missionplanner_debug_processingtimems"};
};
/// @uptrace{SWS_CM_00003}
class planning_missionplanning_route
{
public:
    /// @brief Type alias for type of event data
    /// @uptrace{SWS_CM_00162, SWS_CM_90437}
    using SampleType = oss::type::autoware_planning_msgs::msg::LaneletRoute;
    /// @brief Constructor
    explicit planning_missionplanning_route(para::com::SkeletonInterface* interface, para::com::SkeletonDdsInterface* ddsInterface, para::com::ServiceProtocol protocol)
        : mInterface(interface)
        , mDdsInterface(ddsInterface)
        , mProtocol(protocol)
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                break;
            }
            case para::com::ServiceProtocol::kIpc :
            {
                break;
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                mDdsInterface->CreateEvent<dds::oss::srv::MP2BPP::LaneletRouteEventType>(kCallSign);
                break;
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : break;
        }
    }
    /// @brief Destructor
    virtual ~planning_missionplanning_route() = default;
    /// @brief Delete copy constructor
    planning_missionplanning_route(const planning_missionplanning_route& other) = delete;
    /// @brief Delete copy assignment
    planning_missionplanning_route& operator=(const planning_missionplanning_route& other) = delete;
    /// @brief Move constructor
    planning_missionplanning_route(planning_missionplanning_route&& other) noexcept
        : mInterface(other.mInterface)
        , mDdsInterface(other.mDdsInterface)
        , mProtocol(other.mProtocol)
    {
    }
    /// @brief Move assignment
    planning_missionplanning_route& operator=(planning_missionplanning_route&& other) noexcept
    {
        mInterface = other.mInterface;
        mDdsInterface = other.mDdsInterface;
        mProtocol = other.mProtocol;
        return *this;
    }
    /// @brief Send event with data to subscribing service consumers
    /// @uptrace{SWS_CM_90437}
    ara::core::Result<void> Send(const SampleType& data)
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                const para::serializer::TransformationProps props{};
                para::serializer::Serializer serializer{};
                serializer.write(props, data);
                auto payload = serializer.ensure();
                return mInterface->SendEvent(kCallSign, payload);
            }
            case para::com::ServiceProtocol::kIpc :
            {
                const para::serializer::TransformationProps props{};
                para::serializer::Serializer serializer{};
                serializer.write(props, data);
                auto payload = serializer.ensure();
                return mInterface->SendEvent(kCallSign, payload);
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                dds::oss::srv::MP2BPP::LaneletRouteEventType _event_;
                _event_.instance_id() = mDdsInterface->GetInstanceId();
                _event_.data() = oss::type::autoware_planning_msgs::msg::LaneletRoute_ConvertToDdsType(data);
                return mDdsInterface->SendEvent<dds::oss::srv::MP2BPP::LaneletRouteEventType>(kCallSign, _event_);
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : return ara::core::Result<void>(ara::com::ComErrc::kNetworkBindingFailure);
        }
    }
    /// @brief Returns unique pointer about SampleType
    /// @uptrace{SWS_CM_90438}
    ara::core::Result<ara::com::SampleAllocateePtr<SampleType>> Allocate()
    {
        return std::make_unique<SampleType>();
    }
    
private:
    para::com::SkeletonInterface* mInterface;
    para::com::SkeletonDdsInterface* mDdsInterface;
    para::com::ServiceProtocol mProtocol;
    const std::string kCallSign = {"planning_missionplanning_route"};
};
/// @uptrace{SWS_CM_00003}
class planning_missionplanning_routemarker
{
public:
    /// @brief Type alias for type of event data
    /// @uptrace{SWS_CM_00162, SWS_CM_90437}
    using SampleType = oss::type::visualization_msgs::msg::MarkerArray;
    /// @brief Constructor
    explicit planning_missionplanning_routemarker(para::com::SkeletonInterface* interface, para::com::SkeletonDdsInterface* ddsInterface, para::com::ServiceProtocol protocol)
        : mInterface(interface)
        , mDdsInterface(ddsInterface)
        , mProtocol(protocol)
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                break;
            }
            case para::com::ServiceProtocol::kIpc :
            {
                break;
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                mDdsInterface->CreateEvent<dds::oss::srv::MP2BPP::MarkerArrayEventType>(kCallSign);
                break;
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : break;
        }
    }
    /// @brief Destructor
    virtual ~planning_missionplanning_routemarker() = default;
    /// @brief Delete copy constructor
    planning_missionplanning_routemarker(const planning_missionplanning_routemarker& other) = delete;
    /// @brief Delete copy assignment
    planning_missionplanning_routemarker& operator=(const planning_missionplanning_routemarker& other) = delete;
    /// @brief Move constructor
    planning_missionplanning_routemarker(planning_missionplanning_routemarker&& other) noexcept
        : mInterface(other.mInterface)
        , mDdsInterface(other.mDdsInterface)
        , mProtocol(other.mProtocol)
    {
    }
    /// @brief Move assignment
    planning_missionplanning_routemarker& operator=(planning_missionplanning_routemarker&& other) noexcept
    {
        mInterface = other.mInterface;
        mDdsInterface = other.mDdsInterface;
        mProtocol = other.mProtocol;
        return *this;
    }
    /// @brief Send event with data to subscribing service consumers
    /// @uptrace{SWS_CM_90437}
    ara::core::Result<void> Send(const SampleType& data)
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                const para::serializer::TransformationProps props{};
                para::serializer::Serializer serializer{};
                serializer.write(props, data);
                auto payload = serializer.ensure();
                return mInterface->SendEvent(kCallSign, payload);
            }
            case para::com::ServiceProtocol::kIpc :
            {
                const para::serializer::TransformationProps props{};
                para::serializer::Serializer serializer{};
                serializer.write(props, data);
                auto payload = serializer.ensure();
                return mInterface->SendEvent(kCallSign, payload);
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                dds::oss::srv::MP2BPP::MarkerArrayEventType _event_;
                _event_.instance_id() = mDdsInterface->GetInstanceId();
                _event_.data() = oss::type::visualization_msgs::msg::MarkerArray_ConvertToDdsType(data);
                return mDdsInterface->SendEvent<dds::oss::srv::MP2BPP::MarkerArrayEventType>(kCallSign, _event_);
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : return ara::core::Result<void>(ara::com::ComErrc::kNetworkBindingFailure);
        }
    }
    /// @brief Returns unique pointer about SampleType
    /// @uptrace{SWS_CM_90438}
    ara::core::Result<ara::com::SampleAllocateePtr<SampleType>> Allocate()
    {
        return std::make_unique<SampleType>();
    }
    
private:
    para::com::SkeletonInterface* mInterface;
    para::com::SkeletonDdsInterface* mDdsInterface;
    para::com::ServiceProtocol mProtocol;
    const std::string kCallSign = {"planning_missionplanning_routemarker"};
};
/// @uptrace{SWS_CM_00003}
class planning_missionplanning_state
{
public:
    /// @brief Type alias for type of event data
    /// @uptrace{SWS_CM_00162, SWS_CM_90437}
    using SampleType = oss::type::tier4_planning_msgs::msg::RouteState;
    /// @brief Constructor
    explicit planning_missionplanning_state(para::com::SkeletonInterface* interface, para::com::SkeletonDdsInterface* ddsInterface, para::com::ServiceProtocol protocol)
        : mInterface(interface)
        , mDdsInterface(ddsInterface)
        , mProtocol(protocol)
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                break;
            }
            case para::com::ServiceProtocol::kIpc :
            {
                break;
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                mDdsInterface->CreateEvent<dds::oss::srv::MP2BPP::RouteStateEventType>(kCallSign);
                break;
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : break;
        }
    }
    /// @brief Destructor
    virtual ~planning_missionplanning_state() = default;
    /// @brief Delete copy constructor
    planning_missionplanning_state(const planning_missionplanning_state& other) = delete;
    /// @brief Delete copy assignment
    planning_missionplanning_state& operator=(const planning_missionplanning_state& other) = delete;
    /// @brief Move constructor
    planning_missionplanning_state(planning_missionplanning_state&& other) noexcept
        : mInterface(other.mInterface)
        , mDdsInterface(other.mDdsInterface)
        , mProtocol(other.mProtocol)
    {
    }
    /// @brief Move assignment
    planning_missionplanning_state& operator=(planning_missionplanning_state&& other) noexcept
    {
        mInterface = other.mInterface;
        mDdsInterface = other.mDdsInterface;
        mProtocol = other.mProtocol;
        return *this;
    }
    /// @brief Send event with data to subscribing service consumers
    /// @uptrace{SWS_CM_90437}
    ara::core::Result<void> Send(const SampleType& data)
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                const para::serializer::TransformationProps props{};
                para::serializer::Serializer serializer{};
                serializer.write(props, data);
                auto payload = serializer.ensure();
                return mInterface->SendEvent(kCallSign, payload);
            }
            case para::com::ServiceProtocol::kIpc :
            {
                const para::serializer::TransformationProps props{};
                para::serializer::Serializer serializer{};
                serializer.write(props, data);
                auto payload = serializer.ensure();
                return mInterface->SendEvent(kCallSign, payload);
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                dds::oss::srv::MP2BPP::RouteStateEventType _event_;
                _event_.instance_id() = mDdsInterface->GetInstanceId();
                _event_.data() = oss::type::tier4_planning_msgs::msg::RouteState_ConvertToDdsType(data);
                return mDdsInterface->SendEvent<dds::oss::srv::MP2BPP::RouteStateEventType>(kCallSign, _event_);
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : return ara::core::Result<void>(ara::com::ComErrc::kNetworkBindingFailure);
        }
    }
    /// @brief Returns unique pointer about SampleType
    /// @uptrace{SWS_CM_90438}
    ara::core::Result<ara::com::SampleAllocateePtr<SampleType>> Allocate()
    {
        return std::make_unique<SampleType>();
    }
    
private:
    para::com::SkeletonInterface* mInterface;
    para::com::SkeletonDdsInterface* mDdsInterface;
    para::com::ServiceProtocol mProtocol;
    const std::string kCallSign = {"planning_missionplanning_state"};
};
} /// namespace events
/// @uptrace{SWS_CM_01031}
namespace fields
{
} /// namespace fields
/// @uptrace{SWS_CM_00002}
class BPP_SI_missionplannerSkeleton
{
public:
    /// @uptrace{SWS_CM_00191}
    struct planning_missionplanning_missionplanner_clearrouteOutput
    {
        oss::type::autoware_adapi_v1_msgs::srv::ClearRoute_Response res;
    };
    struct planning_missionplanning_missionplanner_configloggerOutput
    {
        oss::type::logging_demo::srv::ConfigLogger_Response res;
    };
    struct planning_missionplanning_missionplanner_describeparametersOutput
    {
        oss::type::rcl_interfaces::srv::DescribeParameters_Response res;
    };
    struct planning_missionplanning_missionplanner_getparametersOutput
    {
        oss::type::rcl_interfaces::srv::GetParameters_Response res;
    };
    struct planning_missionplanning_missionplanner_getparametertypesOutput
    {
        oss::type::rcl_interfaces::srv::GetParameterTypes_Response res;
    };
    struct planning_missionplanning_missionplanner_listparametersOutput
    {
        oss::type::rcl_interfaces::srv::ListParameters_Response res;
    };
    struct planning_missionplanning_missionplanner_setlaneletrouteOutput
    {
        oss::type::tier4_planning_msgs::srv::SetLaneletRoute_Response res;
    };
    struct planning_missionplanning_missionplanner_setparametersOutput
    {
        oss::type::rcl_interfaces::srv::SetParameters_Response res;
    };
    struct planning_missionplanning_missionplanner_setparametersatomicallyOutput
    {
        oss::type::rcl_interfaces::srv::SetParametersAtomically_Response res;
    };
    struct planning_missionplanning_missionplanner_setwaypointrouteOutput
    {
        oss::type::tier4_planning_msgs::srv::SetWaypointRoute_Response res;
    };
    /// @brief Constructor
    /// @uptrace{SWS_CM_00002, SWS_CM_00152}
    BPP_SI_missionplannerSkeleton(ara::core::InstanceSpecifier instanceSpec, ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent)
        : mInterface(std::make_unique<para::com::SkeletonInterface>(instanceSpec, mode))
        , mDdsInterface(std::make_unique<para::com::SkeletonDdsInterface>(instanceSpec, mode))
        , mProtocol(para::com::GetServiceProtocol(instanceSpec))
        , planning_missionplanning_missionplanner_debug_goalfootprint(mInterface.get(), mDdsInterface.get(), mProtocol)
        , planning_missionplanning_missionplanner_debug_processingtimems(mInterface.get(), mDdsInterface.get(), mProtocol)
        , planning_missionplanning_route(mInterface.get(), mDdsInterface.get(), mProtocol)
        , planning_missionplanning_routemarker(mInterface.get(), mDdsInterface.get(), mProtocol)
        , planning_missionplanning_state(mInterface.get(), mDdsInterface.get(), mProtocol)
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_clearrouteCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_clearroute(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_configloggerCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_configlogger(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_describeparametersCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_describeparameters(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_getparametersCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_getparameters(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_getparametertypesCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_getparametertypes(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_listparametersCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_listparameters(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_setlaneletrouteCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_setlaneletroute(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_setparametersCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_setparameters(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_setparametersatomicallyCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_setparametersatomically(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_setwaypointrouteCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_setwaypointroute(data, token);
                });
                mInterface->SetE2EErrorHandler([this](const ara::com::e2e::E2EErrorDomain& errorCode, ara::com::e2e::DataID dataID, ara::com::e2e::MessageCounter messageCounter) {
                    E2EErrorHandler(errorCode, dataID, messageCounter);
                });
                break;
            }
            case para::com::ServiceProtocol::kIpc :
            {
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_clearrouteCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_clearroute(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_configloggerCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_configlogger(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_describeparametersCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_describeparameters(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_getparametersCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_getparameters(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_getparametertypesCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_getparametertypes(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_listparametersCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_listparameters(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_setlaneletrouteCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_setlaneletroute(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_setparametersCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_setparameters(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_setparametersatomicallyCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_setparametersatomically(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_setwaypointrouteCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_setwaypointroute(data, token);
                });
                mInterface->SetE2EErrorHandler([this](const ara::com::e2e::E2EErrorDomain& errorCode, ara::com::e2e::DataID dataID, ara::com::e2e::MessageCounter messageCounter) {
                    E2EErrorHandler(errorCode, dataID, messageCounter);
                });
                break;
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                mDdsInterface->CreateMethods<dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_Request, dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_Reply>();
                mDdsInterface->SetMethodCallHandler([this](dds::sub::AnyDataReader& reader) {
                    HandleDdsMethod(reader);
                });
                break;
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : break;
        }
    }
    /// @brief Destructor
    virtual ~BPP_SI_missionplannerSkeleton() = default;
    /// @brief Delete copy constructor
    /// @uptrace{SWS_CM_00134}
    BPP_SI_missionplannerSkeleton(const BPP_SI_missionplannerSkeleton& other) = delete;
    /// @brief Delete copy assignment
    /// @uptrace{SWS_CM_00134}
    BPP_SI_missionplannerSkeleton& operator=(const BPP_SI_missionplannerSkeleton& other) = delete;
    /// @brief Move constructor
    /// @uptrace{SWS_CM_00135}
    BPP_SI_missionplannerSkeleton(BPP_SI_missionplannerSkeleton&& other) noexcept
        : mInterface(std::move(other.mInterface))
        , mDdsInterface(std::move(other.mDdsInterface))
        , mProtocol(std::move(other.mProtocol))
        , planning_missionplanning_missionplanner_debug_goalfootprint(std::move(other.planning_missionplanning_missionplanner_debug_goalfootprint))
        , planning_missionplanning_missionplanner_debug_processingtimems(std::move(other.planning_missionplanning_missionplanner_debug_processingtimems))
        , planning_missionplanning_route(std::move(other.planning_missionplanning_route))
        , planning_missionplanning_routemarker(std::move(other.planning_missionplanning_routemarker))
        , planning_missionplanning_state(std::move(other.planning_missionplanning_state))
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_clearrouteCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_clearroute(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_configloggerCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_configlogger(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_describeparametersCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_describeparameters(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_getparametersCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_getparameters(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_getparametertypesCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_getparametertypes(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_listparametersCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_listparameters(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_setlaneletrouteCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_setlaneletroute(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_setparametersCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_setparameters(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_setparametersatomicallyCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_setparametersatomically(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_setwaypointrouteCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_setwaypointroute(data, token);
                });
                mInterface->SetE2EErrorHandler([this](const ara::com::e2e::E2EErrorDomain& errorCode, ara::com::e2e::DataID dataID, ara::com::e2e::MessageCounter messageCounter) {
                    E2EErrorHandler(errorCode, dataID, messageCounter);
                });
            }
            case para::com::ServiceProtocol::kIpc :
            {
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_clearrouteCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_clearroute(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_configloggerCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_configlogger(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_describeparametersCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_describeparameters(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_getparametersCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_getparameters(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_getparametertypesCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_getparametertypes(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_listparametersCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_listparameters(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_setlaneletrouteCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_setlaneletroute(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_setparametersCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_setparameters(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_setparametersatomicallyCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_setparametersatomically(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_setwaypointrouteCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_setwaypointroute(data, token);
                });
                mInterface->SetE2EErrorHandler([this](const ara::com::e2e::E2EErrorDomain& errorCode, ara::com::e2e::DataID dataID, ara::com::e2e::MessageCounter messageCounter) {
                    E2EErrorHandler(errorCode, dataID, messageCounter);
                });
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                mDdsInterface->CreateMethods<dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_Request, dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_Reply>();
                mDdsInterface->SetMethodCallHandler([this](dds::sub::AnyDataReader& reader) {
                    HandleDdsMethod(reader);
                });
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : break;
        }
        other.mInterface.reset();
        other.mDdsInterface.reset();
    }
    /// @brief Move assignment
    /// @uptrace{SWS_CM_00135}
    BPP_SI_missionplannerSkeleton& operator=(BPP_SI_missionplannerSkeleton&& other) noexcept
    {
        mInterface = std::move(other.mInterface);
        mDdsInterface = std::move(other.mDdsInterface);
        mProtocol = std::move(other.mProtocol);
        planning_missionplanning_missionplanner_debug_goalfootprint = std::move(other.planning_missionplanning_missionplanner_debug_goalfootprint);
        planning_missionplanning_missionplanner_debug_processingtimems = std::move(other.planning_missionplanning_missionplanner_debug_processingtimems);
        planning_missionplanning_route = std::move(other.planning_missionplanning_route);
        planning_missionplanning_routemarker = std::move(other.planning_missionplanning_routemarker);
        planning_missionplanning_state = std::move(other.planning_missionplanning_state);
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_clearrouteCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_clearroute(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_configloggerCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_configlogger(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_describeparametersCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_describeparameters(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_getparametersCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_getparameters(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_getparametertypesCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_getparametertypes(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_listparametersCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_listparameters(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_setlaneletrouteCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_setlaneletroute(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_setparametersCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_setparameters(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_setparametersatomicallyCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_setparametersatomically(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_setwaypointrouteCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_setwaypointroute(data, token);
                });
                mInterface->SetE2EErrorHandler([this](const ara::com::e2e::E2EErrorDomain& errorCode, ara::com::e2e::DataID dataID, ara::com::e2e::MessageCounter messageCounter) {
                    E2EErrorHandler(errorCode, dataID, messageCounter);
                });
            }
            case para::com::ServiceProtocol::kIpc :
            {
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_clearrouteCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_clearroute(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_configloggerCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_configlogger(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_describeparametersCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_describeparameters(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_getparametersCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_getparameters(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_getparametertypesCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_getparametertypes(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_listparametersCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_listparameters(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_setlaneletrouteCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_setlaneletroute(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_setparametersCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_setparameters(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_setparametersatomicallyCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_setparametersatomically(data, token);
                });
                mInterface->SetMethodCallHandler(kplanning_missionplanning_missionplanner_setwaypointrouteCallSign, [this](const std::vector<std::uint8_t>& data, const para::com::MethodToken token) {
                    Handleplanning_missionplanning_missionplanner_setwaypointroute(data, token);
                });
                mInterface->SetE2EErrorHandler([this](const ara::com::e2e::E2EErrorDomain& errorCode, ara::com::e2e::DataID dataID, ara::com::e2e::MessageCounter messageCounter) {
                    E2EErrorHandler(errorCode, dataID, messageCounter);
                });
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                mDdsInterface->CreateMethods<dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_Request, dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_Reply>();
                mDdsInterface->SetMethodCallHandler([this](dds::sub::AnyDataReader& reader) {
                    HandleDdsMethod(reader);
                });
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : break;
        }
        other.mInterface.reset();
        other.mDdsInterface.reset();
        return *this;
    }
    /// @brief Send "OfferService" message to Communication Management
    /// @uptrace{SWS_CM_00101}
    ara::core::Result<void> OfferService()
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                return mInterface->OfferService();
            }
            case para::com::ServiceProtocol::kIpc :
            {
            	return mInterface->OfferService();
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
            	return mDdsInterface->OfferService();
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : return ara::core::Result<void>(ara::com::ComErrc::kNetworkBindingFailure);
        }
    }
    /// @brief Send "StopOfferService" message to Communication Management
    /// @uptrace{SWS_CM_00111}
    void StopOfferService()
    {
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                mInterface->StopOfferService();
                break;
            }
            case para::com::ServiceProtocol::kIpc :
            {
                mInterface->StopOfferService();
                break;
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                mDdsInterface->StopOfferService();
                break;
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : break;
        }
    }
    /// @brief Allows the implementation providing the service method to trigger the execution of the next service consumer method call at a specific point of time
    ///        if the processing mode is set to kPoll.
    /// @note This function requires that ara::com::MethodCallProcessingMode is configured as kPoll by constructor
    /// @uptrace{SWS_CM_00199}
    ara::core::Future<bool> ProcessNextMethodCall()
    {
        ara::core::Promise<bool> promise{};
        ara::core::Result<bool> ret{false};
        switch (mProtocol)
        {
            case para::com::ServiceProtocol::kSomeIp :
            {
                ret = mInterface->ProcessNextMethodCall();
                break;
            }
            case para::com::ServiceProtocol::kIpc :
            {
                ret = mInterface->ProcessNextMethodCall();
                break;
            }
            #ifdef PARA_DDS_IMPLEMENTATION
            case para::com::ServiceProtocol::kDds :
            {
                ret = mDdsInterface->ProcessNextMethodCall();
                break;
            }
            #endif /// PARA_DDS_IMPLEMENTATION
            default : break;
        }
        if (ret.HasValue())
        {
            promise.set_value(ret.Value());
        }
        else
        {
            promise.SetError(ret.Error());
        }
        return promise.get_future();
    }
    /// @brief In case the call to E2E_check indicated a failed E2E check of the request message, the server application can get notified via an E2E error handler.
    /// @uptrace{SWS_CM_10470}
    virtual void E2EErrorHandler(const ara::com::e2e::E2EErrorDomain& errorCode, ara::com::e2e::DataID dataID, ara::com::e2e::MessageCounter messageCounter)
    {
    }
    
private:
    std::unique_ptr<para::com::SkeletonInterface> mInterface;
    std::unique_ptr<para::com::SkeletonDdsInterface> mDdsInterface;
    para::com::ServiceProtocol mProtocol;
    
public:
    /// @brief Event, planning_missionplanning_missionplanner_debug_goalfootprint
    events::planning_missionplanning_missionplanner_debug_goalfootprint planning_missionplanning_missionplanner_debug_goalfootprint;
    /// @brief Event, planning_missionplanning_missionplanner_debug_processingtimems
    events::planning_missionplanning_missionplanner_debug_processingtimems planning_missionplanning_missionplanner_debug_processingtimems;
    /// @brief Event, planning_missionplanning_route
    events::planning_missionplanning_route planning_missionplanning_route;
    /// @brief Event, planning_missionplanning_routemarker
    events::planning_missionplanning_routemarker planning_missionplanning_routemarker;
    /// @brief Event, planning_missionplanning_state
    events::planning_missionplanning_state planning_missionplanning_state;
    /// @brief Method, planning_missionplanning_missionplanner_clearroute
    /// @uptrace{SWS_CM_00191}
    virtual ara::core::Future<planning_missionplanning_missionplanner_clearrouteOutput> planning_missionplanning_missionplanner_clearroute() = 0;
    /// @brief Method, planning_missionplanning_missionplanner_configlogger
    /// @uptrace{SWS_CM_00191}
    virtual ara::core::Future<planning_missionplanning_missionplanner_configloggerOutput> planning_missionplanning_missionplanner_configlogger(const oss::type::logging_demo::srv::ConfigLogger_Request& req) = 0;
    /// @brief Method, planning_missionplanning_missionplanner_describeparameters
    /// @uptrace{SWS_CM_00191}
    virtual ara::core::Future<planning_missionplanning_missionplanner_describeparametersOutput> planning_missionplanning_missionplanner_describeparameters(const oss::type::rcl_interfaces::srv::DescribeParameters_Request& req) = 0;
    /// @brief Method, planning_missionplanning_missionplanner_getparameters
    /// @uptrace{SWS_CM_00191}
    virtual ara::core::Future<planning_missionplanning_missionplanner_getparametersOutput> planning_missionplanning_missionplanner_getparameters(const oss::type::rcl_interfaces::srv::GetParameters_Request& req) = 0;
    /// @brief Method, planning_missionplanning_missionplanner_getparametertypes
    /// @uptrace{SWS_CM_00191}
    virtual ara::core::Future<planning_missionplanning_missionplanner_getparametertypesOutput> planning_missionplanning_missionplanner_getparametertypes(const oss::type::rcl_interfaces::srv::GetParameterTypes_Request& req) = 0;
    /// @brief Method, planning_missionplanning_missionplanner_listparameters
    /// @uptrace{SWS_CM_00191}
    virtual ara::core::Future<planning_missionplanning_missionplanner_listparametersOutput> planning_missionplanning_missionplanner_listparameters(const oss::type::rcl_interfaces::srv::ListParameters_Request& req) = 0;
    /// @brief Method, planning_missionplanning_missionplanner_setlaneletroute
    /// @uptrace{SWS_CM_00191}
    virtual ara::core::Future<planning_missionplanning_missionplanner_setlaneletrouteOutput> planning_missionplanning_missionplanner_setlaneletroute(const oss::type::tier4_planning_msgs::srv::SetLaneletRoute_Request& req) = 0;
    /// @brief Method, planning_missionplanning_missionplanner_setparameters
    /// @uptrace{SWS_CM_00191}
    virtual ara::core::Future<planning_missionplanning_missionplanner_setparametersOutput> planning_missionplanning_missionplanner_setparameters(const oss::type::rcl_interfaces::srv::SetParameters_Request& req) = 0;
    /// @brief Method, planning_missionplanning_missionplanner_setparametersatomically
    /// @uptrace{SWS_CM_00191}
    virtual ara::core::Future<planning_missionplanning_missionplanner_setparametersatomicallyOutput> planning_missionplanning_missionplanner_setparametersatomically(const oss::type::rcl_interfaces::srv::SetParametersAtomically_Request& req) = 0;
    /// @brief Method, planning_missionplanning_missionplanner_setwaypointroute
    /// @uptrace{SWS_CM_00191}
    virtual ara::core::Future<planning_missionplanning_missionplanner_setwaypointrouteOutput> planning_missionplanning_missionplanner_setwaypointroute(const oss::type::tier4_planning_msgs::srv::SetWaypointRoute_Request& req) = 0;
    
private:
    void Handleplanning_missionplanning_missionplanner_clearroute(const std::vector<std::uint8_t>& data, const para::com::MethodToken token)
    {
        const para::serializer::TransformationProps props{};
        std::uint8_t retResult{1};
        std::vector<std::uint8_t> retData{};
        auto future = planning_missionplanning_missionplanner_clearroute();
        auto result = future.GetResult();
        if (result.HasValue())
        {
            planning_missionplanning_missionplanner_clearrouteOutput output = result.Value();
            para::serializer::Serializer serializer{};
            serializer.write(props, output.res);
            retData = serializer.ensure();
            retResult = 0;
        }
        else
        {
            para::serializer::ApplicationMethodErrorData errorData{result.Error().Domain().Id(), result.Error().Value()};
            para::serializer::ApplicationMethodError error;
            error = errorData;
            para::serializer::Serializer serializer{};
            serializer.write(para::serializer::Serializer::getApplicationMethodErrorProps(), error);
            retData = serializer.ensure();
            retResult = 1;
        }
        mInterface->ReturnMethod(kplanning_missionplanning_missionplanner_clearrouteCallSign, retResult, retData, token);
    }
    void Handleplanning_missionplanning_missionplanner_configlogger(const std::vector<std::uint8_t>& data, const para::com::MethodToken token)
    {
        const para::serializer::TransformationProps props{};
        std::uint8_t retResult{1};
        std::vector<std::uint8_t> retData{};
        para::serializer::Deserializer deserializer{data};
        oss::type::logging_demo::srv::ConfigLogger_Request _req_;
        deserializer.read(props, _req_);
        auto future = planning_missionplanning_missionplanner_configlogger(_req_);
        auto result = future.GetResult();
        if (result.HasValue())
        {
            planning_missionplanning_missionplanner_configloggerOutput output = result.Value();
            para::serializer::Serializer serializer{};
            serializer.write(props, output.res);
            retData = serializer.ensure();
            retResult = 0;
        }
        else
        {
            para::serializer::ApplicationMethodErrorData errorData{result.Error().Domain().Id(), result.Error().Value()};
            para::serializer::ApplicationMethodError error;
            error = errorData;
            para::serializer::Serializer serializer{};
            serializer.write(para::serializer::Serializer::getApplicationMethodErrorProps(), error);
            retData = serializer.ensure();
            retResult = 1;
        }
        mInterface->ReturnMethod(kplanning_missionplanning_missionplanner_configloggerCallSign, retResult, retData, token);
    }
    void Handleplanning_missionplanning_missionplanner_describeparameters(const std::vector<std::uint8_t>& data, const para::com::MethodToken token)
    {
        const para::serializer::TransformationProps props{};
        std::uint8_t retResult{1};
        std::vector<std::uint8_t> retData{};
        para::serializer::Deserializer deserializer{data};
        oss::type::rcl_interfaces::srv::DescribeParameters_Request _req_;
        deserializer.read(props, _req_);
        auto future = planning_missionplanning_missionplanner_describeparameters(_req_);
        auto result = future.GetResult();
        if (result.HasValue())
        {
            planning_missionplanning_missionplanner_describeparametersOutput output = result.Value();
            para::serializer::Serializer serializer{};
            serializer.write(props, output.res);
            retData = serializer.ensure();
            retResult = 0;
        }
        else
        {
            para::serializer::ApplicationMethodErrorData errorData{result.Error().Domain().Id(), result.Error().Value()};
            para::serializer::ApplicationMethodError error;
            error = errorData;
            para::serializer::Serializer serializer{};
            serializer.write(para::serializer::Serializer::getApplicationMethodErrorProps(), error);
            retData = serializer.ensure();
            retResult = 1;
        }
        mInterface->ReturnMethod(kplanning_missionplanning_missionplanner_describeparametersCallSign, retResult, retData, token);
    }
    void Handleplanning_missionplanning_missionplanner_getparameters(const std::vector<std::uint8_t>& data, const para::com::MethodToken token)
    {
        const para::serializer::TransformationProps props{};
        std::uint8_t retResult{1};
        std::vector<std::uint8_t> retData{};
        para::serializer::Deserializer deserializer{data};
        oss::type::rcl_interfaces::srv::GetParameters_Request _req_;
        deserializer.read(props, _req_);
        auto future = planning_missionplanning_missionplanner_getparameters(_req_);
        auto result = future.GetResult();
        if (result.HasValue())
        {
            planning_missionplanning_missionplanner_getparametersOutput output = result.Value();
            para::serializer::Serializer serializer{};
            serializer.write(props, output.res);
            retData = serializer.ensure();
            retResult = 0;
        }
        else
        {
            para::serializer::ApplicationMethodErrorData errorData{result.Error().Domain().Id(), result.Error().Value()};
            para::serializer::ApplicationMethodError error;
            error = errorData;
            para::serializer::Serializer serializer{};
            serializer.write(para::serializer::Serializer::getApplicationMethodErrorProps(), error);
            retData = serializer.ensure();
            retResult = 1;
        }
        mInterface->ReturnMethod(kplanning_missionplanning_missionplanner_getparametersCallSign, retResult, retData, token);
    }
    void Handleplanning_missionplanning_missionplanner_getparametertypes(const std::vector<std::uint8_t>& data, const para::com::MethodToken token)
    {
        const para::serializer::TransformationProps props{};
        std::uint8_t retResult{1};
        std::vector<std::uint8_t> retData{};
        para::serializer::Deserializer deserializer{data};
        oss::type::rcl_interfaces::srv::GetParameterTypes_Request _req_;
        deserializer.read(props, _req_);
        auto future = planning_missionplanning_missionplanner_getparametertypes(_req_);
        auto result = future.GetResult();
        if (result.HasValue())
        {
            planning_missionplanning_missionplanner_getparametertypesOutput output = result.Value();
            para::serializer::Serializer serializer{};
            serializer.write(props, output.res);
            retData = serializer.ensure();
            retResult = 0;
        }
        else
        {
            para::serializer::ApplicationMethodErrorData errorData{result.Error().Domain().Id(), result.Error().Value()};
            para::serializer::ApplicationMethodError error;
            error = errorData;
            para::serializer::Serializer serializer{};
            serializer.write(para::serializer::Serializer::getApplicationMethodErrorProps(), error);
            retData = serializer.ensure();
            retResult = 1;
        }
        mInterface->ReturnMethod(kplanning_missionplanning_missionplanner_getparametertypesCallSign, retResult, retData, token);
    }
    void Handleplanning_missionplanning_missionplanner_listparameters(const std::vector<std::uint8_t>& data, const para::com::MethodToken token)
    {
        const para::serializer::TransformationProps props{};
        std::uint8_t retResult{1};
        std::vector<std::uint8_t> retData{};
        para::serializer::Deserializer deserializer{data};
        oss::type::rcl_interfaces::srv::ListParameters_Request _req_;
        deserializer.read(props, _req_);
        auto future = planning_missionplanning_missionplanner_listparameters(_req_);
        auto result = future.GetResult();
        if (result.HasValue())
        {
            planning_missionplanning_missionplanner_listparametersOutput output = result.Value();
            para::serializer::Serializer serializer{};
            serializer.write(props, output.res);
            retData = serializer.ensure();
            retResult = 0;
        }
        else
        {
            para::serializer::ApplicationMethodErrorData errorData{result.Error().Domain().Id(), result.Error().Value()};
            para::serializer::ApplicationMethodError error;
            error = errorData;
            para::serializer::Serializer serializer{};
            serializer.write(para::serializer::Serializer::getApplicationMethodErrorProps(), error);
            retData = serializer.ensure();
            retResult = 1;
        }
        mInterface->ReturnMethod(kplanning_missionplanning_missionplanner_listparametersCallSign, retResult, retData, token);
    }
    void Handleplanning_missionplanning_missionplanner_setlaneletroute(const std::vector<std::uint8_t>& data, const para::com::MethodToken token)
    {
        const para::serializer::TransformationProps props{};
        std::uint8_t retResult{1};
        std::vector<std::uint8_t> retData{};
        para::serializer::Deserializer deserializer{data};
        oss::type::tier4_planning_msgs::srv::SetLaneletRoute_Request _req_;
        deserializer.read(props, _req_);
        auto future = planning_missionplanning_missionplanner_setlaneletroute(_req_);
        auto result = future.GetResult();
        if (result.HasValue())
        {
            planning_missionplanning_missionplanner_setlaneletrouteOutput output = result.Value();
            para::serializer::Serializer serializer{};
            serializer.write(props, output.res);
            retData = serializer.ensure();
            retResult = 0;
        }
        else
        {
            para::serializer::ApplicationMethodErrorData errorData{result.Error().Domain().Id(), result.Error().Value()};
            para::serializer::ApplicationMethodError error;
            error = errorData;
            para::serializer::Serializer serializer{};
            serializer.write(para::serializer::Serializer::getApplicationMethodErrorProps(), error);
            retData = serializer.ensure();
            retResult = 1;
        }
        mInterface->ReturnMethod(kplanning_missionplanning_missionplanner_setlaneletrouteCallSign, retResult, retData, token);
    }
    void Handleplanning_missionplanning_missionplanner_setparameters(const std::vector<std::uint8_t>& data, const para::com::MethodToken token)
    {
        const para::serializer::TransformationProps props{};
        std::uint8_t retResult{1};
        std::vector<std::uint8_t> retData{};
        para::serializer::Deserializer deserializer{data};
        oss::type::rcl_interfaces::srv::SetParameters_Request _req_;
        deserializer.read(props, _req_);
        auto future = planning_missionplanning_missionplanner_setparameters(_req_);
        auto result = future.GetResult();
        if (result.HasValue())
        {
            planning_missionplanning_missionplanner_setparametersOutput output = result.Value();
            para::serializer::Serializer serializer{};
            serializer.write(props, output.res);
            retData = serializer.ensure();
            retResult = 0;
        }
        else
        {
            para::serializer::ApplicationMethodErrorData errorData{result.Error().Domain().Id(), result.Error().Value()};
            para::serializer::ApplicationMethodError error;
            error = errorData;
            para::serializer::Serializer serializer{};
            serializer.write(para::serializer::Serializer::getApplicationMethodErrorProps(), error);
            retData = serializer.ensure();
            retResult = 1;
        }
        mInterface->ReturnMethod(kplanning_missionplanning_missionplanner_setparametersCallSign, retResult, retData, token);
    }
    void Handleplanning_missionplanning_missionplanner_setparametersatomically(const std::vector<std::uint8_t>& data, const para::com::MethodToken token)
    {
        const para::serializer::TransformationProps props{};
        std::uint8_t retResult{1};
        std::vector<std::uint8_t> retData{};
        para::serializer::Deserializer deserializer{data};
        oss::type::rcl_interfaces::srv::SetParametersAtomically_Request _req_;
        deserializer.read(props, _req_);
        auto future = planning_missionplanning_missionplanner_setparametersatomically(_req_);
        auto result = future.GetResult();
        if (result.HasValue())
        {
            planning_missionplanning_missionplanner_setparametersatomicallyOutput output = result.Value();
            para::serializer::Serializer serializer{};
            serializer.write(props, output.res);
            retData = serializer.ensure();
            retResult = 0;
        }
        else
        {
            para::serializer::ApplicationMethodErrorData errorData{result.Error().Domain().Id(), result.Error().Value()};
            para::serializer::ApplicationMethodError error;
            error = errorData;
            para::serializer::Serializer serializer{};
            serializer.write(para::serializer::Serializer::getApplicationMethodErrorProps(), error);
            retData = serializer.ensure();
            retResult = 1;
        }
        mInterface->ReturnMethod(kplanning_missionplanning_missionplanner_setparametersatomicallyCallSign, retResult, retData, token);
    }
    void Handleplanning_missionplanning_missionplanner_setwaypointroute(const std::vector<std::uint8_t>& data, const para::com::MethodToken token)
    {
        const para::serializer::TransformationProps props{};
        std::uint8_t retResult{1};
        std::vector<std::uint8_t> retData{};
        para::serializer::Deserializer deserializer{data};
        oss::type::tier4_planning_msgs::srv::SetWaypointRoute_Request _req_;
        deserializer.read(props, _req_);
        auto future = planning_missionplanning_missionplanner_setwaypointroute(_req_);
        auto result = future.GetResult();
        if (result.HasValue())
        {
            planning_missionplanning_missionplanner_setwaypointrouteOutput output = result.Value();
            para::serializer::Serializer serializer{};
            serializer.write(props, output.res);
            retData = serializer.ensure();
            retResult = 0;
        }
        else
        {
            para::serializer::ApplicationMethodErrorData errorData{result.Error().Domain().Id(), result.Error().Value()};
            para::serializer::ApplicationMethodError error;
            error = errorData;
            para::serializer::Serializer serializer{};
            serializer.write(para::serializer::Serializer::getApplicationMethodErrorProps(), error);
            retData = serializer.ensure();
            retResult = 1;
        }
        mInterface->ReturnMethod(kplanning_missionplanning_missionplanner_setwaypointrouteCallSign, retResult, retData, token);
    }
    #ifdef PARA_DDS_IMPLEMENTATION
    void HandleDdsMethod(const dds::sub::AnyDataReader& reader)
    {
        dds::sub::DataReader<dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_Request> _reader_ = reader;
        dds::sub::LoanedSamples<dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_Request> _requests_;
        _requests_ = _reader_.take();
        for (auto& _request_ : _requests_)
        {
            if (_request_->info().valid())
            {
                auto _data_ = _request_.data().data();
                switch (_data_._d())
                {
                    case dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_planning_missionplanning_missionplanner_clearroute_Hash :
                    {
                        Handleplanning_missionplanning_missionplanner_clearroute(_data_.planning_missionplanning_missionplanner_clearroute(), _request_.data().header());
                        break;
                    }
                    case dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_planning_missionplanning_missionplanner_configlogger_Hash :
                    {
                        Handleplanning_missionplanning_missionplanner_configlogger(_data_.planning_missionplanning_missionplanner_configlogger(), _request_.data().header());
                        break;
                    }
                    case dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_planning_missionplanning_missionplanner_describeparameters_Hash :
                    {
                        Handleplanning_missionplanning_missionplanner_describeparameters(_data_.planning_missionplanning_missionplanner_describeparameters(), _request_.data().header());
                        break;
                    }
                    case dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_planning_missionplanning_missionplanner_getparameters_Hash :
                    {
                        Handleplanning_missionplanning_missionplanner_getparameters(_data_.planning_missionplanning_missionplanner_getparameters(), _request_.data().header());
                        break;
                    }
                    case dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_planning_missionplanning_missionplanner_getparametertypes_Hash :
                    {
                        Handleplanning_missionplanning_missionplanner_getparametertypes(_data_.planning_missionplanning_missionplanner_getparametertypes(), _request_.data().header());
                        break;
                    }
                    case dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_planning_missionplanning_missionplanner_listparameters_Hash :
                    {
                        Handleplanning_missionplanning_missionplanner_listparameters(_data_.planning_missionplanning_missionplanner_listparameters(), _request_.data().header());
                        break;
                    }
                    case dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_planning_missionplanning_missionplanner_setlaneletroute_Hash :
                    {
                        Handleplanning_missionplanning_missionplanner_setlaneletroute(_data_.planning_missionplanning_missionplanner_setlaneletroute(), _request_.data().header());
                        break;
                    }
                    case dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_planning_missionplanning_missionplanner_setparameters_Hash :
                    {
                        Handleplanning_missionplanning_missionplanner_setparameters(_data_.planning_missionplanning_missionplanner_setparameters(), _request_.data().header());
                        break;
                    }
                    case dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_planning_missionplanning_missionplanner_setparametersatomically_Hash :
                    {
                        Handleplanning_missionplanning_missionplanner_setparametersatomically(_data_.planning_missionplanning_missionplanner_setparametersatomically(), _request_.data().header());
                        break;
                    }
                    case dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_planning_missionplanning_missionplanner_setwaypointroute_Hash :
                    {
                        Handleplanning_missionplanning_missionplanner_setwaypointroute(_data_.planning_missionplanning_missionplanner_setwaypointroute(), _request_.data().header());
                        break;
                    }
                    default : break;
                }
            }
        }
    }
    #endif /// PARA_DDS_IMPLEMENTATION
    #ifdef PARA_DDS_IMPLEMENTATION
    void Handleplanning_missionplanning_missionplanner_clearroute(const dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_planning_missionplanning_missionplanner_clearroute_In& data, const dds::rpc::RequestHeader token)
    {
        dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_planning_missionplanning_missionplanner_clearroute_Result _result_{};
        auto future = this->planning_missionplanning_missionplanner_clearroute();
        auto result = future.GetResult();
        if (result.HasValue())
        {
            dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_planning_missionplanning_missionplanner_clearroute_Out _out_args_;
            _out_args_.res() = oss::type::autoware_adapi_v1_msgs::srv::ClearRoute_Response_ConvertToDdsType(result.Value().res);
            _result_.result(_out_args_, dds::RETCODE_OK);
        }
        else
        {
            dds::ara::core::ErrorCode _error_;
            _error_.error_code() = result.Error().Value();
            _error_.error_domain_value() = result.Error().Domain().Id();
            _result_.error(_error_, dds::RETCODE_ERROR);
        }
        dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_Return _return_;
        _return_.planning_missionplanning_missionplanner_clearroute(_result_, dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_planning_missionplanning_missionplanner_clearroute_Hash);
        dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_Reply _reply_;
        _reply_.data() = _return_;
        _reply_.header() = mDdsInterface->GetReplyHeader(token);
        mDdsInterface->ReturnMethod<dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_Reply>(_reply_);
    }
    #endif /// PARA_DDS_IMPLEMENTATION
    #ifdef PARA_DDS_IMPLEMENTATION
    void Handleplanning_missionplanning_missionplanner_configlogger(const dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_planning_missionplanning_missionplanner_configlogger_In& data, const dds::rpc::RequestHeader token)
    {
        dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_planning_missionplanning_missionplanner_configlogger_Result _result_{};
        oss::type::logging_demo::srv::ConfigLogger_Request _req = oss::type::logging_demo::srv::ConfigLogger_Request_ConvertFromDdsType(data.req());
        auto future = this->planning_missionplanning_missionplanner_configlogger(_req);
        auto result = future.GetResult();
        if (result.HasValue())
        {
            dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_planning_missionplanning_missionplanner_configlogger_Out _out_args_;
            _out_args_.res() = oss::type::logging_demo::srv::ConfigLogger_Response_ConvertToDdsType(result.Value().res);
            _result_.result(_out_args_, dds::RETCODE_OK);
        }
        else
        {
            dds::ara::core::ErrorCode _error_;
            _error_.error_code() = result.Error().Value();
            _error_.error_domain_value() = result.Error().Domain().Id();
            _result_.error(_error_, dds::RETCODE_ERROR);
        }
        dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_Return _return_;
        _return_.planning_missionplanning_missionplanner_configlogger(_result_, dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_planning_missionplanning_missionplanner_configlogger_Hash);
        dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_Reply _reply_;
        _reply_.data() = _return_;
        _reply_.header() = mDdsInterface->GetReplyHeader(token);
        mDdsInterface->ReturnMethod<dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_Reply>(_reply_);
    }
    #endif /// PARA_DDS_IMPLEMENTATION
    #ifdef PARA_DDS_IMPLEMENTATION
    void Handleplanning_missionplanning_missionplanner_describeparameters(const dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_planning_missionplanning_missionplanner_describeparameters_In& data, const dds::rpc::RequestHeader token)
    {
        dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_planning_missionplanning_missionplanner_describeparameters_Result _result_{};
        oss::type::rcl_interfaces::srv::DescribeParameters_Request _req = oss::type::rcl_interfaces::srv::DescribeParameters_Request_ConvertFromDdsType(data.req());
        auto future = this->planning_missionplanning_missionplanner_describeparameters(_req);
        auto result = future.GetResult();
        if (result.HasValue())
        {
            dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_planning_missionplanning_missionplanner_describeparameters_Out _out_args_;
            _out_args_.res() = oss::type::rcl_interfaces::srv::DescribeParameters_Response_ConvertToDdsType(result.Value().res);
            _result_.result(_out_args_, dds::RETCODE_OK);
        }
        else
        {
            dds::ara::core::ErrorCode _error_;
            _error_.error_code() = result.Error().Value();
            _error_.error_domain_value() = result.Error().Domain().Id();
            _result_.error(_error_, dds::RETCODE_ERROR);
        }
        dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_Return _return_;
        _return_.planning_missionplanning_missionplanner_describeparameters(_result_, dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_planning_missionplanning_missionplanner_describeparameters_Hash);
        dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_Reply _reply_;
        _reply_.data() = _return_;
        _reply_.header() = mDdsInterface->GetReplyHeader(token);
        mDdsInterface->ReturnMethod<dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_Reply>(_reply_);
    }
    #endif /// PARA_DDS_IMPLEMENTATION
    #ifdef PARA_DDS_IMPLEMENTATION
    void Handleplanning_missionplanning_missionplanner_getparameters(const dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_planning_missionplanning_missionplanner_getparameters_In& data, const dds::rpc::RequestHeader token)
    {
        dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_planning_missionplanning_missionplanner_getparameters_Result _result_{};
        oss::type::rcl_interfaces::srv::GetParameters_Request _req = oss::type::rcl_interfaces::srv::GetParameters_Request_ConvertFromDdsType(data.req());
        auto future = this->planning_missionplanning_missionplanner_getparameters(_req);
        auto result = future.GetResult();
        if (result.HasValue())
        {
            dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_planning_missionplanning_missionplanner_getparameters_Out _out_args_;
            _out_args_.res() = oss::type::rcl_interfaces::srv::GetParameters_Response_ConvertToDdsType(result.Value().res);
            _result_.result(_out_args_, dds::RETCODE_OK);
        }
        else
        {
            dds::ara::core::ErrorCode _error_;
            _error_.error_code() = result.Error().Value();
            _error_.error_domain_value() = result.Error().Domain().Id();
            _result_.error(_error_, dds::RETCODE_ERROR);
        }
        dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_Return _return_;
        _return_.planning_missionplanning_missionplanner_getparameters(_result_, dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_planning_missionplanning_missionplanner_getparameters_Hash);
        dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_Reply _reply_;
        _reply_.data() = _return_;
        _reply_.header() = mDdsInterface->GetReplyHeader(token);
        mDdsInterface->ReturnMethod<dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_Reply>(_reply_);
    }
    #endif /// PARA_DDS_IMPLEMENTATION
    #ifdef PARA_DDS_IMPLEMENTATION
    void Handleplanning_missionplanning_missionplanner_getparametertypes(const dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_planning_missionplanning_missionplanner_getparametertypes_In& data, const dds::rpc::RequestHeader token)
    {
        dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_planning_missionplanning_missionplanner_getparametertypes_Result _result_{};
        oss::type::rcl_interfaces::srv::GetParameterTypes_Request _req = oss::type::rcl_interfaces::srv::GetParameterTypes_Request_ConvertFromDdsType(data.req());
        auto future = this->planning_missionplanning_missionplanner_getparametertypes(_req);
        auto result = future.GetResult();
        if (result.HasValue())
        {
            dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_planning_missionplanning_missionplanner_getparametertypes_Out _out_args_;
            _out_args_.res() = oss::type::rcl_interfaces::srv::GetParameterTypes_Response_ConvertToDdsType(result.Value().res);
            _result_.result(_out_args_, dds::RETCODE_OK);
        }
        else
        {
            dds::ara::core::ErrorCode _error_;
            _error_.error_code() = result.Error().Value();
            _error_.error_domain_value() = result.Error().Domain().Id();
            _result_.error(_error_, dds::RETCODE_ERROR);
        }
        dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_Return _return_;
        _return_.planning_missionplanning_missionplanner_getparametertypes(_result_, dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_planning_missionplanning_missionplanner_getparametertypes_Hash);
        dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_Reply _reply_;
        _reply_.data() = _return_;
        _reply_.header() = mDdsInterface->GetReplyHeader(token);
        mDdsInterface->ReturnMethod<dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_Reply>(_reply_);
    }
    #endif /// PARA_DDS_IMPLEMENTATION
    #ifdef PARA_DDS_IMPLEMENTATION
    void Handleplanning_missionplanning_missionplanner_listparameters(const dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_planning_missionplanning_missionplanner_listparameters_In& data, const dds::rpc::RequestHeader token)
    {
        dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_planning_missionplanning_missionplanner_listparameters_Result _result_{};
        oss::type::rcl_interfaces::srv::ListParameters_Request _req = oss::type::rcl_interfaces::srv::ListParameters_Request_ConvertFromDdsType(data.req());
        auto future = this->planning_missionplanning_missionplanner_listparameters(_req);
        auto result = future.GetResult();
        if (result.HasValue())
        {
            dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_planning_missionplanning_missionplanner_listparameters_Out _out_args_;
            _out_args_.res() = oss::type::rcl_interfaces::srv::ListParameters_Response_ConvertToDdsType(result.Value().res);
            _result_.result(_out_args_, dds::RETCODE_OK);
        }
        else
        {
            dds::ara::core::ErrorCode _error_;
            _error_.error_code() = result.Error().Value();
            _error_.error_domain_value() = result.Error().Domain().Id();
            _result_.error(_error_, dds::RETCODE_ERROR);
        }
        dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_Return _return_;
        _return_.planning_missionplanning_missionplanner_listparameters(_result_, dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_planning_missionplanning_missionplanner_listparameters_Hash);
        dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_Reply _reply_;
        _reply_.data() = _return_;
        _reply_.header() = mDdsInterface->GetReplyHeader(token);
        mDdsInterface->ReturnMethod<dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_Reply>(_reply_);
    }
    #endif /// PARA_DDS_IMPLEMENTATION
    #ifdef PARA_DDS_IMPLEMENTATION
    void Handleplanning_missionplanning_missionplanner_setlaneletroute(const dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_planning_missionplanning_missionplanner_setlaneletroute_In& data, const dds::rpc::RequestHeader token)
    {
        dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_planning_missionplanning_missionplanner_setlaneletroute_Result _result_{};
        oss::type::tier4_planning_msgs::srv::SetLaneletRoute_Request _req = oss::type::tier4_planning_msgs::srv::SetLaneletRoute_Request_ConvertFromDdsType(data.req());
        auto future = this->planning_missionplanning_missionplanner_setlaneletroute(_req);
        auto result = future.GetResult();
        if (result.HasValue())
        {
            dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_planning_missionplanning_missionplanner_setlaneletroute_Out _out_args_;
            _out_args_.res() = oss::type::tier4_planning_msgs::srv::SetLaneletRoute_Response_ConvertToDdsType(result.Value().res);
            _result_.result(_out_args_, dds::RETCODE_OK);
        }
        else
        {
            dds::ara::core::ErrorCode _error_;
            _error_.error_code() = result.Error().Value();
            _error_.error_domain_value() = result.Error().Domain().Id();
            _result_.error(_error_, dds::RETCODE_ERROR);
        }
        dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_Return _return_;
        _return_.planning_missionplanning_missionplanner_setlaneletroute(_result_, dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_planning_missionplanning_missionplanner_setlaneletroute_Hash);
        dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_Reply _reply_;
        _reply_.data() = _return_;
        _reply_.header() = mDdsInterface->GetReplyHeader(token);
        mDdsInterface->ReturnMethod<dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_Reply>(_reply_);
    }
    #endif /// PARA_DDS_IMPLEMENTATION
    #ifdef PARA_DDS_IMPLEMENTATION
    void Handleplanning_missionplanning_missionplanner_setparameters(const dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_planning_missionplanning_missionplanner_setparameters_In& data, const dds::rpc::RequestHeader token)
    {
        dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_planning_missionplanning_missionplanner_setparameters_Result _result_{};
        oss::type::rcl_interfaces::srv::SetParameters_Request _req = oss::type::rcl_interfaces::srv::SetParameters_Request_ConvertFromDdsType(data.req());
        auto future = this->planning_missionplanning_missionplanner_setparameters(_req);
        auto result = future.GetResult();
        if (result.HasValue())
        {
            dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_planning_missionplanning_missionplanner_setparameters_Out _out_args_;
            _out_args_.res() = oss::type::rcl_interfaces::srv::SetParameters_Response_ConvertToDdsType(result.Value().res);
            _result_.result(_out_args_, dds::RETCODE_OK);
        }
        else
        {
            dds::ara::core::ErrorCode _error_;
            _error_.error_code() = result.Error().Value();
            _error_.error_domain_value() = result.Error().Domain().Id();
            _result_.error(_error_, dds::RETCODE_ERROR);
        }
        dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_Return _return_;
        _return_.planning_missionplanning_missionplanner_setparameters(_result_, dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_planning_missionplanning_missionplanner_setparameters_Hash);
        dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_Reply _reply_;
        _reply_.data() = _return_;
        _reply_.header() = mDdsInterface->GetReplyHeader(token);
        mDdsInterface->ReturnMethod<dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_Reply>(_reply_);
    }
    #endif /// PARA_DDS_IMPLEMENTATION
    #ifdef PARA_DDS_IMPLEMENTATION
    void Handleplanning_missionplanning_missionplanner_setparametersatomically(const dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_planning_missionplanning_missionplanner_setparametersatomically_In& data, const dds::rpc::RequestHeader token)
    {
        dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_planning_missionplanning_missionplanner_setparametersatomically_Result _result_{};
        oss::type::rcl_interfaces::srv::SetParametersAtomically_Request _req = oss::type::rcl_interfaces::srv::SetParametersAtomically_Request_ConvertFromDdsType(data.req());
        auto future = this->planning_missionplanning_missionplanner_setparametersatomically(_req);
        auto result = future.GetResult();
        if (result.HasValue())
        {
            dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_planning_missionplanning_missionplanner_setparametersatomically_Out _out_args_;
            _out_args_.res() = oss::type::rcl_interfaces::srv::SetParametersAtomically_Response_ConvertToDdsType(result.Value().res);
            _result_.result(_out_args_, dds::RETCODE_OK);
        }
        else
        {
            dds::ara::core::ErrorCode _error_;
            _error_.error_code() = result.Error().Value();
            _error_.error_domain_value() = result.Error().Domain().Id();
            _result_.error(_error_, dds::RETCODE_ERROR);
        }
        dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_Return _return_;
        _return_.planning_missionplanning_missionplanner_setparametersatomically(_result_, dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_planning_missionplanning_missionplanner_setparametersatomically_Hash);
        dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_Reply _reply_;
        _reply_.data() = _return_;
        _reply_.header() = mDdsInterface->GetReplyHeader(token);
        mDdsInterface->ReturnMethod<dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_Reply>(_reply_);
    }
    #endif /// PARA_DDS_IMPLEMENTATION
    #ifdef PARA_DDS_IMPLEMENTATION
    void Handleplanning_missionplanning_missionplanner_setwaypointroute(const dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_planning_missionplanning_missionplanner_setwaypointroute_In& data, const dds::rpc::RequestHeader token)
    {
        dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_planning_missionplanning_missionplanner_setwaypointroute_Result _result_{};
        oss::type::tier4_planning_msgs::srv::SetWaypointRoute_Request _req = oss::type::tier4_planning_msgs::srv::SetWaypointRoute_Request_ConvertFromDdsType(data.req());
        auto future = this->planning_missionplanning_missionplanner_setwaypointroute(_req);
        auto result = future.GetResult();
        if (result.HasValue())
        {
            dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_planning_missionplanning_missionplanner_setwaypointroute_Out _out_args_;
            _out_args_.res() = oss::type::tier4_planning_msgs::srv::SetWaypointRoute_Response_ConvertToDdsType(result.Value().res);
            _result_.result(_out_args_, dds::RETCODE_OK);
        }
        else
        {
            dds::ara::core::ErrorCode _error_;
            _error_.error_code() = result.Error().Value();
            _error_.error_domain_value() = result.Error().Domain().Id();
            _result_.error(_error_, dds::RETCODE_ERROR);
        }
        dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_Return _return_;
        _return_.planning_missionplanning_missionplanner_setwaypointroute(_result_, dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_planning_missionplanning_missionplanner_setwaypointroute_Hash);
        dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_Reply _reply_;
        _reply_.data() = _return_;
        _reply_.header() = mDdsInterface->GetReplyHeader(token);
        mDdsInterface->ReturnMethod<dds::oss::srv::MP2BPP::BPP_SI_missionplannerMethod_Reply>(_reply_);
    }
    #endif /// PARA_DDS_IMPLEMENTATION
    const std::string kplanning_missionplanning_missionplanner_clearrouteCallSign{"planning_missionplanning_missionplanner_clearroute"};
    const std::string kplanning_missionplanning_missionplanner_configloggerCallSign{"planning_missionplanning_missionplanner_configlogger"};
    const std::string kplanning_missionplanning_missionplanner_describeparametersCallSign{"planning_missionplanning_missionplanner_describeparameters"};
    const std::string kplanning_missionplanning_missionplanner_getparametersCallSign{"planning_missionplanning_missionplanner_getparameters"};
    const std::string kplanning_missionplanning_missionplanner_getparametertypesCallSign{"planning_missionplanning_missionplanner_getparametertypes"};
    const std::string kplanning_missionplanning_missionplanner_listparametersCallSign{"planning_missionplanning_missionplanner_listparameters"};
    const std::string kplanning_missionplanning_missionplanner_setlaneletrouteCallSign{"planning_missionplanning_missionplanner_setlaneletroute"};
    const std::string kplanning_missionplanning_missionplanner_setparametersCallSign{"planning_missionplanning_missionplanner_setparameters"};
    const std::string kplanning_missionplanning_missionplanner_setparametersatomicallyCallSign{"planning_missionplanning_missionplanner_setparametersatomically"};
    const std::string kplanning_missionplanning_missionplanner_setwaypointrouteCallSign{"planning_missionplanning_missionplanner_setwaypointroute"};
};
} /// namespace skeleton
} /// namespace MP2BPP
} /// namespace srv
} /// namespace oss
#endif /// PARA_COM_GEN_OSS_SRV_MP2BPP_SERVICE_INTERFACE_BPP_SI_MISSIONPLANNER_SKELETON_H