///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, ARA::COM Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : impl_type_objectclassification_label.h
/// IMPLEMENTATION DATA TYPE NAME     : ObjectClassification_label
/// GENERATED DATE                    : 2025-12-05 12:02:23
///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// CAUTION!! AUTOMATICALLY GENERATED FILE - DO NOT EDIT                                                   
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_ARA_COM_GEN_OSS_TYPE_CPP_IMPL_TYPE_OBJECTCLASSIFICATION_LABEL_H
#define PARA_ARA_COM_GEN_OSS_TYPE_CPP_IMPL_TYPE_OBJECTCLASSIFICATION_LABEL_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// @uptrace{SWS_CM_00402}
#include <cstdint>
#ifdef PARA_DDS_IMPLEMENTATION
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION FOR DDS
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "impl_type_objectclassification_label.hpp"
#endif /// PARA_DDS_IMPLEMENTATION
/// @uptrace{SWS_CM_10375}
namespace oss
{
namespace type
{
enum class ObjectClassification_label : std::uint8_t
{
    UNKNOWN = 0U,
    CAR = 1U,
    TRUCK = 2U,
    BUS = 3U,
    TRAILER = 4U,
    MOTORCYCLE = 5U,
    BICYCLE = 6U,
    PEDESTRIAN = 7U
};
 
#ifdef PARA_DDS_IMPLEMENTATION
inline dds::oss::type::ObjectClassification_label ObjectClassification_label_ConvertToDdsType(const oss::type::ObjectClassification_label& src)
{
    switch (src)
    {
        default:
        case oss::type::ObjectClassification_label::UNKNOWN :
            return dds::oss::type::ObjectClassification_label::ObjectClassification_label_UNKNOWN;
        case oss::type::ObjectClassification_label::CAR :
            return dds::oss::type::ObjectClassification_label::ObjectClassification_label_CAR;
        case oss::type::ObjectClassification_label::TRUCK :
            return dds::oss::type::ObjectClassification_label::ObjectClassification_label_TRUCK;
        case oss::type::ObjectClassification_label::BUS :
            return dds::oss::type::ObjectClassification_label::ObjectClassification_label_BUS;
        case oss::type::ObjectClassification_label::TRAILER :
            return dds::oss::type::ObjectClassification_label::ObjectClassification_label_TRAILER;
        case oss::type::ObjectClassification_label::MOTORCYCLE :
            return dds::oss::type::ObjectClassification_label::ObjectClassification_label_MOTORCYCLE;
        case oss::type::ObjectClassification_label::BICYCLE :
            return dds::oss::type::ObjectClassification_label::ObjectClassification_label_BICYCLE;
        case oss::type::ObjectClassification_label::PEDESTRIAN :
            return dds::oss::type::ObjectClassification_label::ObjectClassification_label_PEDESTRIAN;
    }
}
 
inline oss::type::ObjectClassification_label ObjectClassification_label_ConvertFromDdsType(const dds::oss::type::ObjectClassification_label& src)
{
    switch (src)
    {
        default:
        case dds::oss::type::ObjectClassification_label::ObjectClassification_label_UNKNOWN :
            return oss::type::ObjectClassification_label::UNKNOWN;
        case dds::oss::type::ObjectClassification_label::ObjectClassification_label_CAR :
            return oss::type::ObjectClassification_label::CAR;
        case dds::oss::type::ObjectClassification_label::ObjectClassification_label_TRUCK :
            return oss::type::ObjectClassification_label::TRUCK;
        case dds::oss::type::ObjectClassification_label::ObjectClassification_label_BUS :
            return oss::type::ObjectClassification_label::BUS;
        case dds::oss::type::ObjectClassification_label::ObjectClassification_label_TRAILER :
            return oss::type::ObjectClassification_label::TRAILER;
        case dds::oss::type::ObjectClassification_label::ObjectClassification_label_MOTORCYCLE :
            return oss::type::ObjectClassification_label::MOTORCYCLE;
        case dds::oss::type::ObjectClassification_label::ObjectClassification_label_BICYCLE :
            return oss::type::ObjectClassification_label::BICYCLE;
        case dds::oss::type::ObjectClassification_label::ObjectClassification_label_PEDESTRIAN :
            return oss::type::ObjectClassification_label::PEDESTRIAN;
    }
}
#endif /// PARA_DDS_IMPLEMENTATION
} /// namespace type
} /// namespace oss
#endif /// PARA_ARA_COM_GEN_OSS_TYPE_CPP_IMPL_TYPE_OBJECTCLASSIFICATION_LABEL_H