///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, ARA::COM Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : impl_type_getparametertypes_response.h
/// IMPLEMENTATION DATA TYPE NAME     : GetParameterTypes_Response
/// GENERATED DATE                    : 2025-12-05 12:02:30
///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// CAUTION!! AUTOMATICALLY GENERATED FILE - DO NOT EDIT                                                   
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_ARA_COM_GEN_OSS_TYPE_RCL_INTERFACES_SRV_CPP_IMPL_TYPE_GETPARAMETERTYPES_RESPONSE_H
#define PARA_ARA_COM_GEN_OSS_TYPE_RCL_INTERFACES_SRV_CPP_IMPL_TYPE_GETPARAMETERTYPES_RESPONSE_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// @uptrace{SWS_CM_00402}
#include <ara/core/structure.h>
#include "oss/type/impl_type_uint8_vector.h"
#ifdef PARA_DDS_IMPLEMENTATION
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION FOR DDS
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "impl_type_getparametertypes_response.hpp"
#endif /// PARA_DDS_IMPLEMENTATION
/// @uptrace{SWS_CM_10375}
namespace oss
{
namespace type
{
namespace rcl_interfaces
{
namespace srv
{
struct GetParameterTypes_Response
{
    oss::type::uint8_Vector types;

    /// @brief constructor
    GetParameterTypes_Response() = default;
    GetParameterTypes_Response(const oss::type::uint8_Vector& _types)
        : types{_types}
    {
    }

    /// @note marker for serialize, don't touch
    PARA_STRUCTURE(GetParameterTypes_Response, types);
};
 
#ifdef PARA_DDS_IMPLEMENTATION
inline dds::oss::type::rcl_interfaces::srv::GetParameterTypes_Response GetParameterTypes_Response_ConvertToDdsType(const oss::type::rcl_interfaces::srv::GetParameterTypes_Response& src)
{
    dds::oss::type::rcl_interfaces::srv::GetParameterTypes_Response dst;
    dst.types() = oss::type::uint8_Vector_ConvertToDdsType(src.types);
    return dst;
}
 
inline oss::type::rcl_interfaces::srv::GetParameterTypes_Response GetParameterTypes_Response_ConvertFromDdsType(const dds::oss::type::rcl_interfaces::srv::GetParameterTypes_Response& src)
{
    oss::type::rcl_interfaces::srv::GetParameterTypes_Response dst;
    dst.types = oss::type::uint8_Vector_ConvertFromDdsType(src.types());
    return dst;
}
#endif /// PARA_DDS_IMPLEMENTATION
} /// namespace srv
} /// namespace rcl_interfaces
} /// namespace type
} /// namespace oss
#endif /// PARA_ARA_COM_GEN_OSS_TYPE_RCL_INTERFACES_SRV_CPP_IMPL_TYPE_GETPARAMETERTYPES_RESPONSE_H