///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, ARA::COM Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : impl_type_getparameters_request.h
/// IMPLEMENTATION DATA TYPE NAME     : GetParameters_Request
/// GENERATED DATE                    : 2025-12-05 12:02:29
///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// CAUTION!! AUTOMATICALLY GENERATED FILE - DO NOT EDIT                                                   
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_ARA_COM_GEN_OSS_TYPE_RCL_INTERFACES_SRV_CPP_IMPL_TYPE_GETPARAMETERS_REQUEST_H
#define PARA_ARA_COM_GEN_OSS_TYPE_RCL_INTERFACES_SRV_CPP_IMPL_TYPE_GETPARAMETERS_REQUEST_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// @uptrace{SWS_CM_00402}
#include <ara/core/structure.h>
#include "oss/type/impl_type_string_vector.h"
#ifdef PARA_DDS_IMPLEMENTATION
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION FOR DDS
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "impl_type_getparameters_request.hpp"
#endif /// PARA_DDS_IMPLEMENTATION
/// @uptrace{SWS_CM_10375}
namespace oss
{
namespace type
{
namespace rcl_interfaces
{
namespace srv
{
struct GetParameters_Request
{
    oss::type::string_Vector names;

    /// @brief constructor
    GetParameters_Request() = default;
    GetParameters_Request(const oss::type::string_Vector& _names)
        : names{_names}
    {
    }

    /// @note marker for serialize, don't touch
    PARA_STRUCTURE(GetParameters_Request, names);
};
 
#ifdef PARA_DDS_IMPLEMENTATION
inline dds::oss::type::rcl_interfaces::srv::GetParameters_Request GetParameters_Request_ConvertToDdsType(const oss::type::rcl_interfaces::srv::GetParameters_Request& src)
{
    dds::oss::type::rcl_interfaces::srv::GetParameters_Request dst;
    dst.names() = oss::type::string_Vector_ConvertToDdsType(src.names);
    return dst;
}
 
inline oss::type::rcl_interfaces::srv::GetParameters_Request GetParameters_Request_ConvertFromDdsType(const dds::oss::type::rcl_interfaces::srv::GetParameters_Request& src)
{
    oss::type::rcl_interfaces::srv::GetParameters_Request dst;
    dst.names = oss::type::string_Vector_ConvertFromDdsType(src.names());
    return dst;
}
#endif /// PARA_DDS_IMPLEMENTATION
} /// namespace srv
} /// namespace rcl_interfaces
} /// namespace type
} /// namespace oss
#endif /// PARA_ARA_COM_GEN_OSS_TYPE_RCL_INTERFACES_SRV_CPP_IMPL_TYPE_GETPARAMETERS_REQUEST_H