///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, ARA::COM Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : rs_si_missionplanner_common.h
/// SERVICE INTERFACE NAME            : RS_SI_missionplanner
/// GENERATED DATE                    : 2025-12-02 18:57:08
///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// CAUTION!! AUTOMATICALLY GENERATED FILE - DO NOT EDIT                                                   
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_COM_GEN_OSS_SRV_MP2RS_SERVICE_INTERFACE_RS_SI_MISSIONPLANNER_COMMON_H
#define PARA_COM_GEN_OSS_SRV_MP2RS_SERVICE_INTERFACE_RS_SI_MISSIONPLANNER_COMMON_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "ara/core/future.h"
#include "ara/core/promise.h"
#include "ara/core/result.h"
/// @uptrace{SWS_CM_01001}
#include "ara/com/types.h"
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION OF CPP IMPLEMENTATION DATA TYPE HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// @uptrace{SWS_CM_10372}
#include "oss/type/autoware_adapi_v1_msgs/srv/impl_type_clearroute_response.h"
#include "oss/type/autoware_planning_msgs/msg/impl_type_laneletroute.h"
#include "oss/type/tier4_planning_msgs/msg/impl_type_routestate.h"
#include "oss/type/tier4_planning_msgs/srv/impl_type_setlaneletroute_request.h"
#include "oss/type/tier4_planning_msgs/srv/impl_type_setlaneletroute_response.h"
#include "oss/type/tier4_planning_msgs/srv/impl_type_setwaypointroute_request.h"
#include "oss/type/tier4_planning_msgs/srv/impl_type_setwaypointroute_response.h"
#ifdef PARA_DDS_IMPLEMENTATION
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION FOR DDS
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "rs_si_missionplanner_common.hpp"
#endif /// PARA_DDS_IMPLEMENTATION
/// @uptrace{SWS_CM_01005}
namespace oss
{
namespace srv
{
namespace MP2RS
{
/// @uptrace{SWS_CM_01010}, {SWS_CM_01012}
class RS_SI_missionplanner
{
public:
    std::uint32_t serviceContractVersionMajor = 1;
    std::uint32_t serviceContractVersionMinor = 0;
};
} /// namespace MP2RS
} /// namespace srv
} /// namespace oss
#endif /// PARA_COM_GEN_OSS_SRV_MP2RS_SERVICE_INTERFACE_RS_SI_MISSIONPLANNER_COMMON_H