///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, ARA::COM Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : impl_type_trafficlightelement.h
/// IMPLEMENTATION DATA TYPE NAME     : TrafficLightElement
/// GENERATED DATE                    : 2025-12-05 12:02:25
///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// CAUTION!! AUTOMATICALLY GENERATED FILE - DO NOT EDIT                                                   
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_ARA_COM_GEN_OSS_TYPE_AUTOWARE_PERCEPTION_MSGS_MSG_CPP_IMPL_TYPE_TRAFFICLIGHTELEMENT_H
#define PARA_ARA_COM_GEN_OSS_TYPE_AUTOWARE_PERCEPTION_MSGS_MSG_CPP_IMPL_TYPE_TRAFFICLIGHTELEMENT_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// @uptrace{SWS_CM_00402}
#include <ara/core/structure.h>

#include "oss/type/impl_type_trafficlightelement_color.h"
#include "oss/type/impl_type_trafficlightelement_shape.h"
#include "oss/type/impl_type_trafficlightelement_status.h"
#ifdef PARA_DDS_IMPLEMENTATION
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION FOR DDS
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "impl_type_trafficlightelement.hpp"
#endif /// PARA_DDS_IMPLEMENTATION
/// @uptrace{SWS_CM_10375}
namespace oss
{
namespace type
{
namespace autoware_perception_msgs
{
namespace msg
{
struct TrafficLightElement
{
    oss::type::TrafficLightElement_color color;
    oss::type::TrafficLightElement_shape shape;
    oss::type::TrafficLightElement_status status;
    float confidence;

    /// @brief constructor
    TrafficLightElement() = default;
    TrafficLightElement(const oss::type::TrafficLightElement_color& _color, const oss::type::TrafficLightElement_shape& _shape, const oss::type::TrafficLightElement_status& _status, const float& _confidence)
        : color{_color}
        , shape{_shape}
        , status{_status}
        , confidence{_confidence}
    {
    }

    /// @note marker for serialize, don't touch
    PARA_STRUCTURE(TrafficLightElement, color, shape, status, confidence);
};
 
#ifdef PARA_DDS_IMPLEMENTATION
inline dds::oss::type::autoware_perception_msgs::msg::TrafficLightElement TrafficLightElement_ConvertToDdsType(const oss::type::autoware_perception_msgs::msg::TrafficLightElement& src)
{
    dds::oss::type::autoware_perception_msgs::msg::TrafficLightElement dst;
    dst.color() = oss::type::TrafficLightElement_color_ConvertToDdsType(src.color);
    dst.shape() = oss::type::TrafficLightElement_shape_ConvertToDdsType(src.shape);
    dst.status() = oss::type::TrafficLightElement_status_ConvertToDdsType(src.status);
    dst.confidence() = src.confidence;
    return dst;
}
 
inline oss::type::autoware_perception_msgs::msg::TrafficLightElement TrafficLightElement_ConvertFromDdsType(const dds::oss::type::autoware_perception_msgs::msg::TrafficLightElement& src)
{
    oss::type::autoware_perception_msgs::msg::TrafficLightElement dst;
    dst.color = oss::type::TrafficLightElement_color_ConvertFromDdsType(src.color());
    dst.shape = oss::type::TrafficLightElement_shape_ConvertFromDdsType(src.shape());
    dst.status = oss::type::TrafficLightElement_status_ConvertFromDdsType(src.status());
    dst.confidence = src.confidence();
    return dst;
}
#endif /// PARA_DDS_IMPLEMENTATION
} /// namespace msg
} /// namespace autoware_perception_msgs
} /// namespace type
} /// namespace oss
#endif /// PARA_ARA_COM_GEN_OSS_TYPE_AUTOWARE_PERCEPTION_MSGS_MSG_CPP_IMPL_TYPE_TRAFFICLIGHTELEMENT_H