///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : pport_mp2bpp.h
/// SOFTWARE COMPONENT NAME           : PPort_MP2BPP
/// GENERATED DATE                    : 2025-12-02 18:57:11
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_AA_GEN_SOFTWARE_COMPONENT_PPORT_EXE_MISSIONPLANNER_AA_PPORT_MP2BPP_H
#define PARA_AA_GEN_SOFTWARE_COMPONENT_PPORT_EXE_MISSIONPLANNER_AA_PPORT_MP2BPP_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "oss/srv/MP2BPP/bpp_si_missionplanner_skeleton.h"
 
#include "ara/log/logger.h"
 
#include <mutex>
#include <thread>
 
namespace oss
{
namespace srv
{
namespace MP2BPP
{
namespace skeleton
{
 
class BPP_SI_missionplannerSkeletonImpl : public BPP_SI_missionplannerSkeleton
{
public:
    /// @brief Constructor
    BPP_SI_missionplannerSkeletonImpl(ara::core::InstanceSpecifier instanceSpec, ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent);
    
    /// @brief Request with Response method, planning_missionplanning_missionplanner_clearroute
    ara::core::Future<BPP_SI_missionplannerSkeleton::planning_missionplanning_missionplanner_clearrouteOutput> planning_missionplanning_missionplanner_clearroute() override;
    
    /// @brief Request with Response method, planning_missionplanning_missionplanner_configlogger
    ara::core::Future<BPP_SI_missionplannerSkeleton::planning_missionplanning_missionplanner_configloggerOutput> planning_missionplanning_missionplanner_configlogger(const oss::type::logging_demo::srv::ConfigLogger_Request& req) override;
    
    /// @brief Request with Response method, planning_missionplanning_missionplanner_describeparameters
    ara::core::Future<BPP_SI_missionplannerSkeleton::planning_missionplanning_missionplanner_describeparametersOutput> planning_missionplanning_missionplanner_describeparameters(const oss::type::rcl_interfaces::srv::DescribeParameters_Request& req) override;
    
    /// @brief Request with Response method, planning_missionplanning_missionplanner_getparameters
    ara::core::Future<BPP_SI_missionplannerSkeleton::planning_missionplanning_missionplanner_getparametersOutput> planning_missionplanning_missionplanner_getparameters(const oss::type::rcl_interfaces::srv::GetParameters_Request& req) override;
    
    /// @brief Request with Response method, planning_missionplanning_missionplanner_getparametertypes
    ara::core::Future<BPP_SI_missionplannerSkeleton::planning_missionplanning_missionplanner_getparametertypesOutput> planning_missionplanning_missionplanner_getparametertypes(const oss::type::rcl_interfaces::srv::GetParameterTypes_Request& req) override;
    
    /// @brief Request with Response method, planning_missionplanning_missionplanner_listparameters
    ara::core::Future<BPP_SI_missionplannerSkeleton::planning_missionplanning_missionplanner_listparametersOutput> planning_missionplanning_missionplanner_listparameters(const oss::type::rcl_interfaces::srv::ListParameters_Request& req) override;
    
    /// @brief Request with Response method, planning_missionplanning_missionplanner_setlaneletroute
    ara::core::Future<BPP_SI_missionplannerSkeleton::planning_missionplanning_missionplanner_setlaneletrouteOutput> planning_missionplanning_missionplanner_setlaneletroute(const oss::type::tier4_planning_msgs::srv::SetLaneletRoute_Request& req) override;
    
    /// @brief Request with Response method, planning_missionplanning_missionplanner_setparameters
    ara::core::Future<BPP_SI_missionplannerSkeleton::planning_missionplanning_missionplanner_setparametersOutput> planning_missionplanning_missionplanner_setparameters(const oss::type::rcl_interfaces::srv::SetParameters_Request& req) override;
    
    /// @brief Request with Response method, planning_missionplanning_missionplanner_setparametersatomically
    ara::core::Future<BPP_SI_missionplannerSkeleton::planning_missionplanning_missionplanner_setparametersatomicallyOutput> planning_missionplanning_missionplanner_setparametersatomically(const oss::type::rcl_interfaces::srv::SetParametersAtomically_Request& req) override;
    
    /// @brief Request with Response method, planning_missionplanning_missionplanner_setwaypointroute
    ara::core::Future<BPP_SI_missionplannerSkeleton::planning_missionplanning_missionplanner_setwaypointrouteOutput> planning_missionplanning_missionplanner_setwaypointroute(const oss::type::tier4_planning_msgs::srv::SetWaypointRoute_Request& req) override;

private:
    /// @brief Logger for this port
    ara::log::Logger& m_logger;

};
 
} /// namespace skeleton
} /// namespace MP2BPP
} /// namespace srv
} /// namespace oss

namespace exe_missionplanner
{
namespace aa
{
namespace port
{
 
class PPort_MP2BPP
{
public:
    /// @brief Constructor
    PPort_MP2BPP();
    
    /// @brief Destructor
    ~PPort_MP2BPP();
    
    /// @brief Start port
    void Start();
    
    /// @brief Terminate port
    void Terminate();
    
    /// @brief Write event data to buffer, planning_missionplanning_missionplanner_debug_goalfootprint
    void WriteDataplanning_missionplanning_missionplanner_debug_goalfootprint(const oss::srv::MP2BPP::skeleton::events::planning_missionplanning_missionplanner_debug_goalfootprint::SampleType& data);
     
    /// @brief Send event cyclic from buffer data, planning_missionplanning_missionplanner_debug_goalfootprint
    void SendEventplanning_missionplanning_missionplanner_debug_goalfootprintCyclic();
     
    /// @brief Send event directly from buffer data, planning_missionplanning_missionplanner_debug_goalfootprint
    void SendEventplanning_missionplanning_missionplanner_debug_goalfootprintTriggered();
     
    /// @brief Send event directly with argument, planning_missionplanning_missionplanner_debug_goalfootprint
    void SendEventplanning_missionplanning_missionplanner_debug_goalfootprintTriggered(const oss::srv::MP2BPP::skeleton::events::planning_missionplanning_missionplanner_debug_goalfootprint::SampleType& data);

    /// @brief Write event data to buffer, planning_missionplanning_missionplanner_debug_processingtimems
    void WriteDataplanning_missionplanning_missionplanner_debug_processingtimems(const oss::srv::MP2BPP::skeleton::events::planning_missionplanning_missionplanner_debug_processingtimems::SampleType& data);
     
    /// @brief Send event cyclic from buffer data, planning_missionplanning_missionplanner_debug_processingtimems
    void SendEventplanning_missionplanning_missionplanner_debug_processingtimemsCyclic();
     
    /// @brief Send event directly from buffer data, planning_missionplanning_missionplanner_debug_processingtimems
    void SendEventplanning_missionplanning_missionplanner_debug_processingtimemsTriggered();
     
    /// @brief Send event directly with argument, planning_missionplanning_missionplanner_debug_processingtimems
    void SendEventplanning_missionplanning_missionplanner_debug_processingtimemsTriggered(const oss::srv::MP2BPP::skeleton::events::planning_missionplanning_missionplanner_debug_processingtimems::SampleType& data);

    /// @brief Write event data to buffer, planning_missionplanning_route
    void WriteDataplanning_missionplanning_route(const oss::srv::MP2BPP::skeleton::events::planning_missionplanning_route::SampleType& data);
     
    /// @brief Send event cyclic from buffer data, planning_missionplanning_route
    void SendEventplanning_missionplanning_routeCyclic();
     
    /// @brief Send event directly from buffer data, planning_missionplanning_route
    void SendEventplanning_missionplanning_routeTriggered();
     
    /// @brief Send event directly with argument, planning_missionplanning_route
    void SendEventplanning_missionplanning_routeTriggered(const oss::srv::MP2BPP::skeleton::events::planning_missionplanning_route::SampleType& data);

    /// @brief Write event data to buffer, planning_missionplanning_routemarker
    void WriteDataplanning_missionplanning_routemarker(const oss::srv::MP2BPP::skeleton::events::planning_missionplanning_routemarker::SampleType& data);
     
    /// @brief Send event cyclic from buffer data, planning_missionplanning_routemarker
    void SendEventplanning_missionplanning_routemarkerCyclic();
     
    /// @brief Send event directly from buffer data, planning_missionplanning_routemarker
    void SendEventplanning_missionplanning_routemarkerTriggered();
     
    /// @brief Send event directly with argument, planning_missionplanning_routemarker
    void SendEventplanning_missionplanning_routemarkerTriggered(const oss::srv::MP2BPP::skeleton::events::planning_missionplanning_routemarker::SampleType& data);

    /// @brief Write event data to buffer, planning_missionplanning_state
    void WriteDataplanning_missionplanning_state(const oss::srv::MP2BPP::skeleton::events::planning_missionplanning_state::SampleType& data);
     
    /// @brief Send event cyclic from buffer data, planning_missionplanning_state
    void SendEventplanning_missionplanning_stateCyclic();
     
    /// @brief Send event directly from buffer data, planning_missionplanning_state
    void SendEventplanning_missionplanning_stateTriggered();
     
    /// @brief Send event directly with argument, planning_missionplanning_state
    void SendEventplanning_missionplanning_stateTriggered(const oss::srv::MP2BPP::skeleton::events::planning_missionplanning_state::SampleType& data);
     
private:
    /// @brief Logger for this port
    ara::log::Logger& m_logger;
    
    /// @brief Flag of port status
    bool m_running;
    
    /// @brief Mutex for this port
    std::mutex m_mutex;
    
    /// @brief AUTOSAR Port Interface
    std::unique_ptr<oss::srv::MP2BPP::skeleton::BPP_SI_missionplannerSkeletonImpl> m_interface;
    
    /// @brief Data for event, planning_missionplanning_missionplanner_debug_goalfootprint
    oss::srv::MP2BPP::skeleton::events::planning_missionplanning_missionplanner_debug_goalfootprint::SampleType m_planning_missionplanning_missionplanner_debug_goalfootprintData;
    
    /// @brief Data for event, planning_missionplanning_missionplanner_debug_processingtimems
    oss::srv::MP2BPP::skeleton::events::planning_missionplanning_missionplanner_debug_processingtimems::SampleType m_planning_missionplanning_missionplanner_debug_processingtimemsData;
    
    /// @brief Data for event, planning_missionplanning_route
    oss::srv::MP2BPP::skeleton::events::planning_missionplanning_route::SampleType m_planning_missionplanning_routeData;
    
    /// @brief Data for event, planning_missionplanning_routemarker
    oss::srv::MP2BPP::skeleton::events::planning_missionplanning_routemarker::SampleType m_planning_missionplanning_routemarkerData;
    
    /// @brief Data for event, planning_missionplanning_state
    oss::srv::MP2BPP::skeleton::events::planning_missionplanning_state::SampleType m_planning_missionplanning_stateData;
};
 
} /// namespace port
} /// namespace aa
} /// namespace exe_missionplanner
 
#endif /// PARA_AA_GEN_SOFTWARE_COMPONENT_PPORT_EXE_MISSIONPLANNER_AA_PPORT_MP2BPP_H