///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, ARA::COM Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : impl_type_marker.h
/// IMPLEMENTATION DATA TYPE NAME     : Marker
/// GENERATED DATE                    : 2025-12-08 15:30:29
///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// CAUTION!! AUTOMATICALLY GENERATED FILE - DO NOT EDIT                                                   
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_ARA_COM_GEN_OSS_TYPE_VISUALIZATION_MSGS_MSG_CPP_IMPL_TYPE_MARKER_H
#define PARA_ARA_COM_GEN_OSS_TYPE_VISUALIZATION_MSGS_MSG_CPP_IMPL_TYPE_MARKER_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// @uptrace{SWS_CM_00402}
#include <cstdint>
#include <ara/core/structure.h>

#include "oss/type/builtin_interfaces/msg/impl_type_duration.h"
#include "oss/type/geometry_msgs/msg/impl_type_pose.h"
#include "oss/type/geometry_msgs/msg/impl_type_vector3.h"
#include "oss/type/impl_type_colorrgba_vector.h"
#include "oss/type/impl_type_marker_action.h"
#include "oss/type/impl_type_marker_type.h"
#include "oss/type/impl_type_point_vector.h"
#include "oss/type/impl_type_string.h"
#include "oss/type/impl_type_uvcoordinate_vector.h"
#include "oss/type/sensor_msgs/msg/impl_type_compressedimage.h"
#include "oss/type/std_msgs/msg/impl_type_colorrgba.h"
#include "oss/type/std_msgs/msg/impl_type_header.h"
#include "oss/type/visualization_msgs/msg/impl_type_meshfile.h"
#ifdef PARA_DDS_IMPLEMENTATION
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION FOR DDS
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "impl_type_marker.hpp"
#endif /// PARA_DDS_IMPLEMENTATION
/// @uptrace{SWS_CM_10375}
namespace oss
{
namespace type
{
namespace visualization_msgs
{
namespace msg
{
struct Marker
{
    oss::type::std_msgs::msg::Header header;
    oss::type::string ns;
    std::int32_t id;
    oss::type::Marker_type type;
    oss::type::Marker_action action;
    oss::type::geometry_msgs::msg::Pose pose;
    oss::type::geometry_msgs::msg::Vector3 scale;
    oss::type::std_msgs::msg::ColorRGBA color;
    oss::type::builtin_interfaces::msg::Duration lifetime;
    bool frame_locked;
    oss::type::Point_Vector points;
    oss::type::ColorRGBA_Vector colors;
    oss::type::string texture_resource;
    oss::type::sensor_msgs::msg::CompressedImage texture;
    oss::type::UVCoordinate_Vector uv_coordinates;
    oss::type::string text;
    oss::type::string mesh_resource;
    oss::type::visualization_msgs::msg::MeshFile mesh_file;
    bool mesh_use_embedded_materials;

    /// @brief constructor
    Marker() = default;
    Marker(const oss::type::std_msgs::msg::Header& _header, const oss::type::string& _ns, const std::int32_t& _id, const oss::type::Marker_type& _type, const oss::type::Marker_action& _action, const oss::type::geometry_msgs::msg::Pose& _pose, const oss::type::geometry_msgs::msg::Vector3& _scale, const oss::type::std_msgs::msg::ColorRGBA& _color, const oss::type::builtin_interfaces::msg::Duration& _lifetime, const bool& _frame_locked, const oss::type::Point_Vector& _points, const oss::type::ColorRGBA_Vector& _colors, const oss::type::string& _texture_resource, const oss::type::sensor_msgs::msg::CompressedImage& _texture, const oss::type::UVCoordinate_Vector& _uv_coordinates, const oss::type::string& _text, const oss::type::string& _mesh_resource, const oss::type::visualization_msgs::msg::MeshFile& _mesh_file, const bool& _mesh_use_embedded_materials)
        : header{_header}
        , ns{_ns}
        , id{_id}
        , type{_type}
        , action{_action}
        , pose{_pose}
        , scale{_scale}
        , color{_color}
        , lifetime{_lifetime}
        , frame_locked{_frame_locked}
        , points{_points}
        , colors{_colors}
        , texture_resource{_texture_resource}
        , texture{_texture}
        , uv_coordinates{_uv_coordinates}
        , text{_text}
        , mesh_resource{_mesh_resource}
        , mesh_file{_mesh_file}
        , mesh_use_embedded_materials{_mesh_use_embedded_materials}
    {
    }

    /// @note marker for serialize, don't touch
    PARA_STRUCTURE(Marker, header, ns, id, type, action, pose, scale, color, lifetime, frame_locked, points, colors, texture_resource, texture, uv_coordinates, text, mesh_resource, mesh_file, mesh_use_embedded_materials);
};
 
#ifdef PARA_DDS_IMPLEMENTATION
inline dds::oss::type::visualization_msgs::msg::Marker Marker_ConvertToDdsType(const oss::type::visualization_msgs::msg::Marker& src)
{
    dds::oss::type::visualization_msgs::msg::Marker dst;
    dst.header() = oss::type::std_msgs::msg::Header_ConvertToDdsType(src.header);
    dst.ns() = oss::type::string_ConvertToDdsType(src.ns);
    dst.id() = src.id;
    dst.type() = oss::type::Marker_type_ConvertToDdsType(src.type);
    dst.action() = oss::type::Marker_action_ConvertToDdsType(src.action);
    dst.pose() = oss::type::geometry_msgs::msg::Pose_ConvertToDdsType(src.pose);
    dst.scale() = oss::type::geometry_msgs::msg::Vector3_ConvertToDdsType(src.scale);
    dst.color() = oss::type::std_msgs::msg::ColorRGBA_ConvertToDdsType(src.color);
    dst.lifetime() = oss::type::builtin_interfaces::msg::Duration_ConvertToDdsType(src.lifetime);
    dst.frame_locked() = src.frame_locked;
    dst.points() = oss::type::Point_Vector_ConvertToDdsType(src.points);
    dst.colors() = oss::type::ColorRGBA_Vector_ConvertToDdsType(src.colors);
    dst.texture_resource() = oss::type::string_ConvertToDdsType(src.texture_resource);
    dst.texture() = oss::type::sensor_msgs::msg::CompressedImage_ConvertToDdsType(src.texture);
    dst.uv_coordinates() = oss::type::UVCoordinate_Vector_ConvertToDdsType(src.uv_coordinates);
    dst.text() = oss::type::string_ConvertToDdsType(src.text);
    dst.mesh_resource() = oss::type::string_ConvertToDdsType(src.mesh_resource);
    dst.mesh_file() = oss::type::visualization_msgs::msg::MeshFile_ConvertToDdsType(src.mesh_file);
    dst.mesh_use_embedded_materials() = src.mesh_use_embedded_materials;
    return dst;
}
 
inline oss::type::visualization_msgs::msg::Marker Marker_ConvertFromDdsType(const dds::oss::type::visualization_msgs::msg::Marker& src)
{
    oss::type::visualization_msgs::msg::Marker dst;
    dst.header = oss::type::std_msgs::msg::Header_ConvertFromDdsType(src.header());
    dst.ns = oss::type::string_ConvertFromDdsType(src.ns());
    dst.id = src.id();
    dst.type = oss::type::Marker_type_ConvertFromDdsType(src.type());
    dst.action = oss::type::Marker_action_ConvertFromDdsType(src.action());
    dst.pose = oss::type::geometry_msgs::msg::Pose_ConvertFromDdsType(src.pose());
    dst.scale = oss::type::geometry_msgs::msg::Vector3_ConvertFromDdsType(src.scale());
    dst.color = oss::type::std_msgs::msg::ColorRGBA_ConvertFromDdsType(src.color());
    dst.lifetime = oss::type::builtin_interfaces::msg::Duration_ConvertFromDdsType(src.lifetime());
    dst.frame_locked = src.frame_locked();
    dst.points = oss::type::Point_Vector_ConvertFromDdsType(src.points());
    dst.colors = oss::type::ColorRGBA_Vector_ConvertFromDdsType(src.colors());
    dst.texture_resource = oss::type::string_ConvertFromDdsType(src.texture_resource());
    dst.texture = oss::type::sensor_msgs::msg::CompressedImage_ConvertFromDdsType(src.texture());
    dst.uv_coordinates = oss::type::UVCoordinate_Vector_ConvertFromDdsType(src.uv_coordinates());
    dst.text = oss::type::string_ConvertFromDdsType(src.text());
    dst.mesh_resource = oss::type::string_ConvertFromDdsType(src.mesh_resource());
    dst.mesh_file = oss::type::visualization_msgs::msg::MeshFile_ConvertFromDdsType(src.mesh_file());
    dst.mesh_use_embedded_materials = src.mesh_use_embedded_materials();
    return dst;
}
#endif /// PARA_DDS_IMPLEMENTATION
} /// namespace msg
} /// namespace visualization_msgs
} /// namespace type
} /// namespace oss
#endif /// PARA_ARA_COM_GEN_OSS_TYPE_VISUALIZATION_MSGS_MSG_CPP_IMPL_TYPE_MARKER_H