///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, ARA::COM Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : impl_type_routestate.h
/// IMPLEMENTATION DATA TYPE NAME     : RouteState
/// GENERATED DATE                    : 2025-12-08 15:30:06
///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// CAUTION!! AUTOMATICALLY GENERATED FILE - DO NOT EDIT                                                   
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_ARA_COM_GEN_OSS_TYPE_TIER4_PLANNING_MSGS_MSG_CPP_IMPL_TYPE_ROUTESTATE_H
#define PARA_ARA_COM_GEN_OSS_TYPE_TIER4_PLANNING_MSGS_MSG_CPP_IMPL_TYPE_ROUTESTATE_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// @uptrace{SWS_CM_00402}
#include <ara/core/structure.h>
#include "oss/type/builtin_interfaces/msg/impl_type_time.h"
#include "oss/type/impl_type_routestate_state.h"
#ifdef PARA_DDS_IMPLEMENTATION
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION FOR DDS
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "impl_type_routestate.hpp"
#endif /// PARA_DDS_IMPLEMENTATION
/// @uptrace{SWS_CM_10375}
namespace oss
{
namespace type
{
namespace tier4_planning_msgs
{
namespace msg
{
struct RouteState
{
    oss::type::builtin_interfaces::msg::Time stamp;
    oss::type::RouteState_state state;

    /// @brief constructor
    RouteState() = default;
    RouteState(const oss::type::builtin_interfaces::msg::Time& _stamp, const oss::type::RouteState_state& _state)
        : stamp{_stamp}
        , state{_state}
    {
    }

    /// @note marker for serialize, don't touch
    PARA_STRUCTURE(RouteState, stamp, state);
};
 
#ifdef PARA_DDS_IMPLEMENTATION
inline dds::oss::type::tier4_planning_msgs::msg::RouteState RouteState_ConvertToDdsType(const oss::type::tier4_planning_msgs::msg::RouteState& src)
{
    dds::oss::type::tier4_planning_msgs::msg::RouteState dst;
    dst.stamp() = oss::type::builtin_interfaces::msg::Time_ConvertToDdsType(src.stamp);
    dst.state() = src.state;
    return dst;
}
 
inline oss::type::tier4_planning_msgs::msg::RouteState RouteState_ConvertFromDdsType(const dds::oss::type::tier4_planning_msgs::msg::RouteState& src)
{
    oss::type::tier4_planning_msgs::msg::RouteState dst;
    dst.stamp = oss::type::builtin_interfaces::msg::Time_ConvertFromDdsType(src.stamp());
    dst.state = src.state();
    return dst;
}
#endif /// PARA_DDS_IMPLEMENTATION
} /// namespace msg
} /// namespace tier4_planning_msgs
} /// namespace type
} /// namespace oss
#endif /// PARA_ARA_COM_GEN_OSS_TYPE_TIER4_PLANNING_MSGS_MSG_CPP_IMPL_TYPE_ROUTESTATE_H