///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, ARA::COM Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : impl_type_setwaypointroute_response.h
/// IMPLEMENTATION DATA TYPE NAME     : SetWaypointRoute_Response
/// GENERATED DATE                    : 2025-12-08 15:30:04
///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// CAUTION!! AUTOMATICALLY GENERATED FILE - DO NOT EDIT                                                   
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_ARA_COM_GEN_OSS_TYPE_TIER4_PLANNING_MSGS_SRV_CPP_IMPL_TYPE_SETWAYPOINTROUTE_RESPONSE_H
#define PARA_ARA_COM_GEN_OSS_TYPE_TIER4_PLANNING_MSGS_SRV_CPP_IMPL_TYPE_SETWAYPOINTROUTE_RESPONSE_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// @uptrace{SWS_CM_00402}
#include <ara/core/structure.h>
#include "oss/type/autoware_adapi_v1_msgs/msg/impl_type_responsestatus.h"
#ifdef PARA_DDS_IMPLEMENTATION
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION FOR DDS
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "impl_type_setwaypointroute_response.hpp"
#endif /// PARA_DDS_IMPLEMENTATION
/// @uptrace{SWS_CM_10375}
namespace oss
{
namespace type
{
namespace tier4_planning_msgs
{
namespace srv
{
struct SetWaypointRoute_Response
{
    oss::type::autoware_adapi_v1_msgs::msg::ResponseStatus status;

    /// @brief constructor
    SetWaypointRoute_Response() = default;
    SetWaypointRoute_Response(const oss::type::autoware_adapi_v1_msgs::msg::ResponseStatus& _status)
        : status{_status}
    {
    }

    /// @note marker for serialize, don't touch
    PARA_STRUCTURE(SetWaypointRoute_Response, status);
};
 
#ifdef PARA_DDS_IMPLEMENTATION
inline dds::oss::type::tier4_planning_msgs::srv::SetWaypointRoute_Response SetWaypointRoute_Response_ConvertToDdsType(const oss::type::tier4_planning_msgs::srv::SetWaypointRoute_Response& src)
{
    dds::oss::type::tier4_planning_msgs::srv::SetWaypointRoute_Response dst;
    dst.status() = oss::type::autoware_adapi_v1_msgs::msg::ResponseStatus_ConvertToDdsType(src.status);
    return dst;
}
 
inline oss::type::tier4_planning_msgs::srv::SetWaypointRoute_Response SetWaypointRoute_Response_ConvertFromDdsType(const dds::oss::type::tier4_planning_msgs::srv::SetWaypointRoute_Response& src)
{
    oss::type::tier4_planning_msgs::srv::SetWaypointRoute_Response dst;
    dst.status = oss::type::autoware_adapi_v1_msgs::msg::ResponseStatus_ConvertFromDdsType(src.status());
    return dst;
}
#endif /// PARA_DDS_IMPLEMENTATION
} /// namespace srv
} /// namespace tier4_planning_msgs
} /// namespace type
} /// namespace oss
#endif /// PARA_ARA_COM_GEN_OSS_TYPE_TIER4_PLANNING_MSGS_SRV_CPP_IMPL_TYPE_SETWAYPOINTROUTE_RESPONSE_H