///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : swc_motionvelocityplanner.h
/// SOFTWARE COMPONENT NAME           : Swc_motionvelocityplanner
/// GENERATED DATE                    : 2025-12-08 15:30:48
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_AA_GEN_SOFTWARE_COMPONENT_EXE_MOTIONVELOCITYPLANNER_AA_H
#define PARA_AA_GEN_SOFTWARE_COMPONENT_EXE_MOTIONVELOCITYPLANNER_AA_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "exe_motionvelocityplanner/aa/port/pport_mvp2ocp.h"
#include "exe_motionvelocityplanner/aa/port/rport_po2mvp.h"
#include "exe_motionvelocityplanner/aa/port/rport_scr2mvp.h"
 
#include "ara/log/logger.h"
#include "para/swc/port_pool.h"
 
namespace exe_motionvelocityplanner
{
namespace aa
{
 
class Swc_motionvelocityplanner
{
public:
    /// @brief Constructor
    Swc_motionvelocityplanner();
    
    /// @brief Destructor
    ~Swc_motionvelocityplanner();
    
    /// @brief Initialize software component
    bool Initialize();
    
    /// @brief Start software component
    void Start();
    
    /// @brief Terminate software component
    void Terminate();
    
    /// @brief Run software component
    void Run();
    
private:
    /// @brief Running status of software component
    bool m_running;
    
    /// @brief Pool of port
    ::para::swc::PortPool m_workers;
    
    /// @brief Logger for software component
    ara::log::Logger& m_logger;
    
    /// @brief Instance of Port {Swc_motionvelocityplanner.PPort_MVP2OCP}
    std::unique_ptr<exe_motionvelocityplanner::aa::port::PPort_MVP2OCP> m_PPort_MVP2OCP;
    
    /// @brief Instance of Port {Swc_motionvelocityplanner.RPort_PO2MVP}
    std::unique_ptr<exe_motionvelocityplanner::aa::port::RPort_PO2MVP> m_RPort_PO2MVP;
    
    /// @brief Instance of Port {Swc_motionvelocityplanner.RPort_SCr2MVP}
    std::unique_ptr<exe_motionvelocityplanner::aa::port::RPort_SCr2MVP> m_RPort_SCr2MVP;
};
 
} /// namespace aa
} /// namespace exe_motionvelocityplanner
 
#endif /// PARA_AA_GEN_SOFTWARE_COMPONENT_EXE_MOTIONVELOCITYPLANNER_AA_H